Song_ID: calib
Version:
  - 2
  - 1
  - 1
  - 3
  - 0
Genre_old: 6
Unknown: 24
Difficulty:
  - 3
  - 5
  - 5
  - 7
  - 0
Updated: false
Title: ソウルキャリバーⅡ
Genre_new: 0
Generation: 0
PreviewStartTime: 0
Pronunciation: ""