//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BarInfo : NSObject
{
    int _frameIndex;
    float _left;
    float _right;
}

@property(nonatomic) float right; // @synthesize right=_right;
@property(nonatomic) float left; // @synthesize left=_left;
@property(nonatomic) int frameIndex; // @synthesize frameIndex=_frameIndex;
- (id)description;

@end

