//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXMLParserDelegate-Protocol.h"

@class BGAnimationInfo, BGObjectInfo, NSDictionary, NSMutableDictionary, NSString;

@interface BGAnimationInfoFactory : NSObject <NSXMLParserDelegate>
{
    BGAnimationInfo *info_;	// 8 = 0x8
    NSString *name_;	// 16 = 0x10
    BGObjectInfo *object_;	// 24 = 0x18
    NSMutableDictionary *dict_;	// 32 = 0x20
    NSDictionary *animationAttributes_;	// 40 = 0x28
    NSDictionary *factorAttributes_;	// 48 = 0x30
    _Bool inScene_;	// 56 = 0x38
    _Bool inArray_;	// 57 = 0x39
    _Bool inObject_;	// 58 = 0x3a
    _Bool inAnimation_;	// 59 = 0x3b
    _Bool inAlign_;	// 60 = 0x3c
    _Bool inFlag_;	// 61 = 0x3d
    _Bool inFactor_;	// 62 = 0x3e
}

+ (id)infoForFile:(id)arg1;
- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

