//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BGPath;

@interface BGAnimationVariable : NSObject
{
    BGPath *path_;
    float value_;
    _Bool inherited_;
}

@property(nonatomic) _Bool inherited; // @synthesize inherited=inherited_;
@property(nonatomic) float value; // @synthesize value=value_;
@property(retain, nonatomic) BGPath *path; // @synthesize path=path_;
- (void)dealloc;

@end

