//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BGFunction.h"

@interface BGBSplineFunction : BGFunction
{
    float v0_;	// 16 = 0x10
    float v2_;	// 20 = 0x14
    float p1_;	// 24 = 0x18
    float duration_;	// 28 = 0x1c
}

+ (id)functionWithInitialValue:(float)arg1 controlValue:(float)arg2 finalValue:(float)arg3 duration:(float)arg4;
- (float)internalValueAtTime:(float)arg1;

@end

