//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableData, NSString, NSURLConnection, NSURLResponse;
@protocol BGDownloadDelegate;

@interface BGDownload : NSObject
{
    id <BGDownloadDelegate> delegate_;	// 8 = 0x8
    NSMutableData *data_;	// 16 = 0x10
    NSURLConnection *connection_;	// 24 = 0x18
    unsigned long long m_BgTask;	// 32 = 0x20
    double period_;	// 40 = 0x28
    NSString *key_;	// 48 = 0x30
    id object_;	// 56 = 0x38
    NSURLResponse *_response;	// 64 = 0x40
}

@property(readonly, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(readonly, nonatomic) NSString *cacheKey; // @synthesize cacheKey=key_;
@property(readonly, nonatomic) id object; // @synthesize object=object_;
- (void)endBackgroundTask;
- (void)beginBackgroundTask;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
@property(readonly, nonatomic) NSData *data;
- (void)removeCache;
- (void)cancel;
- (void)dealloc;
- (id)initWithRequest:(id)arg1 withObject:(id)arg2 delegate:(id)arg3;
- (id)initWithRequest:(id)arg1 withObject:(id)arg2 delegate:(id)arg3 period:(double)arg4;

@end

