//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSMutableData, NSString, NSURLConnection, NSURLResponse;

@interface BGDownload : NSObject
{
    id <BGDownloadDelegate> delegate_;
    NSMutableData *data_;
    NSURLConnection *connection_;
    unsigned long long m_BgTask;
    double period_;
    NSString *key_;
    id object_;
    NSURLResponse *_response;
}

@property(readonly, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(readonly, nonatomic) NSString *cacheKey; // @synthesize cacheKey=key_;
@property(readonly, nonatomic) id object; // @synthesize object=object_;
- (void)endBackgroundTask;
- (void)beginBackgroundTask;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
@property(readonly, nonatomic) NSData *data;
- (void)removeCache;
- (void)cancel;
- (void)dealloc;
- (id)initWithRequest:(id)arg1 withObject:(id)arg2 delegate:(id)arg3;
- (id)initWithRequest:(id)arg1 withObject:(id)arg2 delegate:(id)arg3 period:(double)arg4;

@end

