//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BGAnimation;

@interface BGGameChibi : NSObject
{
    struct _AGTEXTUREFRAMEGROUP *group_;
    BGAnimation *animation_;
    float x_;
    float y_;
    float ft_;
    float fx_;
    float fy_;
}

+ (id)chibiWithObjectInfo:(id)arg1 textureMap:(id)arg2 animationMap:(id)arg3 groupMap:(id)arg4;
@property(readonly, nonatomic) float y; // @synthesize y=y_;
@property(readonly, nonatomic) float x; // @synthesize x=x_;
- (void)renderGameChibi:(struct _GAME_CHIBI *)arg1;
- (void)updateGameChibi:(struct _GAME_CHIBI *)arg1;
- (void)setAnimationForGameChibi:(struct _GAME_CHIBI *)arg1;
- (void)dealloc;

@end

