//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface BGLayer : NSObject
{
    NSArray *objects_;
    NSArray *zsorted_;
    unsigned long long part_;
    SEL renderSelector_;
    struct CGPoint _offset;
}

+ (id)layerWithObjectInfoArray:(id)arg1 textureMap:(id)arg2 objectMap:(id)arg3 animationMap:(id)arg4 groupMap:(id)arg5;
+ (id)layerWithObjectInfoArray:(id)arg1 textureMap:(id)arg2 objectMap:(id)arg3 animationMap:(id)arg4 groupMap:(id)arg5 order:(int)arg6 numberOfObjects:(unsigned long long)arg7;
@property(nonatomic) struct CGPoint offset; // @synthesize offset=_offset;
@property(readonly, nonatomic) unsigned long long part; // @synthesize part=part_;
@property(readonly, nonatomic) NSArray *objects; // @synthesize objects=objects_;
- (void)updateRenderingOrder;
- (void)setupAGObjects;
- (id)objectContainsPoint:(struct CGPoint)arg1;
- (_Bool)isFinishedCompletelyAtTime:(float)arg1;
- (_Bool)isFinishedAtTime:(float)arg1;
- (void)renderObjectsWithOffset;
- (void)renderObjects;
- (void)render;
- (void)updateAtTime:(float)arg1;
- (void)startAnimationFromTime:(float)arg1 part:(unsigned long long)arg2;
- (void)dealloc;

@end

