//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BGVariable;

@interface BGObjectVariable : NSObject
{
    BGVariable *variable_;
    float offsetTime_;
}

@property(nonatomic) float offsetTime; // @synthesize offsetTime=offsetTime_;
@property(retain, nonatomic) BGVariable *variable; // @synthesize variable=variable_;
- (void)updateAGObject:(struct _AGOBJECT *)arg1 time:(float)arg2 alpha:(float *)arg3;
- (void)dealloc;

@end

