//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSString;

@interface BGObjectInfo : NSObject
{
    NSString *ipk_;	// 8 = 0x8
    NSString *group_;	// 16 = 0x10
    NSMutableDictionary *animations_;	// 24 = 0x18
    NSMutableDictionary *factors_;	// 32 = 0x20
    int align_;	// 40 = 0x28
    int flags_;	// 44 = 0x2c
    float t_;	// 48 = 0x30
    float z_;	// 52 = 0x34
    float w_;	// 56 = 0x38
    float h_;	// 60 = 0x3c
    int frameIndex_;	// 64 = 0x40
    BGObjectInfo *parent_;	// 72 = 0x48
    NSArray *xArray_;	// 80 = 0x50
    NSArray *yArray_;	// 88 = 0x58
    _Bool userInteractionEnabled_;	// 96 = 0x60
    int id_;	// 100 = 0x64
    struct CGSize hitRectSize_;	// 104 = 0x68
    int numberOfSiblings_;	// 120 = 0x78
    float dx_;	// 124 = 0x7c
    float dy_;	// 128 = 0x80
    float dz_;	// 132 = 0x84
    float dt_;	// 136 = 0x88
}

@property(nonatomic) float dt; // @synthesize dt=dt_;
@property(nonatomic) float dz; // @synthesize dz=dz_;
@property(nonatomic) float dy; // @synthesize dy=dy_;
@property(nonatomic) float dx; // @synthesize dx=dx_;
@property(nonatomic) int numberOfSiblings; // @synthesize numberOfSiblings=numberOfSiblings_;
@property(nonatomic) struct CGSize hitRectSize; // @synthesize hitRectSize=hitRectSize_;
@property(nonatomic) int id; // @synthesize id=id_;
@property(nonatomic) _Bool userInteractionEnabled; // @synthesize userInteractionEnabled=userInteractionEnabled_;
@property(retain, nonatomic) NSArray *yArray; // @synthesize yArray=yArray_;
@property(retain, nonatomic) NSArray *xArray; // @synthesize xArray=xArray_;
@property(retain, nonatomic) BGObjectInfo *parent; // @synthesize parent=parent_;
@property(nonatomic) int frameIndex; // @synthesize frameIndex=frameIndex_;
@property(nonatomic) float h; // @synthesize h=h_;
@property(nonatomic) float w; // @synthesize w=w_;
@property(nonatomic) float z; // @synthesize z=z_;
@property(nonatomic) float t; // @synthesize t=t_;
@property(nonatomic) int flags; // @synthesize flags=flags_;
@property(nonatomic) int align; // @synthesize align=align_;
@property(readonly, nonatomic) NSMutableDictionary *factors; // @synthesize factors=factors_;
@property(readonly, nonatomic) NSMutableDictionary *animations; // @synthesize animations=animations_;
@property(copy, nonatomic) NSString *group; // @synthesize group=group_;
@property(copy, nonatomic) NSString *ipk; // @synthesize ipk=ipk_;
- (void)dealloc;
- (id)init;

@end

