//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BGVariable;

@interface BGObjectVariable : NSObject
{
    BGVariable *variable_;	// 8 = 0x8
    float offsetTime_;	// 16 = 0x10
}

@property(nonatomic) float offsetTime; // @synthesize offsetTime=offsetTime_;
@property(retain, nonatomic) BGVariable *variable; // @synthesize variable=variable_;
- (void)updateAGObject:(struct _AGOBJECT *)arg1 time:(float)arg2 alpha:(float *)arg3;
- (void)dealloc;

@end

