//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BGFunction.h"

@interface BGPolygonFunction : BGFunction
{
    int count_;
    CDStruct_869f9c67 *indicators_;
}

+ (id)functionWithValues:(const float *)arg1 times:(const float *)arg2 count:(int)arg3;
+ (id)functionWithTimeIndicatorArray:(id)arg1;
- (float)internalValueAtTime:(float)arg1;
- (void)dealloc;

@end

