//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

@class BGLayer, BGScene;

@interface BGSceneBase : ISceneBase
{
    BGScene *scene_;
    BGLayer *layer_;
    double t0_;
    _Bool timeLocked_;
    float frame_;
    float adjustedFPS_;
    float animationSpeed_;
}

@property(nonatomic) float animationSpeed; // @synthesize animationSpeed=animationSpeed_;
- (float)time;

@end

