//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BGLayer, NSArray, NSDictionary;

@interface BGScene : NSObject
{
    NSDictionary *textureMap_;
    NSDictionary *groupMap_;
    NSArray *chibi_;
    BGLayer *dancer_;
    BGLayer *background_;
    BGLayer *bar_;
    BGLayer *clear_;
    BGLayer *fever_;
    BGLayer *taiko_;
    _Bool needsDefaultBar_;
}

+ (id)sceneWithInfo:(id)arg1;
@property(readonly, nonatomic) _Bool needsDefaultBar; // @synthesize needsDefaultBar=needsDefaultBar_;
@property(readonly, nonatomic) BGLayer *taiko; // @synthesize taiko=taiko_;
@property(readonly, nonatomic) BGLayer *fever; // @synthesize fever=fever_;
@property(readonly, nonatomic) BGLayer *clear; // @synthesize clear=clear_;
@property(readonly, nonatomic) BGLayer *bar; // @synthesize bar=bar_;
@property(readonly, nonatomic) BGLayer *background; // @synthesize background=background_;
@property(readonly, nonatomic) BGLayer *dancer; // @synthesize dancer=dancer_;
- (void)renderGameChibi:(struct _GAME_CHIBI *)arg1;
- (void)updateGameChibi:(struct _GAME_CHIBI *)arg1;
- (void)setAnimationForGameChibi:(struct _GAME_CHIBI *)arg1;
- (unsigned long long)chibiCount;
- (_Bool)hasTaikoTexture;
- (_Bool)hasFeverTextureOnly;
- (_Bool)hasFever;
- (_Bool)hasBarTexture;
- (_Bool)hasLowerBack;
- (_Bool)hasDancer;
- (_Bool)hasChibi;
- (void)dealloc;

@end

