//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BGSceneBase.h"

#import "UIWebViewDelegate.h"

@class BGSceneObject, NSString, UIActivityIndicatorView, UIWebView;

@interface BGSNSWebBrowser : BGSceneBase <UIWebViewDelegate>
{
    BGSceneObject *bgObject_;
    BGSceneObject *lObject_;
    BGSceneObject *rObject_;
    BGSceneObject *webViewObject_;
    UIWebView *webView_;
    UIActivityIndicatorView *activityIndicatorView_;
    _Bool errorOccurred_;
}

- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (int)stateFadeOut;
- (int)stateRun;
- (int)stateFadeIn;
- (int)update;
- (void)sceneStart;
- (void)processTouches;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)prepareStateToFadeOut;
- (void)fadeWebView:(float)arg1 part:(unsigned long long)arg2;
- (void)render;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)updateButtons;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

