//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ISceneManager, NSDictionary, NSError, NSMutableArray, NSMutableData, NSMutableDictionary, NSOperationQueue, NSSet, NSString, NSURLResponse, UIActivityIndicatorView;

@interface BGSNSManager : NSObject
{
    NSDictionary *dictionary_;
    NSOperationQueue *operationQueue_;
    NSMutableArray *cancellableOperations_;
    UIActivityIndicatorView *activityIndicatorView_;
    NSURLResponse *response_;
    NSMutableData *data_;
    NSError *error_;
    _Bool done_;
    NSDictionary *ngword_;
    NSDictionary *okword_;
    NSDictionary *doncoinProductInfoDictionary_;
    NSDictionary *dontamaTicketProductInfoDictionary_;
    NSMutableDictionary *suspendedTransactions_;
    NSSet *navigableDomains_;
    NSMutableArray *subscriptionTransactions_;
    _Bool busy_;
    _Bool _subscriptionValidationFailed;
    NSString *checksum_;
    NSString *userKey_;
    NSString *taikoban_;
    id <BGSNSConnection> connection_;
    ISceneManager *sceneManager_;
}

+ (id)createActivityIndicatorView;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedManager;
@property _Bool subscriptionValidationFailed; // @synthesize subscriptionValidationFailed=_subscriptionValidationFailed;
@property _Bool busy; // @synthesize busy=busy_;
@property(nonatomic) ISceneManager *sceneManager; // @synthesize sceneManager=sceneManager_;
@property(nonatomic) id <BGSNSConnection> connection; // @synthesize connection=connection_;
@property(readonly, nonatomic) NSString *taikoban; // @synthesize taikoban=taikoban_;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showAlertIfSubsciptionValidationFailed;
- (void)unregisterAllSubscriptions;
- (void)commitSubscriptionTransactions;
- (void)appendSubscriptionTransaction:(id)arg1;
- (_Bool)subscribedToSubscriptionID:(id)arg1;
- (id)loadReceiptExpiresDate:(id)arg1;
- (id)loadReceiptIdentifier:(id)arg1;
- (void)setConfidentialObject:(id)arg1 forKey:(id)arg2;
- (id)confidentialObjectForKey:(id)arg1 error:(id *)arg2;
- (id)confidentialObjectForKey:(id)arg1;
- (id)informationURLStringWithAppliType:(id)arg1 version:(id)arg2;
- (_Bool)isMatsuriDomain:(id)arg1;
- (_Bool)isNavigableDomain:(id)arg1;
- (void)showAlertViewWithError:(id)arg1 placeholder:(id)arg2 delegate:(id)arg3 tag:(int)arg4 cancelButton:(id)arg5 decideButton:(id)arg6;
- (void)showAlertViewWithError:(id)arg1 placeholder:(id)arg2 delegate:(id)arg3 tag:(int)arg4;
- (id)errorMessageWithInterfaceNumber:(unsigned long long)arg1;
- (_Bool)resumeTransactionForProductIdentifier:(id)arg1 delegate:(id)arg2;
- (_Bool)hasTransactionForProductIdentifier:(id)arg1;
- (_Bool)keepConsumableProductTransaction:(id)arg1;
@property(readonly, nonatomic) unsigned long long dontamaTicketProductInfoListCount;
@property(readonly, nonatomic) unsigned long long doncoinProductInfoListCount;
@property(readonly, nonatomic) const CDStruct_856ef1b3 *dontamaTicketProductInfoList;
@property(readonly, nonatomic) const CDStruct_856ef1b3 *doncoinProductInfoList;
- (void)removeActivityIndicator;
- (_Bool)isActivityIndicatorAnimating;
- (void)showActivityIndicator:(_Bool)arg1;
- (id)activityIndicatorView;
- (void)cancelAllRequests;
- (void)removeOperationFromCancellableOperations:(id)arg1;
- (id)requestInterfaceInBackgroundWithNumber:(unsigned long long)arg1 withObject:(id)arg2 delegate:(id)arg3;
- (id)requestInterfaceWithNumber:(unsigned long long)arg1 withObject:(id)arg2 delegate:(id)arg3;
- (id)requestInterfaceInternalWithNumber:(unsigned long long)arg1 withObject:(id)arg2 delegate:(id)arg3 cancellable:(_Bool)arg4;
@property(readonly, nonatomic) NSString *userKey; // @synthesize userKey=userKey_;
- (_Bool)censorNickname:(id)arg1;
- (id)replacedStringWithString:(id)arg1 fromString:(id)arg2 toString:(id)arg3;
- (_Bool)hasChecksum;
- (_Bool)hasUserKey;
@property(readonly, nonatomic) NSString *checksum; // @synthesize checksum=checksum_;
- (void)interface64:(id)arg1;
- (void)interface63:(id)arg1;
- (void)interface62:(id)arg1;
- (void)interface60:(id)arg1;
- (void)interface59:(id)arg1;
- (void)interface58:(id)arg1;
- (void)interface57:(id)arg1;
- (void)interface55:(id)arg1;
- (void)interface53:(id)arg1;
- (void)interface52:(id)arg1;
- (void)interface51:(id)arg1;
- (void)interface50:(id)arg1;
- (void)interface49:(id)arg1;
- (void)interface48:(id)arg1;
- (void)interface47:(id)arg1;
- (void)interface46:(id)arg1;
- (void)VerifyReceiptValidationCount:(id)arg1;
- (void)VerifyReceiptValidationDate:(id)arg1;
- (void)interface45:(id)arg1;
- (void)interface44:(id)arg1;
- (void)interface43:(id)arg1;
- (void)interface41:(id)arg1;
- (void)interface40:(id)arg1;
- (void)interface39:(id)arg1;
- (void)interface38:(id)arg1;
- (void)interface37:(id)arg1;
- (void)interface35:(id)arg1;
- (void)interface34:(id)arg1;
- (void)interface30:(id)arg1;
- (void)interface29:(id)arg1;
- (void)interface27:(id)arg1;
- (void)interface26:(id)arg1;
- (void)interface24:(id)arg1;
- (void)interface23:(id)arg1;
- (void)interface22:(id)arg1;
- (void)interface21:(id)arg1;
- (void)interface20:(id)arg1;
- (void)interface19:(id)arg1;
- (void)interface17:(id)arg1;
- (void)interface16:(id)arg1;
- (void)interface15:(id)arg1;
- (void)interface14:(id)arg1;
- (void)interface13:(id)arg1;
- (void)interface12:(id)arg1;
- (void)interface11:(id)arg1;
- (void)removeCacheOfInterfaceNumber:(unsigned long long)arg1;
- (id)cacheKeyForInterfaceNumber:(unsigned long long)arg1;
- (void)interface07:(id)arg1;
- (void)interface06:(id)arg1;
- (void)interface05:(id)arg1;
- (void)removeTransaction:(id)arg1;
- (void)saveTransaction:(id)arg1;
- (void)interface04:(id)arg1;
- (void)interface03:(id)arg1;
- (void)interface02:(id)arg1;
- (void)interface01:(id)arg1;
- (void)interface00:(id)arg1;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)interfaceNumber:(unsigned long long)arg1 userKey:(_Bool)arg2 components:(id)arg3 block:(CDUnknownBlockType)arg4;
- (id)contentType:(id)arg1;
- (id)connectWithInterfaceNumber:(unsigned long long)arg1 userKey:(_Bool)arg2 components:(id)arg3 response:(id *)arg4 error:(id *)arg5;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)encodeURIComponent:(id)arg1;
- (id)checksumStringWithDataString:(id)arg1;
- (void)addXHeadersToRequest:(id)arg1 userKey:(_Bool)arg2;
@property(readonly, nonatomic) NSString *appVersion;
@property(readonly, nonatomic) NSString *appName;
- (id)URLStringForInterfaceNumber:(unsigned long long)arg1;
- (id)URLStringForKey:(id)arg1;
- (id)arrayForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)saveUserKeyToUserDefaults:(id)arg1;
- (id)userKeyInUserDefaults;
- (void)clearChecksum;
- (id)autorelease;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

