//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BGSceneBase.h"

@class BGSceneObject, NSArray, NSMutableDictionary;

@interface BGSNSDialog : BGSceneBase
{
    BGSceneObject *bgObject_;
    BGSceneObject *windowObject_;
    BGSceneObject *selectedObject_;
    BGSceneObject *initialSelectedObject_;
    BGSceneObject *highlightObject_;
    BGSceneObject *textObject_;
    BGSceneObject *priceObject_;
    BGSceneObject *countObject_;
    BGSceneObject *digitObjects_[3];
    BGSceneObject *productNameObjects_[4];
    BGSceneObject *productPriceObjects_[4];
    struct _AGTEXTURE textures_[12];
    struct _AGTEXTUREFRAMEGROUP frameGroups_[12];
    int type_;
    NSMutableDictionary *userDataDictionary_;
    _Bool ready_;
    _Bool done_;
    _Bool bgCancel_;
    int selectedIndex_;
    int cancelIndex_;
    unsigned long long textIndex_;
    NSArray *products_;
    unsigned long long productIndex_;
    unsigned long long fadeOutMask_;
}

@property(nonatomic) unsigned long long fadeOutMask; // @synthesize fadeOutMask=fadeOutMask_;
@property(nonatomic) unsigned long long productIndex; // @synthesize productIndex=productIndex_;
@property(retain, nonatomic) NSArray *products; // @synthesize products=products_;
@property(nonatomic) unsigned long long textIndex; // @synthesize textIndex=textIndex_;
@property(nonatomic) _Bool bgCancel; // @synthesize bgCancel=bgCancel_;
@property(nonatomic) int cancelIndex; // @synthesize cancelIndex=cancelIndex_;
@property(readonly, nonatomic) int selectedIndex; // @synthesize selectedIndex=selectedIndex_;
@property(readonly, nonatomic) _Bool done; // @synthesize done=done_;
@property(readonly, nonatomic) _Bool ready; // @synthesize ready=ready_;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (int)stateFadeOut;
- (int)stateRun;
- (int)stateFadeIn;
- (int)update;
- (void)sceneStart;
- (void)processTouches;
- (void)render;
- (float)time;
- (void)sceneDestroy;
- (void)sceneLoad;
- (id)initWithManager:(id)arg1 type:(int)arg2 base01Group:(struct _AGTEXTUREFRAMEGROUP *)arg3 button01Group:(struct _AGTEXTUREFRAMEGROUP *)arg4 downloadGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 fukugenGroup:(struct _AGTEXTUREFRAMEGROUP *)arg6;
- (id)initWithManager:(id)arg1 type:(int)arg2;
- (void)loadWithType:(int)arg1 base01Group:(struct _AGTEXTUREFRAMEGROUP *)arg2 button01Group:(struct _AGTEXTUREFRAMEGROUP *)arg3 downloadGroup:(struct _AGTEXTUREFRAMEGROUP *)arg4 fukugenGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5;
- (void)selectObject:(id)arg1;
- (void)setupNumberObject:(id)arg1 index:(unsigned long long)arg2 number:(unsigned long long)arg3 align:(long long)arg4;
- (void)setupStringObject:(id)arg1 index:(unsigned long long)arg2 string:(id)arg3 align:(long long)arg4;
- (void)setupStringObject:(id)arg1 index:(unsigned long long)arg2 string:(id)arg3 align:(long long)arg4 bold:(_Bool)arg5;

@end

