//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BGSoundEffect : NSObject
{
    unsigned long long numberOfChannels_;	// 8 = 0x8
    unsigned long long nextChannel_;	// 16 = 0x10
    unsigned int *sources_;	// 24 = 0x18
    unsigned int *buffers_;	// 32 = 0x20
    struct ALCcontext_struct *context_;	// 40 = 0x28
    struct ALCdevice_struct *device_;	// 48 = 0x30
}

- (void)setGain:(float)arg1;
- (void)resume;
- (void)suspend;
- (void)stopChannel:(int)arg1;
- (unsigned long long)playBuffer:(unsigned int)arg1 gain:(float)arg2;
- (unsigned long long)findAvailableChannel;
- (void)dealloc;
- (id)initWithNumberOfChannels:(unsigned long long)arg1;

@end

