//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BGSoundEffect : NSObject
{
    unsigned long long numberOfChannels_;
    unsigned long long nextChannel_;
    unsigned int *sources_;
    unsigned int *buffers_;
    struct ALCcontext_struct *context_;
    struct ALCdevice_struct *device_;
}

- (void)setGain:(float)arg1;
- (void)resume;
- (void)suspend;
- (void)stopChannel:(int)arg1;
- (unsigned long long)playBuffer:(unsigned int)arg1 gain:(float)arg2;
- (unsigned long long)findAvailableChannel;
- (void)dealloc;
- (id)initWithNumberOfChannels:(unsigned long long)arg1;

@end

