//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BGNode, BGPath, NSArray;

@interface BGVariable : NSObject
{
    int state_;
    BGNode *node_;
    float t0_;
    unsigned long long index_;
    BGPath *path_;
    NSArray *edges_;
    float duration_;
    int loopCount_;
    float loopTime_;
    float defaultValue_;
    float offsetValue_;
}

+ (id)variableWithPath:(id)arg1;
@property(nonatomic) float offsetValue; // @synthesize offsetValue=offsetValue_;
@property(nonatomic) float defaultValue; // @synthesize defaultValue=defaultValue_;
@property(readonly, nonatomic) int state; // @synthesize state=state_;
- (int)intValueAtTime:(float)arg1;
- (float)valueAtTime:(float)arg1;
- (void)setPath:(id)arg1;
- (void)reset;
- (void)dealloc;

@end

