//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CollaboInfo, ISceneSongSelect, ISongInfo;

@interface BoxInfo : NSObject
{
    _Bool _check;
    _Bool _sumi;
    _Bool _canTrialListen;
    _Bool _newFlag;
    unsigned int _type;
    ISongInfo *_songInfo;
    CollaboInfo *_collaboInfo;
    ISceneSongSelect *_delegate;
}

@property(nonatomic) _Bool newFlag; // @synthesize newFlag=_newFlag;
@property(nonatomic) _Bool canTrialListen; // @synthesize canTrialListen=_canTrialListen;
@property(nonatomic) _Bool sumi; // @synthesize sumi=_sumi;
@property(nonatomic) _Bool check; // @synthesize check=_check;
@property(nonatomic) ISceneSongSelect *delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CollaboInfo *collaboInfo; // @synthesize collaboInfo=_collaboInfo;
@property(retain, nonatomic) ISongInfo *songInfo; // @synthesize songInfo=_songInfo;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
- (void)renderSideBar:(struct CGPoint *)arg1 boxIndex:(int)arg2;
- (int)getWidth;
- (void)dealloc;

@end

