//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TOSBaseDlg.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIControl, UITextField;

@interface CheckAgeDlg : TOSBaseDlg <UITextFieldDelegate>
{
    NSString *tosurl;	// 352 = 0x160
    UITextField *texbirth[3];	// 360 = 0x168
    UIControl *btmctrl;	// 384 = 0x180
    struct CGRect btmrect;	// 392 = 0x188
}

+ (CDStruct_08b27754 *)getDefaultLayoutErrorLoop;
+ (CDStruct_08b27754 *)getDefaultLayout;
- (id).cxx_construct;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)setViewController:(id)arg1 ReturnDlg:(id)arg2;
- (void)BtnKeybordHidden:(id)arg1;
- (void)BtnActionReturn:(id)arg1;
- (void)BtnActionAgree:(id)arg1;
- (void)BtnActionPolicy:(id)arg1;
- (id)initWithURLString:(id)arg1 Manager:(id)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

