//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TOSBaseDlg.h"

@class NSString, UITextField;

@interface CheckAgeConfirmDlg : TOSBaseDlg
{
    UITextField *tfbirthday;
    NSString *birthdaystr;
    NSString *tosurl;
}

+ (CDStruct_08b27754 *)getDefaultLayout;
- (void)setBirthDayText:(id)arg1;
- (void)BtnActionNega:(id)arg1;
- (void)BtnActionPosi:(id)arg1;
- (void)dealloc;
- (id)initWithURLString:(id)arg1 Manager:(id)arg2;
- (void)viewDidLoad;

@end

