//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ISongInfo, NSString;

@interface CollaboInfo : NSObject
{
    struct _AGTEXTURE texture[2];
    struct _AGTEXTUREFRAMEGROUP frameGroup[2];
    struct _AGOBJECT object[2];
    NSString *collaboID;
    NSString *productID;
    NSString *musicID;
    NSString *datPath;
    unsigned int fileSize;
    unsigned int checkSum;
    int priority;
    unsigned int collaboSongType;
    ISongInfo *_songInfo;
    NSString *_endDate;
    NSString *_endDateExercise;
    NSString *_endDateLongest;
    NSString *_multiPurposeField;
}

@property(copy, nonatomic) NSString *multiPurposeField; // @synthesize multiPurposeField=_multiPurposeField;
@property(copy, nonatomic) NSString *endDateLongest; // @synthesize endDateLongest=_endDateLongest;
@property(copy, nonatomic) NSString *endDateExercise; // @synthesize endDateExercise=_endDateExercise;
@property(copy, nonatomic) NSString *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) ISongInfo *songInfo; // @synthesize songInfo=_songInfo;
- (_Bool)createTexture:(id)arg1 musicDirPath:(id)arg2;
- (void)dealloc;

@end

