//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ISongInfo, NSString;

@interface CollaboInfo : NSObject
{
    struct _AGTEXTURE texture[2];	// 8 = 0x8
    struct _AGTEXTUREFRAMEGROUP frameGroup[2];	// 120 = 0x78
    struct _AGOBJECT object[2];	// 168 = 0xa8
    NSString *collaboID;	// 280 = 0x118
    NSString *productID;	// 288 = 0x120
    NSString *musicID;	// 296 = 0x128
    NSString *datPath;	// 304 = 0x130
    unsigned int fileSize;	// 312 = 0x138
    unsigned int checkSum;	// 316 = 0x13c
    int priority;	// 320 = 0x140
    unsigned int collaboSongType;	// 324 = 0x144
    ISongInfo *_songInfo;	// 328 = 0x148
    NSString *_endDate;	// 336 = 0x150
    NSString *_endDateExercise;	// 344 = 0x158
    NSString *_endDateLongest;	// 352 = 0x160
    NSString *_multiPurposeField;	// 360 = 0x168
}

@property(copy, nonatomic) NSString *multiPurposeField; // @synthesize multiPurposeField=_multiPurposeField;
@property(copy, nonatomic) NSString *endDateLongest; // @synthesize endDateLongest=_endDateLongest;
@property(copy, nonatomic) NSString *endDateExercise; // @synthesize endDateExercise=_endDateExercise;
@property(copy, nonatomic) NSString *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) ISongInfo *songInfo; // @synthesize songInfo=_songInfo;
- (_Bool)createTexture:(id)arg1 musicDirPath:(id)arg2;
- (void)dealloc;

@end

