//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TOSBaseDlg.h"

@class NSString, UITextField;

@interface DisplayAgeDataDlg : TOSBaseDlg
{
    UITextField *tfbirthday;	// 352 = 0x160
    NSString *birthdaystr;	// 360 = 0x168
}

+ (CDStruct_08b27754 *)getDefaultLayout;
- (void)setBirthDayText:(id)arg1;
- (void)BtnActionReturn:(id)arg1;
- (void)viewDidLoad;

@end

