//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IMemberInfoForVSSettings : NSObject
{
    NSString *m_strMemberName;
    unsigned long long m_intMemberName;
    int m_memberLength;
}

@property(nonatomic) int memberLength; // @synthesize memberLength=m_memberLength;
@property(nonatomic) unsigned long long intMemberName; // @synthesize intMemberName=m_intMemberName;
@property(retain, nonatomic) NSString *strMemberName; // @synthesize strMemberName=m_strMemberName;
- (void)dealloc;
- (id)init;

@end

