//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BGSceneBase.h"

#import "SceneDialogDelegate-Protocol.h"

@class ISceneDialog, NSMutableArray, NSString, TaikoNumberLabel, TaikoSceneNode, TaikoTextureCache, TaikoWindow;

@interface ISceneExerciseBonusDialog : BGSceneBase <SceneDialogDelegate>
{
    int pauseState_;	// 108 = 0x6c
    int pauseCounter_;	// 112 = 0x70
    unsigned int pauseBackColor_;	// 116 = 0x74
    float partsAlpha_;	// 120 = 0x78
    struct CGRect arrowCollisions_[2];	// 128 = 0x80
    int page_;	// 192 = 0xc0
    int pageType_;	// 196 = 0xc4
    TaikoTextureCache *textureCache_;	// 200 = 0xc8
    int stockedPoint_;	// 208 = 0xd0
    int totalPoint_;	// 212 = 0xd4
    int month_;	// 216 = 0xd8
    int day_;	// 220 = 0xdc
    NSMutableArray *rankingBonusList_;	// 224 = 0xe0
    float prevNumberOffsetX_;	// 232 = 0xe8
    ISceneDialog *frontDialog_;	// 240 = 0xf0
    TaikoSceneNode *goukeiNode_;	// 248 = 0xf8
    TaikoSceneNode *getNode_;	// 256 = 0x100
    TaikoSceneNode *pointNode_;	// 264 = 0x108
    TaikoNumberLabel *totalNumberLabel_;	// 272 = 0x110
    TaikoSceneNode *plateLeftNode_;	// 280 = 0x118
    TaikoSceneNode *plateMiddleNode_;	// 288 = 0x120
    TaikoSceneNode *plateRightNode_;	// 296 = 0x128
    TaikoWindow *detailWindow_;	// 304 = 0x130
    struct _AGOBJECT closeButtonObject_[2];	// 312 = 0x138
    struct _AGOBJECT arrowObject_[4];	// 424 = 0x1a8
    struct _AGOBJECT titleObject_[2];	// 648 = 0x288
    struct _AGOBJECT dateDigitObject_[2];	// 760 = 0x2f8
    struct _AGOBJECT nameObject_;	// 872 = 0x368
    struct _AGOBJECT noticeObject_;	// 928 = 0x3a0
    struct _AGOBJECT goukeiObject_;	// 984 = 0x3d8
    struct _AGOBJECT plateObject_[2];	// 1040 = 0x410
    struct _AGOBJECT pointObject_;	// 1152 = 0x480
    struct _AGOBJECT rankObject_;	// 1208 = 0x4b8
    struct _AGOBJECT pObject_;	// 1264 = 0x4f0
    struct _AGOBJECT rankOutObject_;	// 1320 = 0x528
    struct _AGOBJECT rankNoneObject_;	// 1376 = 0x560
    struct _AGOBJECT difficultyObject_[5];	// 1432 = 0x598
    struct _AGOBJECT numberObject_[4];	// 1712 = 0x6b0
    TaikoNumberLabel *prevNumberLabel_;	// 1936 = 0x790
    int _pageNum;	// 1944 = 0x798
}

@property(readonly, nonatomic) int pageNum; // @synthesize pageNum=_pageNum;
- (void)sceneDialogDidEnable:(id)arg1;
- (void)sceneDialog:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)sceneDialog:(id)arg1 selectedButtonAtIndex:(int)arg2;
- (void)changePage:(int)arg1;
- (void)preloadCache;
- (_Bool)checkCacheComplete;
- (void)updateData:(id)arg1;
- (int)stateDetailDialog;
- (int)stateFrontDialog;
- (void)renderRank:(id)arg1 index:(int)arg2 originX:(float)arg3 originY:(float)arg4;
- (void)renderDate:(struct _AGOBJECT *)arg1 slashX:(int)arg2 doubleDigitX:(int)arg3 monthX:(int)arg4 dayX:(int)arg5 dayDist:(int)arg6;
- (void)renderBoardRelative:(float)arg1;
- (void)render;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)setupPlateWithX:(float)arg1 y:(float)arg2 width:(float)arg3;
- (void)dealloc;
- (id)initWithManager:(id)arg1 tfgFrontWindow:(struct _AGTEXTUREFRAMEGROUP *)arg2 tfgFrontTitle:(struct _AGTEXTUREFRAMEGROUP *)arg3 tfgFrontButton:(struct _AGTEXTUREFRAMEGROUP *)arg4 tfgFrontChoice:(struct _AGTEXTUREFRAMEGROUP *)arg5 tfgMisc:(struct _AGTEXTUREFRAMEGROUP *)arg6 tfgDigit:(struct _AGTEXTUREFRAMEGROUP *)arg7 tfgDetailWindow:(struct _AGTEXTUREFRAMEGROUP *)arg8 tfgArrow:(struct _AGTEXTUREFRAMEGROUP *)arg9 tfgMisc2:(struct _AGTEXTUREFRAMEGROUP *)arg10 tfgDigit2:(struct _AGTEXTUREFRAMEGROUP *)arg11 tfgDigit3:(struct _AGTEXTUREFRAMEGROUP *)arg12 tfgDigit4:(struct _AGTEXTUREFRAMEGROUP *)arg13 tfgItemPlate:(struct _AGTEXTUREFRAMEGROUP *)arg14;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

