//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "BGSNSInterfaceDelegate.h"
#import "UIAlertViewDelegate.h"

@class ISceneBonuspoint, ISceneNamePlate, NSDateFormatter, NSString, TaikoPrizeManager, TaikoTextureCache;

@interface IScenePrizeList : ISceneBase <BGSNSInterfaceDelegate, UIAlertViewDelegate>
{
    int m_NextScene;
    int m_FadeCounter;
    float m_BackScrollSpeed;
    float m_BackPosition;
    _Bool isListGotten_;
    _Bool hiddenDateFlagList_[6];
    NSDateFormatter *dateFormatter_;
    int pageNum_;
    int page_;
    ISceneBonuspoint *sceneBonuspoint_;
    ISceneNamePlate *sceneNamePlate_;
    TaikoPrizeManager *deliverPrizeManager_;
    TaikoTextureCache *iconTextureCache_;
    TaikoTextureCache *titleTextureCache_;
    struct _AGTEXTURE mainTexture_;
    struct _AGTEXTUREFRAMEGROUP tfgBackButton_;
    struct _AGTEXTUREFRAMEGROUP tfgBonuspointPlate_;
    struct _AGTEXTUREFRAMEGROUP tfgBonuspointDigit_;
    struct _AGTEXTUREFRAMEGROUP tfgBack_;
    struct _AGTEXTUREFRAMEGROUP tfgTitle_;
    struct _AGTEXTUREFRAMEGROUP tfgPlate_;
    struct _AGTEXTUREFRAMEGROUP tfgBar_;
    struct _AGTEXTUREFRAMEGROUP tfgArrow_;
    struct _AGTEXTUREFRAMEGROUP tfgNumber_;
    struct _AGTEXTUREFRAMEGROUP tfgNewIcon_;
    struct _AGTEXTUREFRAMEGROUP tfgType_;
    struct _AGTEXTUREFRAMEGROUP tfgIcon_;
    struct _AGTEXTUREFRAMEGROUP tfgMade_;
    struct _AGTEXTUREFRAMEGROUP tfgDateNumber_;
    struct _AGTEXTUREFRAMEGROUP tfgSecret_;
    struct _AGOBJECT backButtonObject_;
    struct _AGOBJECT backObject_;
    struct _AGOBJECT titleObject_;
    struct _AGOBJECT plateObject_;
    struct _AGOBJECT barObject_;
    struct _AGOBJECT arrowLeftObject_;
    struct _AGOBJECT arrowRightObject_;
    struct _AGOBJECT numberLeftObject_[2];
    struct _AGOBJECT numberRightObject_[2];
    struct _AGOBJECT slashObject_;
    struct _AGOBJECT nameObject_;
    struct _AGOBJECT newIconObject_;
    struct _AGOBJECT typeObject_;
    struct _AGOBJECT iconObject_;
    struct _AGOBJECT madeObject_;
    struct _AGOBJECT yearObject_[4];
    struct _AGOBJECT monthObject_[2];
    struct _AGOBJECT dayObject_[2];
    struct _AGOBJECT hourObject_[2];
    struct _AGOBJECT minuteObject_[2];
    struct _AGOBJECT slash2Object_;
    struct _AGOBJECT colonObject_;
    struct _AGOBJECT secretObject_;
}

- (_Bool)isHiddenDate:(id)arg1;
- (void)goBackToFukubiki;
- (void)preloadPage:(int)arg1;
- (void)changePage:(int)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (int)stateWaitForList;
- (int)stateRun;
- (void)renderPanel;
- (void)render;
- (void)updateAnimation;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

