//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "BGDownloadDelegate.h"
#import "BGSNSInterfaceDelegate.h"
#import "SKProductsRequestDelegate.h"
#import "SceneDialogDelegate.h"
#import "UIAlertViewDelegate.h"

@class BGDownload, ISceneDialog, ISceneNamePlate, NSArray, NSCache, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSTimer, TaikoProgressIndicator, TaikoRestore, UIActivityIndicatorView, UIButton;

@interface ISceneStore : ISceneBase <UIAlertViewDelegate, SKProductsRequestDelegate, BGSNSInterfaceDelegate, BGDownloadDelegate, SceneDialogDelegate>
{
    UIActivityIndicatorView *m_pIndBannerLoad;
    UIButton *m_pButtonBanner;
    NSString *m_szBannerID;
    NSString *m_szBannerLinkURL;
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTURE *m_PackageTitleTexture;
    struct _AGTEXTURE *m_PackageIconTexture;
    struct _AGTEXTURE m_PackageDetailsTitleTexture;
    struct _AGTEXTURE m_PackageSongListTexture;
    struct _AGTEXTURE m_PackageDescriptionTexture;
    struct _AGTEXTURE m_PackagePriceTexture;
    struct _AGTEXTURE m_PackageDescriptionImageTexture;
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BarFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BuyButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DetailsButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_ExpandingBarFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DetailsCloseButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DetailsBuyButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DownloadFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_NameFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_RestoreButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP *m_PackageTitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP *m_PackageIconFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_PackageDetailsTitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_PackageSongListFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_PackageDescriptionFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_PackagePriceFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_PackageDescriptionImageFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_ArrowFrameGroup;
    struct _AGOBJECT m_BackObject;
    struct _AGOBJECT m_TitleObject;
    struct _AGOBJECT m_BarObject;
    struct _AGOBJECT m_PackageIconObject;
    struct _AGOBJECT m_PackageTitleObject;
    struct _AGOBJECT m_BuyButtonObject;
    struct _AGOBJECT m_DetailsButtonObject;
    struct _AGOBJECT m_ExpandingBarObject[3];
    struct _AGOBJECT m_DetailsTitleObject;
    struct _AGOBJECT m_DetailsSongListObject;
    struct _AGOBJECT m_DetailsDescriptionObject;
    struct _AGOBJECT m_DetailsPriceObject;
    struct _AGOBJECT m_DetailsCloseButtonObject;
    struct _AGOBJECT m_DetailsBuyButtonObject;
    struct _AGOBJECT m_BackButtonObject;
    struct _AGOBJECT m_RestoreButtonObject;
    struct _AGOBJECT m_TokusyouButtonObject;
    struct _AGOBJECT m_ArrowObject[2];
    struct _AGTEXTURE m_BannerTexture;
    struct _AGTEXTUREFRAMEGROUP m_BannerFrameGroup;
    struct _AGOBJECT m_BannerObject;
    struct _AGTEXTUREFRAMEGROUP m_TrialListenFrameGroup;
    struct _AGOBJECT m_TrialListenNormalBG;
    struct _AGOBJECT m_TrialListenExtraBG;
    struct _AGOBJECT m_TrialListenNormalNgBG;
    struct _AGOBJECT m_TrialListenExtraNgBG;
    struct _AGOBJECT m_TrialListenPush;
    struct _AGOBJECT m_TrialListenWait;
    struct _AGOBJECT m_TrialListenAnime;
    struct _AGOBJECT m_TrialListenNg;
    int m_TrialListenID;
    int m_TrialListenTouchingID;
    NSString *m_TrialListenDownloadingSongID;
    int m_TrialListenCounter;
    UIButton *m_TrialListenButton[7];
    UIActivityIndicatorView *m_TrialListenIndicator;
    struct CGPoint m_TrialListenButtonPos[7];
    struct CGPoint m_TrialListenIconPos[7];
    _Bool m_TrialListenAllowedFlags[7];
    _Bool m_TrialListenNGAll;
    NSCache *m_TrialListenCache;
    struct _AGTEXTUREFRAMEGROUP m_RestoreSongsDialogWindowFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_RestoreSongsDialogMessageFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DownloadSongsDialogWindowFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DownloadSongsDialogMessageFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DownloadSongsDialogButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DownloadSongsDialogChoiceFrameGroup;
    float m_BarPosition;
    float m_BarSpace;
    float m_DetailsButtonPosition;
    float m_fBlackBottomAddy;
    float m_ScrollSpeed;
    float m_ScrollStartPosition;
    float m_ScrollPosition;
    float m_MaxScrollPosition;
    struct CGPoint m_ScrollTouchPoint;
    struct CGRect m_ScrollAreaRect;
    NSArray *m_PackageArray;
    NSDictionary *m_PackageDictionary;
    int m_SelectedProduct;
    unsigned long long m_DownloadedSize;
    unsigned long long m_TotalFileSize;
    int m_RestoredPackNum;
    int m_TotalPackNum;
    int m_AnimationCounter;
    int m_FadeCounter;
    _Bool m_ShowBars;
    _Bool m_ShowDetails;
    _Bool m_ScrollEnabled;
    _Bool m_Scrolling;
    NSString *purchasingProductIdentifier_;
    float m_ArrowMinPosition;
    float m_ArrowMaxPosition;
    int m_ArrowAnimationCounter;
    _Bool m_nVisibleArrow;
    ISceneNamePlate *m_SceneNamePlate;
    ISceneDialog *m_RestoreSongsDialog;
    ISceneDialog *m_DownloadSongsDialog;
    NSMutableDictionary *m_Transactions;
    NSMutableArray *m_ImageDownloads;
    TaikoRestore *m_TaikoRestore;
    BGDownload *m_SongDownload;
    TaikoProgressIndicator *m_ProgressIndicator;
    NSString *m_BootPackageID;
    _Bool m_ShowCheckAgeDlg;
    UIActivityIndicatorView *m_DescriptionImageLoading;
    struct _AGOBJECT m_DetailsDescriptionImageObject;
    _Bool m_ShowDetailsDescriptionImage;
    _Bool m_BannerButtonHidden;
    NSTimer *taikoControllerDisconnectionWaitTimer_;
}

+ (void)setBuyFlagToPackage:(id)arg1;
- (void)onTouchUpInsideButtonTrialListen:(id)arg1;
- (void)onTouchDragExitButtonTrialListen:(id)arg1;
- (void)onTouchDownButtonTrialListen:(id)arg1;
- (void)onTouchCancelButtonTrialListen:(id)arg1;
- (void)buttonBanner;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)startDownloadingTrialListen:(int)arg1;
- (void)finishTrialListen;
- (void)disableTrialListen;
- (void)enableTrialListen;
- (void)checkTaikoControllerDisconnection;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)requestDidFinish:(id)arg1;
- (void)transactionFailedWithTransaction:(id)arg1;
- (_Bool)transactionCompletedWithTransaction:(id)arg1;
- (void)sceneDialog:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)sceneDialog:(id)arg1 selectedButtonAtIndex:(int)arg2;
- (void)gotoMenu;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (int)stateDialogDownload;
- (int)stateDialogRestore;
- (void)restoreTransactionsFailedWithError:(id)arg1;
- (void)restoreTransactionsCompleted;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (int)stateLoading;
- (int)stateDownloadCompleted;
- (int)stateDownload;
- (int)stateRestorePackCompleted;
- (int)stateRestorePack;
- (int)stateIdle;
- (void)ExitDlg:(int)arg1 Result:(int)arg2;
- (int)stateRun;
- (void)finishShowingDetails;
- (void)ExitCheckAgeDlg:(int)arg1 Result:(int)arg2;
- (void)buy;
- (void)renderCommon;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)requestLoadingList;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)finishDialog;
- (void)finishPurchase:(id)arg1;
- (void)startDownload;
- (void)didFinishLoadingList:(id)arg1;
- (void)requestLoadingBanner;
- (void)didFinishLoadingBanner:(id)arg1;
- (void)downloadImageWithURLString:(id)arg1 index:(int)arg2;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)showRetryDialog:(long long)arg1;
- (void)alertFailureWithTitle:(id)arg1 message:(id)arg2 tag:(int)arg3;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)hideBannerButton:(_Bool)arg1;
- (void)downloadDidFinish:(id)arg1;
- (_Bool)checkDownloadedMusicData:(id)arg1 song:(id)arg2;
- (void)captureBanner;
- (void)finishLoadingBanner;
- (void)setBannerButtonHidden:(_Bool)arg1;
- (int)update;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

