//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneBase.h"

#import "SceneDialogDelegate-Protocol.h"

@class ISceneDialog, NSString, TaikoAction, TaikoSceneNode;

@interface ISceneVDrumsSettings : ISceneBase <SceneDialogDelegate>
{
    unsigned char settings_[2][16];	// 72 = 0x48
    unsigned int currentType_;	// 104 = 0x68
    unsigned int nextType_;	// 108 = 0x6c
    int currentPart_;	// 112 = 0x70
    int nextPart_;	// 116 = 0x74
    float scrollX_;	// 120 = 0x78
    float targetX_;	// 124 = 0x7c
    int scrollCount_;	// 128 = 0x80
    _Bool changed_;	// 132 = 0x84
    int fadeCount_;	// 136 = 0x88
    struct _AGTEXTURE texture_;	// 144 = 0x90
    struct _AGTEXTUREFRAMEGROUP titleFrameGroup_;	// 200 = 0xc8
    struct _AGTEXTUREFRAMEGROUP contentFrameGroup_;	// 224 = 0xe0
    struct _AGTEXTUREFRAMEGROUP cursorFrameGroup_;	// 248 = 0xf8
    struct _AGTEXTUREFRAMEGROUP nameFrameGroup_;	// 272 = 0x110
    struct _AGTEXTUREFRAMEGROUP rimmedNameFrameGroup_;	// 296 = 0x128
    struct _AGTEXTUREFRAMEGROUP namePlateFrameGroup_;	// 320 = 0x140
    struct _AGTEXTUREFRAMEGROUP inputFrameGroup_;	// 344 = 0x158
    struct _AGTEXTUREFRAMEGROUP backButtonFrameGroup_;	// 368 = 0x170
    struct _AGTEXTUREFRAMEGROUP resetButtonFrameGroup_;	// 392 = 0x188
    struct _AGTEXTUREFRAMEGROUP changeButtonFrameGroup_;	// 416 = 0x1a0
    struct _AGTEXTUREFRAMEGROUP leftButtonFrameGroup_;	// 440 = 0x1b8
    struct _AGTEXTUREFRAMEGROUP rightButtonFrameGroup_;	// 464 = 0x1d0
    struct _AGTEXTUREFRAMEGROUP resetDialogWindowFrameGroup_;	// 488 = 0x1e8
    struct _AGTEXTUREFRAMEGROUP resetDialogMessageFrameGroup_;	// 512 = 0x200
    struct _AGTEXTUREFRAMEGROUP resetDialogButtonFrameGroup_;	// 536 = 0x218
    struct _AGTEXTUREFRAMEGROUP resetDialogChoiceFrameGroup_;	// 560 = 0x230
    struct _AGTEXTUREFRAMEGROUP changeDialogWindowFrameGroup_;	// 584 = 0x248
    struct _AGTEXTUREFRAMEGROUP changeDialogMessageFrameGroup_;	// 608 = 0x260
    struct _AGTEXTUREFRAMEGROUP changeDialogButtonFrameGroup_;	// 632 = 0x278
    struct _AGTEXTUREFRAMEGROUP changeDialogChoiceFrameGroup_;	// 656 = 0x290
    struct _AGOBJECT titleObject_;	// 680 = 0x2a8
    struct _AGOBJECT contentObject_;	// 736 = 0x2e0
    struct _AGOBJECT nameObject_;	// 792 = 0x318
    struct _AGOBJECT namePlateObject_;	// 848 = 0x350
    struct _AGOBJECT inputObject_;	// 904 = 0x388
    struct _AGOBJECT backButtonObject_;	// 960 = 0x3c0
    struct _AGOBJECT resetButtonObject_;	// 1016 = 0x3f8
    struct _AGOBJECT changeButtonObject_;	// 1072 = 0x430
    ISceneDialog *resetDialog_;	// 1128 = 0x468
    ISceneDialog *changeDialog_;	// 1136 = 0x470
    TaikoSceneNode *cursorNode_;	// 1144 = 0x478
    TaikoSceneNode *nameNode_;	// 1152 = 0x480
    struct _AASAMPLE seSamples_[2];	// 1160 = 0x488
    struct _AGTEXTUREFRAMEGROUP noticeTextureFrameGroup_;	// 1208 = 0x4b8
    TaikoSceneNode *noticeNode_;	// 1232 = 0x4d0
    TaikoAction *noticeAnimation_;	// 1240 = 0x4d8
}

- (void)moveNextType:(id)arg1;
- (void)movePreviousType:(id)arg1;
- (void)changeStateToScroll;
- (void)updateChangeButton;
- (void)renderInputsWithType:(unsigned int)arg1 dx:(float)arg2;
- (void)renderConfigWithType:(unsigned int)arg1 dx:(float)arg2;
- (void)render;
- (int)stateWait;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (int)stateAlert;
- (int)stateScroll;
- (void)sceneDialog:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)sceneDialog:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)sceneDialog:(id)arg1 selectedButtonAtIndex:(int)arg2;
- (int)stateChange;
- (int)stateReset;
- (int)stateRun;
- (int)update;
- (void)playSEForType:(unsigned int)arg1 part:(int)arg2;
- (void)playSEForInput:(unsigned char)arg1;
- (void)changePart;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)setupCursor;
- (void)resetConfig;
- (void)saveConfig;
- (void)loadConfig;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

