//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BGSceneBase.h"

#import "SceneDialogDelegate-Protocol.h"

@class GameOptionIcons, ISceneDialog, ISceneSongSelect, ISongInfo, NSString, TaikoTextureCache, TaikoWindow;

@interface ISceneScoreDialog : BGSceneBase <SceneDialogDelegate>
{
    int pauseState_;	// 108 = 0x6c
    int pauseCounter_;	// 112 = 0x70
    unsigned int pauseBackColor_;	// 116 = 0x74
    int arrowAnimationCounter_;	// 120 = 0x78
    float arrowAlpha_;	// 124 = 0x7c
    int boardScrollCounter_;	// 128 = 0x80
    struct CGPoint touchStartPoint_;	// 136 = 0x88
    _Bool touchDragging_;	// 152 = 0x98
    float arrowX_[2];	// 156 = 0x9c
    struct CGRect arrowCollisions_[2];	// 168 = 0xa8
    struct _AGOBJECT songTitleObject_;	// 232 = 0xe8
    int *currentTitleObjectFrameIndex_;	// 288 = 0x120
    int *nextTitleObjectFrameIndex_;	// 296 = 0x128
    int savedTitleObjectFrameIndex_;	// 304 = 0x130
    struct _AGOBJECT scorePlateObject_[2];	// 312 = 0x138
    struct _AGOBJECT scorePointObject_;	// 424 = 0x1a8
    struct _AGOBJECT closeButtonObject_;	// 480 = 0x1e0
    struct _AGOBJECT onlineRankingButtonObject_;	// 536 = 0x218
    struct _AGOBJECT resetButtonObject_;	// 592 = 0x250
    struct _AGOBJECT difficultyObject_;	// 648 = 0x288
    struct _AGOBJECT uraObject_;	// 704 = 0x2c0
    struct _AGOBJECT achievementObject_;	// 760 = 0x2f8
    struct _AGOBJECT textObject_[6];	// 816 = 0x330
    struct _AGOBJECT numberFixObject_[4];	// 1152 = 0x480
    struct _AGOBJECT numberWfixObject_[7];	// 1376 = 0x560
    struct _AGOBJECT arrowObject_[2];	// 1768 = 0x6e8
    struct _AGOBJECT hyphenObject_;	// 1880 = 0x758
    TaikoWindow *window_;	// 1936 = 0x790
    TaikoWindow *innerWindow_;	// 1944 = 0x798
    TaikoTextureCache *textureCache_;	// 1952 = 0x7a0
    GameOptionIcons *optionIcons_;	// 1960 = 0x7a8
    _Bool _rankingSelected;	// 1968 = 0x7b0
    int _selectedCourse;	// 1972 = 0x7b4
    ISongInfo *_selectedSongInfo;	// 1976 = 0x7b8
    const CDStruct_6cc9a17f *_selectedSongRecord;	// 1984 = 0x7c0
    ISceneDialog *_resetDialog;	// 1992 = 0x7c8
    ISceneSongSelect *_sceneSongSelect;	// 2000 = 0x7d0
}

@property(nonatomic) ISceneSongSelect *sceneSongSelect; // @synthesize sceneSongSelect=_sceneSongSelect;
@property(nonatomic) ISceneDialog *resetDialog; // @synthesize resetDialog=_resetDialog;
@property(readonly, nonatomic) _Bool rankingSelected; // @synthesize rankingSelected=_rankingSelected;
@property(nonatomic) int selectedCourse; // @synthesize selectedCourse=_selectedCourse;
@property(nonatomic) const CDStruct_6cc9a17f *selectedSongRecord; // @synthesize selectedSongRecord=_selectedSongRecord;
@property(nonatomic) ISongInfo *selectedSongInfo; // @synthesize selectedSongInfo=_selectedSongInfo;
- (_Bool)isUserInteractionEnabled;
- (void)sceneDialog:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)sceneDialog:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)skipFadingIn;
- (int)getHigherCourse:(int)arg1;
- (int)getLowerCourse:(int)arg1;
- (int)stateWait;
- (int)stateRoot;
- (void)renderBoardRelative:(float)arg1 course:(int)arg2;
- (void)render;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)dealloc;
- (id)initWithManager:(id)arg1 currentTitleObjectFrameIndex:(int *)arg2 nextTitleObjectFrameIndex:(int *)arg3 frameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg4 onlineRankingButtonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 numberFixFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg6 numberWfixFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg7 closeButtonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg8 optionIconFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

