//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"

@class BGSNSWorldonInfo, ISceneNamePlate, ISceneScrollView, NSString, OAConsumer, OAToken, TaikoButton, TaikoEquipment, TaikoLabel, UIButton;

@interface ISceneSettings : ISceneBase <UITextFieldDelegate, UIAlertViewDelegate>
{
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTURE m_DogTexture;
    struct _AGTEXTUREFRAMEGROUP m_DogFrameGroup[2];
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_NameFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SceneMenuButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TwitterButtonFrameGroup;
    struct _AGOBJECT m_BackObject;
    struct _AGOBJECT m_TitleObject;
    struct _AGOBJECT m_BackButtonObject;
    struct _AGOBJECT m_SceneMenuButtonObject;
    struct _AGTEXTUREFRAMEGROUP m_BarFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_MainBoardFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SubBoardFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TaikoSettingsTitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TaikoSettingsSizeFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TaikoSettingsOnOffFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TwitterSettingsFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SoundTaikoSettingsFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SoundBalanceSettingsFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_VDrumsSettingsFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_OtherSettingsFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_HowtoSettingsFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_NewIconFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_NewTextFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_NewMessageWindowFrameGroup;
    struct _AGOBJECT m_BarObject[7];
    struct _AGOBJECT m_MainBoardObject[3];
    struct _AGOBJECT m_SubBoardObject[3];
    struct _AGOBJECT m_TaikoSettingsTitleObject[5];
    struct _AGOBJECT m_TaikoSettingsSizeObject[4];
    struct _AGOBJECT m_TaikoSettingsAlphaObject[2];
    struct _AGOBJECT m_TaikoSettingsSkinObject;
    struct _AGOBJECT m_TaikoSettingsTataconObject[2];
    struct _AGOBJECT m_TwitterSettingsObject[3];
    struct _AGOBJECT m_VDrumsSettingsObject[3];
    struct _AGOBJECT m_OtherSettingsObject[4];
    struct _AGOBJECT m_HowtoSettingsObject[4];
    struct _AGOBJECT m_SoundTaikoSettingsObject[2];
    struct _AGOBJECT m_SoundBalanceSettingsObject[4];
    struct _AGOBJECT m_SoundSelectedSettingsObject;
    struct _AGOBJECT m_SoundBalanceMeterObject[6];
    struct _AGOBJECT m_DogObject[2];
    struct _AGOBJECT m_ThemeThumbnailObject;
    struct _AGOBJECT m_CostumeThumbnailObject;
    struct _AGOBJECT m_TaikoSkinThumbnailObject;
    struct _AGOBJECT m_ThemeNewText;
    struct _AGOBJECT m_CostumeNewText;
    struct _AGOBJECT m_ToneNewText;
    struct _AGOBJECT m_TaikoSkinNewText;
    struct _AGOBJECT m_NewMessageObject[3];
    int m_BarState[7];
    float m_BoardAnimationSpeed;
    float m_BoardMaxWidth;
    float m_BarSpace;
    float m_BarUpSpeed;
    float m_BarDownSpeed;
    float m_BarSlideSpeed;
    float m_BarMaxPosition;
    float m_BarMinPosition;
    float m_BarSelectUpSpeed;
    float m_BarSelectDownSpeed;
    float m_BarStartPosition;
    float m_BarChoosePosition;
    float m_MainBoardSize;
    struct CGPoint m_MainBoardPosition;
    float m_SubBoardSize;
    struct CGPoint m_SubBoardPosition;
    int m_AnimationState;
    int m_AnimationCounter;
    int m_MainSelect;
    int m_SoundSelect;
    int m_OtherSelect;
    int m_SettingSelect;
    int m_HowtoSelect;
    int m_NextScene;
    int m_FadeCounter;
    float m_TextFieldDelta;
    float m_SoundBalancePosition;
    float m_SoundBalanceMeterUnitWidth;
    float m_DogFallDistance;
    float m_DogFallAmount;
    int m_DogAnimationCounter;
    _Bool m_MainBoardFront;
    _Bool m_SubBoardFront;
    _Bool m_ShowTwitterSettings;
    _Bool m_ShowTaikoSettings;
    _Bool m_ShowVDrumsSettings;
    _Bool m_ShowTaikoSkinSettings;
    _Bool m_ShowSoundSettings;
    _Bool m_ShowSoundTaikoSettings;
    _Bool m_ShowSoundBalanceSettings;
    _Bool m_ShowOtherSettings;
    _Bool m_ShowThemeSettings;
    _Bool m_ShowCostumeSettings;
    _Bool m_ShowHowtoSettings;
    _Bool m_TouchDragging;
    unsigned char m_KeyboardActive;
    _Bool m_enableTwitterRequest;
    OAConsumer *m_Consumer;
    OAToken *m_RequestToken;
    TaikoLabel *m_ScreenNameLabel;
    TaikoButton *m_TwitterButton;
    _Bool m_RefuseTouch;
    _Bool m_IsSkipMode;
    int m_SkipType;
    int m_NumMenus;
    const int *m_MenuList;
    ISceneNamePlate *m_SceneNamePlate;
    BGSNSWorldonInfo *m_WorldonInfo;
    float m_BoardRatio;
    _Bool m_VDrumsInputEnabled;
    unsigned int m_VDrumsCurrentType;
    TaikoButton *m_VDrumsSettingsButton[2];
    UIButton *m_PushingSender;
    _Bool m_IsGotoSceneVDrumsSettings;
    _Bool m_IsGotoRolandVDrumsPage;
    _Bool m_AlertVisible;
    ISceneScrollView *m_ThemeScrollView;
    ISceneScrollView *m_CostumeScrollView;
    ISceneScrollView *m_ToneScrollView;
    ISceneScrollView *m_TaikoSkinScrollView;
    TaikoEquipment *m_LastThemeEquipment;
    _Bool m_IsThemeNew;
    _Bool m_IsCostumeNew;
    _Bool m_IsToneNew;
    _Bool m_IsTaikoSkinNew;
}

- (void)applicationWillResignActive;
- (void)accessTokenTicket:(id)arg1 didFailWithError:(id)arg2;
- (void)accessTokenTicket:(id)arg1 didFinishWithData:(id)arg2;
- (void)getAccessToken;
- (void)handleOpenURL:(id)arg1;
- (void)requestTokenTicket:(id)arg1 didFailWithError:(id)arg2;
- (void)requestTokenTicket:(id)arg1 didFinishWithData:(id)arg2;
- (void)getRequestToken;
- (void)clearOAuthConsumer;
- (void)didPresentAlertView:(id)arg1;
- (void)startTwitterAuth;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onTouchDownButtonOption:(id)arg1;
- (void)onTouchUpOutsideButtonOption:(id)arg1;
- (void)onTouchUpInsideButtonOption:(id)arg1;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (int)stateAnimate;
- (int)stateVDrumsSettings;
- (int)stateTaikoSkinSettings;
- (int)stateSoundBalanceSettings;
- (int)stateSoundTaikoSettings;
- (int)stateSoundSettings;
- (int)stateCostumeSettings;
- (int)stateThemeSettings;
- (void)ExitDlg:(int)arg1 Result:(int)arg2;
- (int)stateHowtoSettings;
- (int)stateOtherSettings;
- (int)stateTwitterSettings;
- (int)stateTaikoSettings;
- (int)stateMain;
- (void)switchVDrumsToTaikoController;
- (void)updateAnimation;
- (void)renderNewMessage;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

