//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneBase.h"

#import "UIAlertViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class BGSNSWorldonInfo, ISceneNamePlate, ISceneScrollView, NSString, OAConsumer, OAToken, TaikoButton, TaikoEquipment, TaikoLabel, UIButton;

@interface ISceneSettings : ISceneBase <UITextFieldDelegate, UIAlertViewDelegate>
{
    struct _AGTEXTURE m_MainTexture;	// 72 = 0x48
    struct _AGTEXTURE m_DogTexture;	// 128 = 0x80
    struct _AGTEXTUREFRAMEGROUP m_DogFrameGroup[2];	// 184 = 0xb8
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;	// 232 = 0xe8
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;	// 256 = 0x100
    struct _AGTEXTUREFRAMEGROUP m_NameFrameGroup;	// 280 = 0x118
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;	// 304 = 0x130
    struct _AGTEXTUREFRAMEGROUP m_SceneMenuButtonFrameGroup;	// 328 = 0x148
    struct _AGTEXTUREFRAMEGROUP m_TwitterButtonFrameGroup;	// 352 = 0x160
    struct _AGOBJECT m_BackObject;	// 376 = 0x178
    struct _AGOBJECT m_TitleObject;	// 432 = 0x1b0
    struct _AGOBJECT m_BackButtonObject;	// 488 = 0x1e8
    struct _AGOBJECT m_SceneMenuButtonObject;	// 544 = 0x220
    struct _AGTEXTUREFRAMEGROUP m_BarFrameGroup;	// 600 = 0x258
    struct _AGTEXTUREFRAMEGROUP m_MainBoardFrameGroup;	// 624 = 0x270
    struct _AGTEXTUREFRAMEGROUP m_SubBoardFrameGroup;	// 648 = 0x288
    struct _AGTEXTUREFRAMEGROUP m_TaikoSettingsTitleFrameGroup;	// 672 = 0x2a0
    struct _AGTEXTUREFRAMEGROUP m_TaikoSettingsSizeFrameGroup;	// 696 = 0x2b8
    struct _AGTEXTUREFRAMEGROUP m_TaikoSettingsOnOffFrameGroup;	// 720 = 0x2d0
    struct _AGTEXTUREFRAMEGROUP m_TwitterSettingsFrameGroup;	// 744 = 0x2e8
    struct _AGTEXTUREFRAMEGROUP m_SoundTaikoSettingsFrameGroup;	// 768 = 0x300
    struct _AGTEXTUREFRAMEGROUP m_SoundBalanceSettingsFrameGroup;	// 792 = 0x318
    struct _AGTEXTUREFRAMEGROUP m_VDrumsSettingsFrameGroup;	// 816 = 0x330
    struct _AGTEXTUREFRAMEGROUP m_OtherSettingsFrameGroup;	// 840 = 0x348
    struct _AGTEXTUREFRAMEGROUP m_HowtoSettingsFrameGroup;	// 864 = 0x360
    struct _AGTEXTUREFRAMEGROUP m_NewIconFrameGroup;	// 888 = 0x378
    struct _AGTEXTUREFRAMEGROUP m_NewTextFrameGroup;	// 912 = 0x390
    struct _AGTEXTUREFRAMEGROUP m_NewMessageWindowFrameGroup;	// 936 = 0x3a8
    struct _AGOBJECT m_BarObject[7];	// 960 = 0x3c0
    struct _AGOBJECT m_MainBoardObject[3];	// 1352 = 0x548
    struct _AGOBJECT m_SubBoardObject[3];	// 1520 = 0x5f0
    struct _AGOBJECT m_TaikoSettingsTitleObject[5];	// 1688 = 0x698
    struct _AGOBJECT m_TaikoSettingsSizeObject[4];	// 1968 = 0x7b0
    struct _AGOBJECT m_TaikoSettingsAlphaObject[2];	// 2192 = 0x890
    struct _AGOBJECT m_TaikoSettingsSkinObject;	// 2304 = 0x900
    struct _AGOBJECT m_TaikoSettingsTataconObject[2];	// 2360 = 0x938
    struct _AGOBJECT m_TwitterSettingsObject[3];	// 2472 = 0x9a8
    struct _AGOBJECT m_VDrumsSettingsObject[3];	// 2640 = 0xa50
    struct _AGOBJECT m_OtherSettingsObject[4];	// 2808 = 0xaf8
    struct _AGOBJECT m_HowtoSettingsObject[4];	// 3032 = 0xbd8
    struct _AGOBJECT m_SoundTaikoSettingsObject[2];	// 3256 = 0xcb8
    struct _AGOBJECT m_SoundBalanceSettingsObject[4];	// 3368 = 0xd28
    struct _AGOBJECT m_SoundSelectedSettingsObject;	// 3592 = 0xe08
    struct _AGOBJECT m_SoundBalanceMeterObject[6];	// 3648 = 0xe40
    struct _AGOBJECT m_DogObject[2];	// 3984 = 0xf90
    struct _AGOBJECT m_ThemeThumbnailObject;	// 4096 = 0x1000
    struct _AGOBJECT m_CostumeThumbnailObject;	// 4152 = 0x1038
    struct _AGOBJECT m_TaikoSkinThumbnailObject;	// 4208 = 0x1070
    struct _AGOBJECT m_ThemeNewText;	// 4264 = 0x10a8
    struct _AGOBJECT m_CostumeNewText;	// 4320 = 0x10e0
    struct _AGOBJECT m_ToneNewText;	// 4376 = 0x1118
    struct _AGOBJECT m_TaikoSkinNewText;	// 4432 = 0x1150
    struct _AGOBJECT m_NewMessageObject[3];	// 4488 = 0x1188
    int m_BarState[7];	// 4656 = 0x1230
    float m_BoardAnimationSpeed;	// 4684 = 0x124c
    float m_BoardMaxWidth;	// 4688 = 0x1250
    float m_BarSpace;	// 4692 = 0x1254
    float m_BarUpSpeed;	// 4696 = 0x1258
    float m_BarDownSpeed;	// 4700 = 0x125c
    float m_BarSlideSpeed;	// 4704 = 0x1260
    float m_BarMaxPosition;	// 4708 = 0x1264
    float m_BarMinPosition;	// 4712 = 0x1268
    float m_BarSelectUpSpeed;	// 4716 = 0x126c
    float m_BarSelectDownSpeed;	// 4720 = 0x1270
    float m_BarStartPosition;	// 4724 = 0x1274
    float m_BarChoosePosition;	// 4728 = 0x1278
    float m_MainBoardSize;	// 4732 = 0x127c
    struct CGPoint m_MainBoardPosition;	// 4736 = 0x1280
    float m_SubBoardSize;	// 4752 = 0x1290
    struct CGPoint m_SubBoardPosition;	// 4760 = 0x1298
    int m_AnimationState;	// 4776 = 0x12a8
    int m_AnimationCounter;	// 4780 = 0x12ac
    int m_MainSelect;	// 4784 = 0x12b0
    int m_SoundSelect;	// 4788 = 0x12b4
    int m_OtherSelect;	// 4792 = 0x12b8
    int m_SettingSelect;	// 4796 = 0x12bc
    int m_HowtoSelect;	// 4800 = 0x12c0
    int m_NextScene;	// 4804 = 0x12c4
    int m_FadeCounter;	// 4808 = 0x12c8
    float m_TextFieldDelta;	// 4812 = 0x12cc
    float m_SoundBalancePosition;	// 4816 = 0x12d0
    float m_SoundBalanceMeterUnitWidth;	// 4820 = 0x12d4
    float m_DogFallDistance;	// 4824 = 0x12d8
    float m_DogFallAmount;	// 4828 = 0x12dc
    int m_DogAnimationCounter;	// 4832 = 0x12e0
    _Bool m_MainBoardFront;	// 4836 = 0x12e4
    _Bool m_SubBoardFront;	// 4837 = 0x12e5
    _Bool m_ShowTwitterSettings;	// 4838 = 0x12e6
    _Bool m_ShowTaikoSettings;	// 4839 = 0x12e7
    _Bool m_ShowVDrumsSettings;	// 4840 = 0x12e8
    _Bool m_ShowTaikoSkinSettings;	// 4841 = 0x12e9
    _Bool m_ShowSoundSettings;	// 4842 = 0x12ea
    _Bool m_ShowSoundTaikoSettings;	// 4843 = 0x12eb
    _Bool m_ShowSoundBalanceSettings;	// 4844 = 0x12ec
    _Bool m_ShowOtherSettings;	// 4845 = 0x12ed
    _Bool m_ShowThemeSettings;	// 4846 = 0x12ee
    _Bool m_ShowCostumeSettings;	// 4847 = 0x12ef
    _Bool m_ShowHowtoSettings;	// 4848 = 0x12f0
    _Bool m_TouchDragging;	// 4849 = 0x12f1
    unsigned char m_KeyboardActive;	// 4850 = 0x12f2
    _Bool m_enableTwitterRequest;	// 4851 = 0x12f3
    OAConsumer *m_Consumer;	// 4856 = 0x12f8
    OAToken *m_RequestToken;	// 4864 = 0x1300
    TaikoLabel *m_ScreenNameLabel;	// 4872 = 0x1308
    TaikoButton *m_TwitterButton;	// 4880 = 0x1310
    _Bool m_RefuseTouch;	// 4888 = 0x1318
    _Bool m_IsSkipMode;	// 4889 = 0x1319
    int m_SkipType;	// 4892 = 0x131c
    int m_NumMenus;	// 4896 = 0x1320
    const int *m_MenuList;	// 4904 = 0x1328
    ISceneNamePlate *m_SceneNamePlate;	// 4912 = 0x1330
    BGSNSWorldonInfo *m_WorldonInfo;	// 4920 = 0x1338
    float m_BoardRatio;	// 4928 = 0x1340
    _Bool m_VDrumsInputEnabled;	// 4932 = 0x1344
    unsigned int m_VDrumsCurrentType;	// 4936 = 0x1348
    TaikoButton *m_VDrumsSettingsButton[2];	// 4944 = 0x1350
    UIButton *m_PushingSender;	// 4960 = 0x1360
    _Bool m_IsGotoSceneVDrumsSettings;	// 4968 = 0x1368
    _Bool m_IsGotoRolandVDrumsPage;	// 4969 = 0x1369
    _Bool m_AlertVisible;	// 4970 = 0x136a
    ISceneScrollView *m_ThemeScrollView;	// 4976 = 0x1370
    ISceneScrollView *m_CostumeScrollView;	// 4984 = 0x1378
    ISceneScrollView *m_ToneScrollView;	// 4992 = 0x1380
    ISceneScrollView *m_TaikoSkinScrollView;	// 5000 = 0x1388
    TaikoEquipment *m_LastThemeEquipment;	// 5008 = 0x1390
    _Bool m_IsThemeNew;	// 5016 = 0x1398
    _Bool m_IsCostumeNew;	// 5017 = 0x1399
    _Bool m_IsToneNew;	// 5018 = 0x139a
    _Bool m_IsTaikoSkinNew;	// 5019 = 0x139b
}

- (void)applicationWillResignActive;
- (void)accessTokenTicket:(id)arg1 didFailWithError:(id)arg2;
- (void)accessTokenTicket:(id)arg1 didFinishWithData:(id)arg2;
- (void)getAccessToken;
- (void)handleOpenURL:(id)arg1;
- (void)requestTokenTicket:(id)arg1 didFailWithError:(id)arg2;
- (void)requestTokenTicket:(id)arg1 didFinishWithData:(id)arg2;
- (void)getRequestToken;
- (void)clearOAuthConsumer;
- (void)didPresentAlertView:(id)arg1;
- (void)startTwitterAuth;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onTouchDownButtonOption:(id)arg1;
- (void)onTouchUpOutsideButtonOption:(id)arg1;
- (void)onTouchUpInsideButtonOption:(id)arg1;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (int)stateAnimate;
- (int)stateVDrumsSettings;
- (int)stateTaikoSkinSettings;
- (int)stateSoundBalanceSettings;
- (int)stateSoundTaikoSettings;
- (int)stateSoundSettings;
- (int)stateCostumeSettings;
- (int)stateThemeSettings;
- (void)ExitDlg:(int)arg1 Result:(int)arg2;
- (int)stateHowtoSettings;
- (int)stateOtherSettings;
- (int)stateTwitterSettings;
- (int)stateTaikoSettings;
- (int)stateMain;
- (void)switchVDrumsToTaikoController;
- (void)updateAnimation;
- (void)renderNewMessage;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

