//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "SceneDialogDelegate.h"

@class ISceneDialog, NSString, TaikoSceneNode;

@interface ISceneLinkage : ISceneBase <SceneDialogDelegate>
{
    unsigned int state_;
    struct _AGTEXTURE dialogTexture_;
    struct _AGTEXTUREFRAMEGROUP windowFrameGroup_;
    struct _AGTEXTUREFRAMEGROUP dialogMessageFrameGroup_;
    struct _AGTEXTUREFRAMEGROUP dialogButtonFrameGroup_;
    struct _AGTEXTUREFRAMEGROUP dialogChoiceFrameGroup_;
    struct _AGTEXTUREFRAMEGROUP digitFrameGroup_;
    ISceneDialog *dialog_;
    TaikoSceneNode *digitNodes_[11];
    struct _AGTEXTURE titleTexture_;
    struct _AGTEXTUREFRAMEGROUP titleFrameGroup_;
    TaikoSceneNode *titleNode_;
    _Bool _busy;
}

@property(readonly, nonatomic) _Bool busy; // @synthesize busy=_busy;
- (void)sceneDialog:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)setFileNameImage:(id)arg1;
- (void)setEndDateString:(id)arg1;
- (int)setDigitToNodeAtIndex:(int)arg1 string:(id)arg2 begin:(int)arg3 end:(int)arg4;
- (void)renderDialog;
- (void)updateDialog;
- (void)destroyDialog;
- (void)openDialog;
- (void)render;
- (int)stateRun;
- (void)dealloc;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

