//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneManagerVDrums.h"

@class ISceneLinkage, ISceneManagerLinkageAlertViewDelegate, NSDictionary, NSMutableArray, NSString, TaikoCoverView, UIActivityIndicatorView;

@interface ISceneManagerLinkage : ISceneManagerVDrums
{
    NSString *linkageDirectory_;	// 1248 = 0x4e0
    ISceneLinkage *sceneLinkage_;	// 1256 = 0x4e8
    TaikoCoverView *coverView_;	// 1264 = 0x4f0
    _Bool covered_;	// 1272 = 0x4f8
    _Bool coverTouched_;	// 1273 = 0x4f9
    struct _TOUCH alternativeTouches_[10];	// 1280 = 0x500
    NSDictionary *preservedInfo_;	// 1920 = 0x780
    int queryCount_;	// 1928 = 0x788
    NSMutableArray *processingLinkageProducts_;	// 1936 = 0x790
    NSMutableArray *completedLinkageProducts_;	// 1944 = 0x798
    _Bool waitingForAlertview_;	// 1952 = 0x7a0
    NSString *linkageQuery_;	// 1960 = 0x7a8
    UIActivityIndicatorView *activityIndicatorView_;	// 1968 = 0x7b0
    int musicIndex_;	// 1976 = 0x7b8
    ISceneManagerLinkageAlertViewDelegate *alertViewDelegate_;	// 1984 = 0x7c0
    _Bool _canOpenLinkageDialog;	// 1992 = 0x7c8
    NSString *_addedLinkageMusicID;	// 2000 = 0x7d0
    CDUnknownBlockType _linkageInfoUpdatedCallback;	// 2008 = 0x7d8
}

@property(copy, nonatomic) CDUnknownBlockType linkageInfoUpdatedCallback; // @synthesize linkageInfoUpdatedCallback=_linkageInfoUpdatedCallback;
@property(copy, nonatomic) NSString *addedLinkageMusicID; // @synthesize addedLinkageMusicID=_addedLinkageMusicID;
@property(nonatomic) _Bool canOpenLinkageDialog; // @synthesize canOpenLinkageDialog=_canOpenLinkageDialog;
- (id)horizontalTitleImageFilePathWithLinkage:(id)arg1 targetProductID:(id)arg2 atIndex:(int)arg3;
- (id)musicIDWithLinkage:(id)arg1 targetProductID:(id)arg2 atIndex:(int)arg3;
- (void)showActivityIndicator:(_Bool)arg1;
- (id)activityIndicatorView;
- (void)notifyLinkageInfoUpdatedWithLinkageProduct:(id)arg1;
- (void)clearAddedLinkageMusicID;
- (void)openLinkageAnotherURL;
- (void)openLinkageURL;
- (_Bool)canOpenLinkageURL;
- (void)tapLinkageButtonWithNumber:(int)arg1;
- (id)linkageButtonImageAndMaskImage:(id *)arg1;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (_Bool)finalizeProcessingLinkageWithDownload:(id)arg1 error:(int)arg2;
- (void)startCheckingLinkageButtonInfo;
- (void)updateLinkageInfo:(id)arg1 code:(id)arg2;
- (void)checkAndDownloadForLinkageProduct:(id)arg1 inDirectory:(id)arg2 fileName:(id)arg3 URLString:(id)arg4;
- (void)startCheckingServerRenewalInfo;
- (void)applicationDidEnterBackground;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)registerLinkageQuery:(id)arg1;
- (id)parseQueryString:(id)arg1;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)ISceneManagerLinkage_alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)processCompletedLinkage;
- (void)showAlertWithSubtitle:(id)arg1 message:(id)arg2 tag:(int)arg3;
- (_Bool)openDialogWithLinkageProduct:(id)arg1;
- (void)processLinkageQuery;
- (void)endQuery;
- (void)beginQuery;
- (void)renderLast;
- (_Bool)needsCover;
- (_Bool)isProcessing;
- (void)update;
- (struct _TOUCH *)allTouches;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 options:(id)arg2;
- (_Bool)isBusyWithLinkage;

@end

