//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIAlertViewDelegate-Protocol.h"

@class ISceneManagerLinkage, NSString;

@interface ISceneManagerLinkageAlertViewDelegate : NSObject <UIAlertViewDelegate>
{
    ISceneManagerLinkage *_delegate;	// 8 = 0x8
}

@property(nonatomic) ISceneManagerLinkage *delegate; // @synthesize delegate=_delegate;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

