//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "GKTaikoBattleDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSMutableArray, NSString;

@interface ISceneVSResult : ISceneBase <GKTaikoBattleDelegate, UIAlertViewDelegate>
{
    struct _AASAMPLE m_oSampleDrumRoll;
    struct _AASAMPLE m_oSampleDrumSubmit;
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTURE m_BackTexture;
    struct _AGTEXTURE m_FontTexture;
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_ScoreNumFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_NameFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_WinCountFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_PedestalFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DonGroup[4];
    struct _AGTEXTUREFRAMEGROUP m_WindowFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_WindowContentsFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_ComNameGroup;
    struct _AGTEXTUREFRAMEGROUP m_ConnectErrorGroup;
    struct _AGOBJECT m_BackObject;
    struct _AGOBJECT m_BackWordObject;
    struct _AGOBJECT m_ScoreNumObject[4][7];
    struct _AGOBJECT m_NameObject[4][5];
    struct _AGOBJECT m_WinCountObject[4][3];
    struct _AGOBJECT m_PedestalObject[4];
    struct _AGOBJECT m_PedestalInfoObject[4];
    struct _AGOBJECT m_DonObject[4];
    struct _AGOBJECT m_WindowObject[3];
    struct _AGOBJECT m_WindowContentsObject[5];
    struct _AGOBJECT m_oObjPleaseWait;
    struct _AGOBJECT m_aroObjComName[4];
    struct _AGOBJECT m_aroObjWindowConnectError[3];
    struct _AGOBJECT m_oObjTextConnectError;
    _Bool m_isDraw;
    int m_Counter;
    _Bool m_PedestalAnimationFlag[4];
    float m_PedestalDestY[4];
    float m_PedestalSpeedY[4];
    int m_DonAnimationMode[4];
    int m_DonAnimationCounter[4];
    float m_DonJumpHeight[4];
    struct CGPoint m_DonPosition;
    int m_ReplySelect;
    NSMutableArray *m_members;
    int m_gameResult;
    unsigned int m_nWindowEnableCount;
    int m_NextScene;
    _Bool m_nRecieveWait;
    _Bool m_nErrorAlert;
    _Bool m_nShowConnectError;
    _Bool m_nShowWindow;
    _Bool m_bEndIdle;
    _Bool m_bAllClientsReady;
}

- (void)didPresentAlertView:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)disconnectAllPeer;
- (void)recieveData:(id)arg1 Scene:(unsigned int)arg2 Order:(unsigned int)arg3 Arr:(unsigned int)arg4;
- (void)applicationWillResignActive;
- (int)stateAlert;
- (int)stateRecieveWait;
- (int)stateFadeOutFromAlert;
- (int)stateFadeOut;
- (int)stateReplay;
- (int)stateIdleForClient;
- (int)stateWaitServerReady;
- (int)stateWaitAllClientsReady;
- (int)stateIdle;
- (int)stateCountScore;
- (void)setWaitRoutine;
- (int)stateFadeIn;
- (int)stateFadeInBefore;
- (void)updateAnimation;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

