//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "GKTaikoBattleDelegate.h"
#import "UIAlertViewDelegate.h"

@class ISceneNamePlate, NSArray, NSMutableArray, NSString, UIActivityIndicatorView, UISwitch;

@interface ISceneVSSettings : ISceneBase <GKTaikoBattleDelegate, UIAlertViewDelegate>
{
    struct _AASAMPLE m_oSoundDonMake;
    struct _AASAMPLE m_oSoundDonFind;
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BarFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_MainBoardFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SubBoardFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_ExpandingBarGroup;
    struct _AGTEXTUREFRAMEGROUP m_ArrowGroup;
    struct _AGTEXTUREFRAMEGROUP m_NameFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TFGDon;
    struct _AGTEXTUREFRAMEGROUP m_TFGSpeechBubble;
    struct _AGTEXTUREFRAMEGROUP m_InviteMemberGroup;
    struct _AGTEXTUREFRAMEGROUP m_MemberNameFontGroup;
    struct _AGTEXTUREFRAMEGROUP m_ButtleSettingsGroup;
    struct _AGTEXTUREFRAMEGROUP m_RuleSwitchGroup;
    struct _AGTEXTUREFRAMEGROUP m_RatingGroup;
    struct _AGTEXTUREFRAMEGROUP m_CourseIconGroup;
    struct _AGTEXTUREFRAMEGROUP m_GameOptionGroup;
    struct _AGTEXTURE m_SongTexture;
    struct _AGTEXTUREFRAMEGROUP m_SongGroup;
    struct _AGTEXTUREFRAMEGROUP m_RoomSelectGroup;
    struct _AGTEXTUREFRAMEGROUP m_NumberFontGroup;
    struct _AGTEXTUREFRAMEGROUP m_ComNameGroup;
    struct _AGTEXTUREFRAMEGROUP m_ConnectErrorGroup;
    struct _AGOBJECT m_BackObject;
    struct _AGOBJECT m_TitleObject;
    struct _AGOBJECT m_BackButtonObject;
    struct _AGOBJECT m_BarObject[3];
    struct _AGOBJECT m_MainBoardObject[3];
    struct _AGOBJECT m_SubBoardObject[3];
    struct _AGOBJECT m_ExpandingBarObject[3];
    struct _AGOBJECT m_ArrowObject[2];
    struct _AGOBJECT m_DonObject;
    struct _AGOBJECT m_SpeechBubbleObject[2];
    struct _AGOBJECT m_InviteMemberObject[4];
    struct _AGOBJECT m_MemberNameObject[4][5];
    struct _AGOBJECT m_aroObjComName[3];
    struct _AGOBJECT m_ButtleSettings_SongTitle;
    struct _AGOBJECT m_ButtleSettings_StartButtle;
    struct _AGOBJECT m_ButtleSettings_Words[4];
    struct _AGOBJECT m_ButtleSettings_Rule[2];
    struct _AGOBJECT m_ButtleSettings_CourseIcon;
    struct _AGOBJECT m_ButtleSettings_Rating;
    struct _AGOBJECT m_ButtleSettings_PleaseWait;
    struct _AGOBJECT m_ButtleSettings_BackWaku[2];
    struct _AGOBJECT m_ButtleSettings_Arrows[8];
    struct _AGOBJECT m_ButtleSettings_GameOption[2];
    _Bool m_ButtleSettings_GameOptionEnabled;
    struct CGPoint m_aroArrowBasePos[8];
    struct _AGOBJECT m_RoomSelect_Words[2];
    struct _AGOBJECT m_RoomSelect_Name[5];
    struct _AGOBJECT m_aroObjWindowConnectError[3];
    struct _AGOBJECT m_oObjTextConnectError;
    UISwitch *m_ItemEnabledSwitch;
    UISwitch *m_ItemComSwitch;
    UIActivityIndicatorView *m_pIndCommunication;
    int m_BarState[3];
    float m_BoardAnimationSpeed;
    float m_BoardMaxWidth;
    float m_BarSpace;
    float m_BarUpSpeed;
    float m_BarDownSpeed;
    float m_BarMaxPosition;
    float m_BarMinPosition;
    float m_BarSelectUpSpeed;
    float m_BarSelectDownSpeed;
    float m_BarStartPosition;
    float m_BarChoosePosition;
    float m_BarHideChoosePosition;
    float m_MainBoardSize;
    struct CGPoint m_MainBoardPosition;
    float m_SubBoardSize;
    struct CGPoint m_SubBoardPosition;
    struct CGPoint m_ExpandingBarPosition;
    float m_ExpandingBarSpace;
    float m_ArrowMinPosition;
    float m_ArrowMaxPosition;
    int m_ArrowAnimationCounter;
    int m_MainSelect;
    int m_AnimationState;
    int m_AnimationCounter;
    int m_NextScene;
    int m_FadeCounter;
    _Bool m_MainBoardFront;
    _Bool m_SubBoardFront;
    _Bool m_ShowInviteMember;
    _Bool m_ShowButtleSettings;
    _Bool m_ShowRoomSelect;
    int m_DonChanCounter;
    int m_SpeechBubbleCounter;
    float m_DonAppearDistance;
    float m_DonAppearAmount;
    float m_DonAppearIncrement;
    struct CGPoint m_RatingStarPos;
    float m_RatingStarSpace;
    struct CGPoint m_RoomSelect_NamePos;
    float m_RoomSelect_NameSpace;
    float m_ScrollSpeed;
    float m_ScrollStartPosition;
    float m_ScrollPosition;
    float m_MaxScrollPosition;
    struct CGPoint m_ScrollTouchPoint;
    struct CGRect m_ScrollAreaRect;
    _Bool m_ScrollEnabled;
    _Bool m_Scrolling;
    unsigned long long m_Member[4];
    int m_MemberLength[4];
    int m_Rule;
    _Bool m_useItem;
    NSMutableArray *m_rooms;
    NSMutableArray *m_members;
    NSMutableArray *m_pArrMusicID;
    NSString *m_songID;
    int m_course;
    unsigned int m_nSelectSongArr;
    _Bool m_loadSongTexture;
    _Bool m_isServer;
    unsigned int m_nIndCount;
    unsigned int m_nGrayOverColor;
    unsigned int m_nSendSettingCount;
    unsigned int m_nConnectWaitCount;
    unsigned int m_nWaitGameStartCount;
    unsigned int m_ObiColor;
    float m_fArrowDeltaPoint;
    _Bool m_nShowConnectError;
    _Bool m_nErrorAlert;
    _Bool m_nSettingBefore;
    ISceneNamePlate *m_SceneNamePlate;
    struct _AGTEXTUREFRAMEGROUP m_TaisenTextGroup;
    struct _AGTEXTUREFRAMEGROUP m_TaisenBackGroup;
    struct _AGTEXTUREFRAMEGROUP m_CourseIconFrameGroup;
    struct _AGOBJECT m_oObjTaisenCource;
    struct _AGOBJECT m_aroObjTaisenText[9];
    struct _AGOBJECT m_aroObjTaisenBack[2];
    struct _AGOBJECT m_aroObjTaisenTop[3];
    struct _AGOBJECT m_aroObjTaisenBottom[4];
    struct _AGOBJECT m_NumObject[7];
    struct _AGOBJECT m_RecordArrowObject[2];
    unsigned int m_ararnTopCount[4][3];
    unsigned int m_ararnTopPar[4][3];
    unsigned int m_ararnBottomCount[4][4];
    unsigned int m_ararnBottomPar[4][4];
    unsigned int m_nSelectCource;
    unsigned int m_nBeforeCource;
    float m_BoardScrollPosition;
    int m_BoardScrollCounter;
    struct CGPoint m_StartTouchPoint;
    _Bool m_TouchActive;
    float m_ScoreCourseSpace;
    float m_ArrowDeltaPosition;
    _Bool m_ShowTaisen;
    NSArray *m_SongList;
}

- (void)didPresentAlertView:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)disconnectAllPeer;
- (void)recieveData:(id)arg1 Scene:(unsigned int)arg2 Order:(unsigned int)arg3 Arr:(unsigned int)arg4;
- (void)enableGameOption;
- (void)connectErrorProcess;
- (void)applicationWillResignActive;
- (int)stateAlert;
- (void)sendButtleSettingsWithSubmit:(_Bool)arg1;
- (void)enableCom;
- (void)enableItem;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (int)stateFadeInBefore;
- (int)stateSelectRoom;
- (int)stateButtleSettingsS;
- (int)stateButtleSettingsC;
- (int)stateInviteMemberS;
- (int)stateInviteMemberC;
- (int)stateAnimate;
- (int)stateTaisen;
- (int)stateMain;
- (void)updateAnimation;
- (void)render;
- (void)renderTaisenBoardAtPosition:(float)arg1 cource:(unsigned int)arg2;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

