//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BGSceneBase.h"

#import "BGSNSInterfaceDelegate.h"
#import "SKProductsRequestDelegate.h"
#import "SceneDialogDelegate.h"

@class ISceneDialog, ISceneHowTo, NSArray, NSDate, NSMutableArray, NSMutableDictionary, NSString, TaikoAction, TaikoButton, TaikoRestore, TaikoWindow, UIButton;

@interface ISceneSubscriptionMenu : BGSceneBase <SKProductsRequestDelegate, BGSNSInterfaceDelegate, SceneDialogDelegate>
{
    int pauseState_;
    int pauseCounter_;
    unsigned int pauseBackColor_;
    unsigned int pauseBackColor2_;
    int kanyuCounter_;
    int kanyuDateNum_[3];
    int pageNum_;
    int page_;
    int selectedButton_;
    struct _AGTEXTUREFRAMEGROUP *mainFrameGroup_;
    TaikoButton *buttons_[7];
    struct _AGOBJECT buttonLabelObjects_[7];
    struct _AGOBJECT closeButtonObject_;
    struct _AGOBJECT restoreButtonObject_;
    struct _AGOBJECT tokusyouButtonObject_;
    struct _AGOBJECT ticketLabelObject_;
    struct _AGOBJECT kanyuObject_[2];
    struct _AGOBJECT kanyuNumObject_[2];
    struct _AGOBJECT kanyuSlashObject_;
    struct _AGOBJECT *contentObject_;
    struct _AGOBJECT songListObject_[10];
    struct _AGOBJECT urimonkuDon_;
    struct _AGOBJECT urimonkuText_;
    TaikoWindow *windows_[2];
    struct CGRect arrowCollisions_[2];
    TaikoAction *arrowActions_[2];
    ISceneDialog *purchaseFinishDialog_;
    ISceneDialog *restoreConfirmDialog_;
    ISceneDialog *restoreFinishDialog_;
    ISceneHowTo *sceneHowTo_;
    _Bool triggered_;
    UIButton *triggeredSender_;
    UIButton *pressedSender_;
    int currentButton_;
    int *currentTitleObjectFrameIndex_;
    int *nextTitleObjectFrameIndex_;
    int savedTitleObjectFrameIndex_;
    int titleObjectFrameIndex_;
    TaikoRestore *restorer_;
    NSMutableArray *receiptValidationRequests_;
    NSMutableArray *receiptRegistrationRequests_;
    NSMutableArray *restoredTransaction_;
    _Bool waitingProductsRequest_;
    _Bool shouldClose_;
    _Bool errorOccured_;
    _Bool waitingSongListImageDownload_;
    int songListImageCount_;
    int songListImageDownloadTimeoutCount_;
    struct _AGTEXTURE songListImageTextures_[10];
    struct _AGTEXTUREFRAMEGROUP tfgSongListImages_[10];
    struct _AGOBJECT songListImageObjects_[10];
    NSArray *musicPackages_;
    NSMutableDictionary *skProducts_;
    NSDate *priceExpiresDate_;
    _Bool rendering_;
    _Bool purchaseMode_;
    _Bool restoring_;
    _Bool isOpenSongList_;
    NSString *purchasingProductIdentifier_;
}

- (void)sceneDialog:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)sceneDialog:(id)arg1 selectedButtonAtIndex:(int)arg2;
- (void)restoreTransactionsFailedWithError:(id)arg1;
- (void)restoreTransactionsCompleted;
- (void)transactionFailedWithTransaction:(id)arg1;
- (_Bool)transactionCompletedWithTransaction:(id)arg1;
- (void)registerTransaction:(id)arg1;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)requestDidFinish:(id)arg1;
- (void)removeRegistrationRequestWithTransaction:(id)arg1;
- (void)removeValidationRequestWithSubscriptionID:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertFailureWithTitle:(id)arg1 message:(id)arg2 tag:(int)arg3;
- (void)onTouchDownButtonOption:(id)arg1;
- (void)onTouchUpOutsideButtonOption:(id)arg1;
- (void)onTouchUpInsideButtonOption:(id)arg1;
- (int)stateRestoreFinishDialog;
- (int)stateRestoreConfirmDialog;
- (int)statePurchaseFinishDialog;
- (void)changePage:(int)arg1;
- (void)touchTokusyouButton;
- (void)touchRestoreButton;
- (void)touchReturnButton;
- (void)ExitDlg:(int)arg1 Result:(int)arg2;
- (int)stateSongList;
- (void)ExitCheckAgeDlg:(int)arg1 Result:(int)arg2;
- (void)gotoStateSongList;
- (int)stateRoot;
- (int)stateIdle;
- (int)stateWait;
- (int)stateWaitSubscriptionVersionDownload;
- (void)render;
- (void)renderKanyu;
- (void)renderPrice;
- (void)enableButtons;
- (void)switchPurchaseMode;
- (void)returnToRoot;
- (void)resume;
- (void)close;
- (void)start;
- (void)waitingSongListImageDownload;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)dealloc;
- (void)createAction:(int)arg1 posX:(float)arg2 posY:(float)arg3 moveLeft:(_Bool)arg4;
- (id)initWithManager:(id)arg1 currentTitleObjectFrameIndex:(int *)arg2 nextTitleObjectFrameIndex:(int *)arg3 titleObjectFrameIndex:(int)arg4 mainFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 closeButtonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg6 restoreButtonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg7 popupWindowFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg8 popupWindow2FrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg9 popupWindow3FrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg10 popupWindow4FrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg11 tfgDialogButton:(struct _AGTEXTUREFRAMEGROUP *)arg12 tfgDialogChoice:(struct _AGTEXTUREFRAMEGROUP *)arg13;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

