//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BGSceneBase.h"

@class ISceneScrollView, TaikoButton, TaikoWindow, UIButton;

@interface ISceneOptionSelectDialog : BGSceneBase
{
    int pauseState_;
    int pauseCounter_;
    unsigned int pauseBackColor_;
    int selectedOption_[4];
    TaikoButton *optionButton_[5];
    _Bool requestPageChange_;
    UIButton *requestPageChangeSender_;
    UIButton *pushingSender_;
    int currentGroup_;
    _Bool isShowNeiroObject_;
    float dogFallDistance_;
    float dogFallAmount_;
    int dogAnimationCounter_;
    int *currentTitleObjectFrameIndex_;
    int *nextTitleObjectFrameIndex_;
    int savedTitleObjectFrameIndex_;
    struct _AGOBJECT headObject_[6];
    struct _AGOBJECT headObject2_;
    struct _AGOBJECT headObject3_;
    struct _AGOBJECT optionObject_[5];
    struct _AGOBJECT selectObject_[4];
    struct _AGOBJECT selectBackObject_[4];
    struct _AGOBJECT descriptionObject_;
    struct _AGOBJECT okButtonObject_;
    struct _AGOBJECT closeButtonObject_;
    struct _AGOBJECT dogObject_[2];
    struct _AGOBJECT newMessageObject_[4];
    TaikoWindow *windows_[2];
    ISceneScrollView *toneScrollView_;
    _Bool isToneNew_;
}

- (_Bool)isUserInteractionEnabled;
- (void)onTouchDownButtonOption:(id)arg1;
- (void)onTouchUpOutsideButtonOption:(id)arg1;
- (void)onTouchUpInsideButtonOption:(id)arg1;
- (void)registerOption:(int)arg1;
- (int)stateOptionSelect;
- (int)stateNeiroSelect;
- (int)stateRoot;
- (void)render;
- (void)resetStateNeiroSelect;
- (void)resetStateOptionSelect;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)dealloc;
- (id)initWithManager:(id)arg1 currentTitleObjectFrameIndex:(int *)arg2 nextTitleObjectFrameIndex:(int *)arg3 frameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg4 okButtonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 closeButtonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg6 popupWindow1FrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg7 popupWindow2FrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg8 dog1FrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg9 dog2FrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg10 tfgNewIcon:(struct _AGTEXTUREFRAMEGROUP *)arg11 tfgToneBack:(struct _AGTEXTUREFRAMEGROUP *)arg12 tfgNewMessage:(struct _AGTEXTUREFRAMEGROUP *)arg13;

@end

