//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

@class NSMutableSet, TaikoEquipment, TaikoSECache, TaikoTextureCache;

@interface ISceneScrollView : ISceneBase
{
    unsigned int m_LayoutType;
    TaikoTextureCache *m_TextureCache;
    TaikoSECache *m_SeCache;
    struct _AGOBJECT m_Object;
    struct _AGOBJECT m_NewIconObject;
    struct _AGOBJECT m_ToneBackObject;
    NSMutableSet *m_NewEquipmentSet;
    int m_ViewSize;
    float m_ViewSpace;
    int m_ScrollSpeed;
    int m_ScrollCounter;
    int m_ScrollDistance;
    _Bool m_IsViewLoop;
    int m_SelectedItemIndex;
    int m_ItemsSize;
    TaikoEquipment *m_LastEquipment;
    struct CGPoint m_TouchStartPoint;
    _Bool m_TouchDragging;
    _Bool _isBusy;
    _Bool _isCenterTouched;
    _Bool _touchEnabled;
    int _soundCounter;
    float _alpha;
}

@property(nonatomic) _Bool touchEnabled; // @synthesize touchEnabled=_touchEnabled;
@property(readonly, nonatomic) _Bool isCenterTouched; // @synthesize isCenterTouched=_isCenterTouched;
@property(nonatomic) float alpha; // @synthesize alpha=_alpha;
@property(readonly, nonatomic) int soundCounter; // @synthesize soundCounter=_soundCounter;
@property(readonly, nonatomic) _Bool isBusy; // @synthesize isBusy=_isBusy;
- (void)disableNewOfEquipmentSet;
- (void)playKatsuOfCurrentItem;
- (void)playDonOfCurrentItem;
- (struct _AGTEXTUREFRAMEGROUP *)getFrameGroupOfLastItem;
- (struct _AGTEXTUREFRAMEGROUP *)getFrameGroupOfCurrentItem;
- (float)getScrollRate;
- (void)setCurrentSelectedItem;
- (void)selectItem:(int)arg1;
- (int)stateRoot;
- (void)render;
- (int)update;
- (void)suspend;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (id)initWithManager:(id)arg1 layoutType:(unsigned int)arg2 tfgNewIcon:(struct _AGTEXTUREFRAMEGROUP *)arg3 tfgToneBack:(struct _AGTEXTUREFRAMEGROUP *)arg4;

@end

