//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ISongInfo : NSObject
{
    unsigned int m_Version;
    NSString *m_PackageID;
    NSString *m_Path;
    NSString *m_ImagePackPath;
    NSString *m_Identifier;
    NSString *m_Title;
    unsigned int m_Genre;
    double m_PreviewStartTime;
    int m_CourseDifficulties[5];
    unsigned int m_MusicDataOffset;
    unsigned int m_MusicDataLength;
    unsigned int m_ScoreDataOffset[5];
    unsigned int m_ScoreDataLength[5];
    unsigned int m_ImagePackDataOffset;
    unsigned int m_nSongPackSortNum;
    int m_AnimationType;
    int m_DancerCount[5];
    int m_ChibiCount[5];
    int m_BgCount[2];
    unsigned int m_AnimationDataOffset;
    unsigned int m_AnimationDataLength;
    double m_ScoreDelayTime;
    _Bool m_HasBranch[5];
    unsigned int m_Length;
    unsigned int m_CheckSum;
    _Bool m_IsValid;
    NSString *m_Pronunciation;
    unsigned int m_Generation;
    double m_HookStart;
    double m_HookEnd;
    int m_NumberOfCourses;
    _Bool m_Purchased;
    _Bool _corrupt;
    _Bool _subscribed;
}

+ (unsigned int)hashCode:(id)arg1 length:(unsigned int)arg2;
+ (void)setAdditionalInfoDictionary:(id)arg1;
+ (void)initialize;
@property(nonatomic) _Bool subscribed; // @synthesize subscribed=_subscribed;
@property(readonly, nonatomic) _Bool corrupt; // @synthesize corrupt=_corrupt;
@property(readonly, nonatomic) int numberOfCourses; // @synthesize numberOfCourses=m_NumberOfCourses;
@property(readonly, nonatomic) double hookStart; // @synthesize hookStart=m_HookStart;
@property(readonly, nonatomic) _Bool purchased; // @synthesize purchased=m_Purchased;
@property(readonly, nonatomic) double scoreDelayTime; // @synthesize scoreDelayTime=m_ScoreDelayTime;
@property(readonly, nonatomic) int animationType; // @synthesize animationType=m_AnimationType;
@property(readonly, nonatomic) unsigned int imagePackDataOffset; // @synthesize imagePackDataOffset=m_ImagePackDataOffset;
@property(readonly, nonatomic) double previewStartTime; // @synthesize previewStartTime=m_PreviewStartTime;
@property(readonly, nonatomic) unsigned int generation; // @synthesize generation=m_Generation;
@property(readonly, nonatomic) unsigned int genre; // @synthesize genre=m_Genre;
@property(readonly, nonatomic) NSString *pronunciation; // @synthesize pronunciation=m_Pronunciation;
@property(readonly, nonatomic) NSString *title; // @synthesize title=m_Title;
@property(readonly, nonatomic) NSString *imagePackPath; // @synthesize imagePackPath=m_ImagePackPath;
@property(readonly, nonatomic) NSString *path; // @synthesize path=m_Path;
@property(readonly, nonatomic) NSString *packageID; // @synthesize packageID=m_PackageID;
@property(readonly, nonatomic) unsigned int genuineVersion; // @synthesize genuineVersion=m_Version;
- (_Bool)isSameMetadataWithFileAtPath:(id)arg1 packageID:(id)arg2 length:(unsigned int)arg3 checkSum:(unsigned int)arg4 packsortnum:(unsigned int)arg5 purchased:(_Bool)arg6;
- (int)generationSortValue;
- (int)genreSortValue;
- (id)animationData;
- (id)identifier;
- (int)getBgCount:(int)arg1;
- (int)getChibiCount:(int)arg1;
- (int)getDancerCount:(int)arg1;
- (struct __sFILE *)scoreFilePointerOfCourse:(unsigned int)arg1;
- (id)binDataOfCourse:(unsigned int)arg1;
- (int)difficultyOfCourse:(unsigned int)arg1;
- (id)musicData;
- (void)dealloc;
- (id)initWithFileAtPath:(id)arg1 packageID:(id)arg2 length:(unsigned int)arg3 checkSum:(unsigned int)arg4 packsortnum:(unsigned int)arg5 purchased:(_Bool)arg6;
- (_Bool)isValid;
- (_Bool)hasBranch:(int)arg1;
- (void)setupWithTaikoMusicData:(id)arg1;
- (void)updateInfo;
- (void)checkIPKBundled;
@property(readonly, nonatomic) _Bool titleImagesUnified;
- (_Bool)IPKBundled;
@property(readonly, nonatomic) _Bool shouldUpdate;
- (_Bool)hasUnifiedIPK;
@property(readonly, nonatomic) unsigned int version;
- (_Bool)hasAnimation;
@property(readonly, nonatomic) unsigned int songPackSortNum;

@end

