//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IStorePackage, NSString;

@interface IStoreSong : NSObject
{
    NSString *m_Title;
    NSString *m_FileName;
    unsigned int m_FileSize;
    unsigned int m_CheckSum;
    IStorePackage *m_Package;
    _Bool m_Downloaded;
    unsigned int m_nSongPackSortNum;
    NSString *m_Identifier;
}

@property(nonatomic) _Bool downloaded; // @synthesize downloaded=m_Downloaded;
@property(readonly, nonatomic) IStorePackage *package; // @synthesize package=m_Package;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=m_Identifier;
@property(readonly, nonatomic) unsigned int packSortNum; // @synthesize packSortNum=m_nSongPackSortNum;
@property(readonly, nonatomic) unsigned int checkSum; // @synthesize checkSum=m_CheckSum;
@property(readonly, nonatomic) unsigned int fileSize; // @synthesize fileSize=m_FileSize;
@property(readonly, nonatomic) NSString *fileName; // @synthesize fileName=m_FileName;
@property(readonly, nonatomic) NSString *title; // @synthesize title=m_Title;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 identifier:(id)arg2 fileSize:(unsigned int)arg3 checkSum:(unsigned int)arg4 packsortnum:(unsigned int)arg5 package:(id)arg6;

@end

