//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TaikoPackageInfo;

@interface LinkageProduct : NSObject
{
    int _error;
    long long _tag;
    TaikoPackageInfo *_linkage;
    NSString *_identifier;
}

@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) TaikoPackageInfo *linkage; // @synthesize linkage=_linkage;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(nonatomic) int error; // @synthesize error=_error;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;

@end

