//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ISceneManager, NSMutableArray, PlayerUserData;

@interface LumenManager : NSObject
{
    struct Context *m_Context;
    struct LumenAlloc *m_Alloc;
    struct LumenRenderer *m_Renderer;
    struct LumenLoader *m_Loader;
    struct LumenMouseInput *m_MouseInput;
    struct LumenSoundPlayer *m_SoundPlayer;
    ISceneManager *m_Manager;
    NSMutableArray *m_PlayerArray;
    PlayerUserData *m_CurrentSoundPlayer;
    struct _AGOBJECT *m_CurrentObjectArray;
    struct _AGOBJECT *m_CurrentObject;
    int m_CurrentBlendMode;
    struct ColorTransform m_CurrentColorTransform;
    unsigned int m_CurrentColor;
    struct matrix_2x3_wrapper<lumen::matrix_2x3<float>, float> m_CurrentWorldMatrix;
    unsigned int m_CurrentLoadImageResourceID;
    int m_CurrentLayerLevel;
    unsigned int m_TouchState;
    struct CGPoint m_TouchPoint;
    _Bool m_EnableMouseInput;
    struct Variant m_CurrentFunctionResult;
}

+ (_Bool)parsePartsHeaderFromData:(id)arg1 context:(struct _AnimationContextHeader *)arg2 parts:(struct _AnimationPartsHeader *)arg3;
+ (_Bool)parseHeaderFromData:(id)arg1 contextType:(unsigned char)arg2 header:(struct _LumenAnimationDataHeader *)arg3 context:(struct _AnimationContextHeader *)arg4;
+ (_Bool)checkSignatureFromData:(id)arg1;
+ (const char *)partsName:(int)arg1;
- (id).cxx_construct;
- (_Bool)isPlay:(void *)arg1;
- (void)resetMovie:(void *)arg1;
- (float)getSpeed:(void *)arg1;
- (void)setSpeed:(void *)arg1 speed:(float)arg2;
- (float)getMovieHeight:(void *)arg1;
- (float)getMovieWidth:(void *)arg1;
- (void)setMovieScale:(void *)arg1 xScale:(float)arg2 yScale:(float)arg3;
- (void)setMoviePosition:(void *)arg1 x:(float)arg2 y:(float)arg3;
- (int)getCurrentActionScriptResultInt;
- (void)callActionScriptParam3:(void *)arg1 functionName:(id)arg2 param:(id)arg3 type:(int)arg4 param2:(id)arg5 type2:(int)arg6 param3:(id)arg7 type3:(int)arg8;
- (void)callActionScriptParam2:(void *)arg1 functionName:(id)arg2 param:(id)arg3 type:(int)arg4 param2:(id)arg5 type2:(int)arg6;
- (void)callActionScriptParam:(void *)arg1 functionName:(id)arg2 param:(id)arg3 type:(int)arg4;
- (void)callActionScriptInt:(void *)arg1 functionName:(id)arg2 param:(int)arg3;
- (void)callActionScriptBool:(void *)arg1 functionName:(id)arg2 param:(_Bool)arg3;
- (void)callActionScript:(void *)arg1 functionName:(id)arg2;
- (void)drawMovie:(void *)arg1;
- (void)drawAll;
- (void)updateMovie:(void *)arg1;
- (void)gcWithUpdateAll:(_Bool)arg1;
- (void *)loadWithData:(id)arg1 url:(const char *)arg2 texFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3 texNum:(int)arg4 isFloatVertex:(_Bool)arg5 sampleNum:(int)arg6 bgmName:(id)arg7 tfgArray:(struct _AGTEXTUREFRAMEGROUP *)arg8 texNumArray:(int *)arg9;
- (void *)load:(id)arg1 texFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg2 texNum:(int)arg3 isFloatVertex:(_Bool)arg4 sampleNum:(int)arg5 bgmName:(id)arg6 tfgArray:(struct _AGTEXTUREFRAMEGROUP *)arg7 texNumArray:(int *)arg8;
- (void)finishMemoryPoolMode;
- (void)startMemoryPoolMode:(unsigned long long)arg1;
- (void)enableMouseInput:(_Bool)arg1;
- (void)updateTouchState:(unsigned int)arg1 touchPoint:(struct CGPoint)arg2;
- (void)resetContext;
- (void)dealloc;
- (id)initWithManager:(id)arg1;

@end

