//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString, NSURL, OADataFetcher, OAMutableURLRequest, OAServiceTicket;
@protocol OACallDelegate;

@interface OACall : NSObject
{
    NSURL *url;	// 8 = 0x8
    NSString *method;	// 16 = 0x10
    NSArray *parameters;	// 24 = 0x18
    NSDictionary *files;	// 32 = 0x20
    NSObject<OACallDelegate> *delegate;	// 40 = 0x28
    SEL finishedSelector;	// 48 = 0x30
    OADataFetcher *fetcher;	// 56 = 0x38
    OAMutableURLRequest *request;	// 64 = 0x40
    OAServiceTicket *ticket;	// 72 = 0x48
}

@property(retain, nonatomic) OAServiceTicket *ticket; // @synthesize ticket;
@property(readonly) NSDictionary *files; // @synthesize files;
@property(readonly) NSArray *parameters; // @synthesize parameters;
@property(readonly) NSString *method; // @synthesize method;
@property(readonly) NSURL *url; // @synthesize url;
- (void)perform:(id)arg1 token:(id)arg2 realm:(id)arg3 delegate:(id)arg4 didFinish:(SEL)arg5;
- (void)callFinished:(id)arg1 withData:(id)arg2;
- (void)callFailed:(id)arg1 withError:(id)arg2;
- (void)dealloc;
- (id)initWithURL:(id)arg1 method:(id)arg2 parameters:(id)arg3 files:(id)arg4;
- (id)initWithURL:(id)arg1 parameters:(id)arg2 files:(id)arg3;
- (id)initWithURL:(id)arg1 method:(id)arg2 parameters:(id)arg3;
- (id)initWithURL:(id)arg1 parameters:(id)arg2;
- (id)initWithURL:(id)arg1 method:(id)arg2;
- (id)initWithURL:(id)arg1;
- (id)init;

@end

