//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface OAConsumer : NSObject
{
    NSString *key;
    NSString *secret;
}

@property(copy) NSString *secret; // @synthesize secret;
@property(copy) NSString *key; // @synthesize key;
- (_Bool)isEqualToConsumer:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithKey:(id)arg1 secret:(id)arg2;

@end

