//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OAConsumer : NSObject
{
    NSString *key;	// 8 = 0x8
    NSString *secret;	// 16 = 0x10
}

@property(copy) NSString *secret; // @synthesize secret;
@property(copy) NSString *key; // @synthesize key;
- (_Bool)isEqualToConsumer:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithKey:(id)arg1 secret:(id)arg2;

@end

