//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableData, NSURLConnection, NSURLResponse, OAMutableURLRequest;

@interface OADataFetcher : NSObject
{
    OAMutableURLRequest *request;	// 8 = 0x8
    NSURLResponse *response;	// 16 = 0x10
    NSURLConnection *connection;	// 24 = 0x18
    NSMutableData *responseData;	// 32 = 0x20
    id delegate;	// 40 = 0x28
    SEL didFinishSelector;	// 48 = 0x30
    SEL didFailSelector;	// 56 = 0x38
}

- (void)fetchDataWithRequest:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3 didFailSelector:(SEL)arg4;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)dealloc;
- (id)init;

@end

