//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableURLRequest.h>

@class NSString, OAConsumer, OAToken;
@protocol OASignatureProviding;

@interface OAMutableURLRequest : NSMutableURLRequest
{
    OAConsumer *consumer;	// 16 = 0x10
    OAToken *token;	// 24 = 0x18
    NSString *realm;	// 32 = 0x20
    NSString *signature;	// 40 = 0x28
    id <OASignatureProviding> signatureProvider;	// 48 = 0x30
    NSString *nonce;	// 56 = 0x38
    NSString *timestamp;	// 64 = 0x40
}

@property(readonly) NSString *nonce; // @synthesize nonce;
@property(readonly) NSString *signature; // @synthesize signature;
- (void)dealloc;
- (id)_signatureBaseString;
- (void)_generateNonce;
- (void)_generateTimestamp;
- (void)prepare;
- (id)initWithURL:(id)arg1 consumer:(id)arg2 token:(id)arg3 realm:(id)arg4 signatureProvider:(id)arg5 nonce:(id)arg6 timestamp:(id)arg7;
- (id)initWithURL:(id)arg1 consumer:(id)arg2 token:(id)arg3 realm:(id)arg4 signatureProvider:(id)arg5;

@end

