//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString, NSURLResponse, OAMutableURLRequest;

@interface OAServiceTicket : NSObject
{
    OAMutableURLRequest *request;	// 8 = 0x8
    NSURLResponse *response;	// 16 = 0x10
    NSData *data;	// 24 = 0x18
    _Bool didSucceed;	// 32 = 0x20
}

@property(readonly) _Bool didSucceed; // @synthesize didSucceed;
@property(readonly) NSData *data; // @synthesize data;
@property(readonly) NSURLResponse *response; // @synthesize response;
@property(readonly) OAMutableURLRequest *request; // @synthesize request;
@property(readonly) NSString *body;
- (void)dealloc;
- (id)initWithRequest:(id)arg1 response:(id)arg2 data:(id)arg3 didSucceed:(_Bool)arg4;

@end

