//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PlayerUserData : NSObject
{
    struct _AGOBJECT *objectArray;	// 8 = 0x8
    struct _AASAMPLE *sampleArray;	// 16 = 0x10
    int sampleNum;	// 24 = 0x18
    int bgmIndex;	// 28 = 0x1c
    NSString *_lmName;	// 32 = 0x20
    NSString *_bgmResourceName;	// 40 = 0x28
}

@property(copy, nonatomic) NSString *bgmResourceName; // @synthesize bgmResourceName=_bgmResourceName;
@property(copy, nonatomic) NSString *lmName; // @synthesize lmName=_lmName;
- (void)dealloc;

@end

