//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BGDownloadDelegate.h"

@class BGDownload, NSData, NSMutableArray, NSString;

@interface RankingBonusInfo : NSObject <BGDownloadDelegate>
{
    _Bool _isDownloadError;
    NSString *_identifier;
    NSString *_name;
    NSString *_nameURL;
    NSMutableArray *_points;
    NSMutableArray *_ranks;
    BGDownload *_download;
    NSData *_data;
    NSString *_cacheKey;
}

@property(readonly, nonatomic) _Bool isDownloadError; // @synthesize isDownloadError=_isDownloadError;
@property(copy, nonatomic) NSString *cacheKey; // @synthesize cacheKey=_cacheKey;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) BGDownload *download; // @synthesize download=_download;
@property(retain, nonatomic) NSMutableArray *ranks; // @synthesize ranks=_ranks;
@property(retain, nonatomic) NSMutableArray *points; // @synthesize points=_points;
@property(copy, nonatomic) NSString *nameURL; // @synthesize nameURL=_nameURL;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (id)imageData;
- (void)removeCache;
- (void)purge;
- (void)dealloc;

@end

