//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BGDownloadDelegate-Protocol.h"

@class BGDownload, NSData, NSMutableArray, NSString;

@interface RankingBonusInfo : NSObject <BGDownloadDelegate>
{
    _Bool _isDownloadError;	// 8 = 0x8
    NSString *_identifier;	// 16 = 0x10
    NSString *_name;	// 24 = 0x18
    NSString *_nameURL;	// 32 = 0x20
    NSMutableArray *_points;	// 40 = 0x28
    NSMutableArray *_ranks;	// 48 = 0x30
    BGDownload *_download;	// 56 = 0x38
    NSData *_data;	// 64 = 0x40
    NSString *_cacheKey;	// 72 = 0x48
}

@property(readonly, nonatomic) _Bool isDownloadError; // @synthesize isDownloadError=_isDownloadError;
@property(copy, nonatomic) NSString *cacheKey; // @synthesize cacheKey=_cacheKey;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) BGDownload *download; // @synthesize download=_download;
@property(retain, nonatomic) NSMutableArray *ranks; // @synthesize ranks=_ranks;
@property(retain, nonatomic) NSMutableArray *points; // @synthesize points=_points;
@property(copy, nonatomic) NSString *nameURL; // @synthesize nameURL=_nameURL;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (id)imageData;
- (void)removeCache;
- (void)purge;
- (void)dealloc;

@end

