//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TOSBaseDlg.h"

@class NSString;

@interface SimpleReturnDlg : TOSBaseDlg
{
    NSString *textkey;
    int dlgformat;
    int layoutype;
}

- (void)BtnActionReturn:(id)arg1;
- (id)initWithLayoutType:(int)arg1 Manager:(id)arg2 TextKey:(id)arg3 Format:(int)arg4;
- (id)initWithLayoutType:(int)arg1 Manager:(id)arg2 TextKey:(id)arg3;
- (void)viewDidLoad;

@end

