//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface SubscriptionDistributeSongInfo : NSObject <NSCoding>
{
    _Bool _newFlag;
    _Bool _canTrialListen;
    _Bool _downloaded;
    _Bool _purchased;
    unsigned int _fileSize;
    unsigned int _checkSum;
    unsigned int _songPackSortNum;
    unsigned int _genre;
    unsigned int _generation;
    NSString *_songID;
    NSString *_productID;
    NSString *_name;
    NSString *_pronunciation;
}

@property(nonatomic) _Bool purchased; // @synthesize purchased=_purchased;
@property(nonatomic) _Bool downloaded; // @synthesize downloaded=_downloaded;
@property(nonatomic) _Bool canTrialListen; // @synthesize canTrialListen=_canTrialListen;
@property(nonatomic) _Bool newFlag; // @synthesize newFlag=_newFlag;
@property(nonatomic) unsigned int generation; // @synthesize generation=_generation;
@property(nonatomic) unsigned int genre; // @synthesize genre=_genre;
@property(nonatomic) unsigned int songPackSortNum; // @synthesize songPackSortNum=_songPackSortNum;
@property(nonatomic) unsigned int checkSum; // @synthesize checkSum=_checkSum;
@property(nonatomic) unsigned int fileSize; // @synthesize fileSize=_fileSize;
@property(retain, nonatomic) NSString *pronunciation; // @synthesize pronunciation=_pronunciation;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *productID; // @synthesize productID=_productID;
@property(retain, nonatomic) NSString *songID; // @synthesize songID=_songID;
- (void)createTexture:(id)arg1 texture:(struct _AGTEXTURE *)arg2 frameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3;
- (_Bool)isValidImage:(id)arg1;
- (int)generationSortValue;
- (int)genreSortValue;
- (id)identifier;
- (_Bool)titleImagesUnified;
- (int)numberOfCourses;
- (_Bool)shouldUpdate;
- (_Bool)subscribed;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

