//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TaikoCacheEntry-Protocol.h"

@class NSString;
@protocol TaikoCacheEntrySource;

@interface TaikoTextureCacheEntry : NSObject <TaikoCacheEntry>
{
    id <TaikoCacheEntrySource> source_;	// 8 = 0x8
    struct _AGTEXTURE texture_;	// 16 = 0x10
    struct _AGTEXTUREFRAMEGROUP textureFrameGroup_;	// 72 = 0x48
}

@property(readonly, nonatomic) struct _AGTEXTUREFRAMEGROUP *textureFrameGroup;
@property(readonly, nonatomic) struct _AGTEXTURE *texture;
- (void)destroy;
- (id)source;
- (void)dealloc;
- (id)initWithSource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

