//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BGSNSInterfaceDelegate-Protocol.h"

@class BGSNSInterfaceError, NSString;
@protocol TaikoUpdateCheckerDelegate;

@interface TaikoUpdateChecker : NSObject <BGSNSInterfaceDelegate>
{
    BGSNSInterfaceError *error_;	// 8 = 0x8
    id <TaikoUpdateCheckerDelegate> delegate_;	// 16 = 0x10
    _Bool _checking;	// 24 = 0x18
    _Bool _finished;	// 25 = 0x19
    int _result;	// 28 = 0x1c
}

@property(readonly, nonatomic) int result; // @synthesize result=_result;
@property(readonly, nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
@property(readonly, nonatomic, getter=isChecking) _Bool checking; // @synthesize checking=_checking;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)openAppStore;
- (void)showForcedUpdateAlert;
- (void)showRecommendedUpdateAlert;
- (_Bool)processResultWithDelegate:(id)arg1;
- (void)start;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

