//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TaikoEquipment.h"

@interface TaikoEquipmentTaiko : TaikoEquipment
{
}

- (id)initWithType:(unsigned int)arg1 identifier:(id)arg2 dataPath:(id)arg3;

@end

