//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TaikoSceneNode.h"

@class TaikoAction;
@protocol TaikoWindowDelegate;

@interface TaikoWindow : TaikoSceneNode
{
    struct _AGOBJECT windowLeftObject_;	// 80 = 0x50
    struct _AGOBJECT windowMiddleObject_;	// 136 = 0x88
    struct _AGOBJECT windowRightObject_;	// 192 = 0xc0
    TaikoAction *windowInAction_;	// 248 = 0xf8
    TaikoAction *windowOutAction_;	// 256 = 0x100
    TaikoAction *windowAction_;	// 264 = 0x108
    unsigned int shadowAlpha_;	// 272 = 0x110
    _Bool updated_;	// 276 = 0x114
    _Bool hidden_;	// 277 = 0x115
    _Bool finished_;	// 278 = 0x116
    _Bool _active;	// 279 = 0x117
    id <TaikoWindowDelegate> _delegate;	// 280 = 0x118
    struct CGPoint _origin;	// 288 = 0x120
}

+ (id)windowWithWindowTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1 windowMiddleRect:(struct CGRect)arg2 animationType:(unsigned int)arg3 inDuration:(int)arg4 outDuration:(int)arg5;
@property(readonly, nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) struct CGPoint origin; // @synthesize origin=_origin;
@property(nonatomic) id <TaikoWindowDelegate> delegate; // @synthesize delegate=_delegate;
- (void)setHidden:(_Bool)arg1;
- (_Bool)hidden;
@property(readonly, nonatomic) unsigned int shadowAlpha; // @synthesize shadowAlpha=shadowAlpha_;
- (void)startDisappearing;
- (void)startAppearing;
- (void)render;
- (void)update;
- (void)setFrameIndexOffset:(int)arg1;
- (void)resetColor;
- (void)dealloc;
- (id)initWithWindowTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1 windowMiddleRect:(struct CGRect)arg2 animationType:(unsigned int)arg3 inDuration:(int)arg4 outDuration:(int)arg5;

@end

