//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TaikoAction.h"

@interface TaikoRepeatAction : TaikoAction
{
    TaikoAction *action_;
    _Bool infinite_;
}

- (void)rewind;
- (_Bool)updateAGObject:(struct _AGOBJECT *)arg1;
- (id)initWithAction:(id)arg1;
- (id)initWithAction:(id)arg1 count:(unsigned long long)arg2;
- (void)dealloc;

@end

