//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ISceneBase, IStoreSong, NSDictionary, NSMutableArray, NSMutableDictionary, SKPaymentTransaction, SKProductsRequest;
@protocol SKProductsRequestDelegate><BGSNSInterfaceDelegate;

@interface TaikoRestore : NSObject
{
    ISceneBase<SKProductsRequestDelegate><BGSNSInterfaceDelegate> *m_Scene;	// 8 = 0x8
    SKProductsRequest *m_ProductsRequest;	// 16 = 0x10
    NSMutableArray *m_PackageArray;	// 24 = 0x18
    NSMutableArray *m_AllPackages;	// 32 = 0x20
    NSMutableArray *m_OpenPackages;	// 40 = 0x28
    NSDictionary *m_PackageDictionary;	// 48 = 0x30
    NSMutableDictionary *m_Transactions;	// 56 = 0x38
    int m_NumberOfSongs;	// 64 = 0x40
    NSMutableArray *m_SongArray;	// 72 = 0x48
    NSMutableArray *m_DownloadingPackages;	// 80 = 0x50
    IStoreSong *m_CurrentSong;	// 88 = 0x58
    SKPaymentTransaction *m_CurrentTransaction;	// 96 = 0x60
}

@property(nonatomic) NSMutableDictionary *transactions; // @synthesize transactions=m_Transactions;
- (int)getWillDownloadSongTotalNum:(id)arg1;
- (id)productIdentifierForKey:(id)arg1;
- (_Bool)finishDownloadSubscriptionPackage:(id)arg1;
- (_Bool)necessityToDownloadSong:(id)arg1;
- (void)retryDownloadNextSubscriptionSongData;
- (_Bool)startDownloadNextSubscriptionSongData;
- (unsigned long long)startDownloadSongsForPlan:(id)arg1;
- (_Bool)setSubscriptionSongList:(id)arg1;
- (void)songDataDownloadFailed;
- (_Bool)finishDownloadPackage:(id)arg1;
- (int)saveMusicData:(id)arg1 song:(id)arg2;
- (int)songDataDownloaded:(id)arg1 data:(id)arg2;
- (_Bool)startDownloadNextPrizeSongDataWithComponents:(id)arg1;
- (unsigned long long)startDownloadPrizeSongDataOneByOne:(_Bool)arg1 components:(id)arg2;
- (void)retryDownloadNextSongData;
- (_Bool)startDownloadNextSongData;
- (unsigned long long)startDownloadSongDataOneByOne:(_Bool)arg1;
- (unsigned long long)startDownloadSongData:(_Bool)arg1;
- (void)packRestoreFailed;
- (_Bool)packRestored:(id)arg1;
- (void)retryRestoreNextPack;
- (_Bool)startRestoreNextPack;
- (void)startRestorePackOneByOne;
- (_Bool)restoreTransactionsFailedWithError:(id)arg1;
- (int)restoreTransactionsCompleted;
- (void)transactionStateRestored:(id)arg1;
- (void)startRestoreTransactions;
- (void)productsRequestReceiveFailed:(id)arg1 error:(id)arg2;
- (id)productsRequestReceiveResponse:(id)arg1 response:(id)arg2;
- (void)cancelProductsRequest;
- (void)finishProductsRequest;
- (void)issueProductsRequest:(id)arg1;
- (id)finishLoadingSongList:(id)arg1 requestSKProduct:(_Bool)arg2;
- (_Bool)shouldGetSongList;
- (void)clearTransactions;
- (void)dealloc;
- (id)initWithScene:(id)arg1;

@end

