//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class TaikoCache;

@interface TaikoCacheOperation : NSOperation
{
    _Bool runnable_;
    TaikoCache *_cache;
    id <TaikoCacheEntrySource> _source;
    CDUnknownBlockType _creationBlock;
    CDUnknownBlockType _cancellingBlock;
}

@property(copy, nonatomic) CDUnknownBlockType cancellingBlock; // @synthesize cancellingBlock=_cancellingBlock;
@property(copy, nonatomic) CDUnknownBlockType creationBlock; // @synthesize creationBlock=_creationBlock;
@property(retain, nonatomic) id <TaikoCacheEntrySource> source; // @synthesize source=_source;
@property(nonatomic) TaikoCache *cache; // @synthesize cache=_cache;
- (void)stop;
- (void)main;
- (void)dealloc;
- (id)init;

@end

