//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BGDownloadDelegate.h"
#import "NSCoding.h"

@class NSMutableDictionary, NSString, TaikoPrizeImageInfo;

@interface TaikoPrize : NSObject <BGDownloadDelegate, NSCoding>
{
    NSMutableDictionary *dictionary_;
    TaikoPrizeImageInfo *images_[3];
    _Bool _new;
    _Bool _duplicate;
    _Bool _secret;
    unsigned int _type;
    int _refundBonuspoint;
    NSString *_identifier;
    NSString *_expireDate;
}

@property(readonly, nonatomic, getter=isSecret) _Bool secret; // @synthesize secret=_secret;
@property(readonly, nonatomic) NSString *expireDate; // @synthesize expireDate=_expireDate;
@property(readonly, nonatomic) int refundBonuspoint; // @synthesize refundBonuspoint=_refundBonuspoint;
@property(readonly, nonatomic, getter=isDuplicate) _Bool duplicate; // @synthesize duplicate=_duplicate;
@property(readonly, nonatomic, getter=isNew) _Bool new; // @synthesize new=_new;
@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (void)removeCacheWithType:(unsigned int)arg1;
- (void)purgeImageDataWithType:(unsigned int)arg1;
- (id)imageDataWithType:(unsigned int)arg1 error:(id *)arg2;
- (id)imageURLStringWithType:(unsigned int)arg1;
- (void)setup;
- (id)initWithDictionary:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

