//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableDictionary;

@interface TaikoPackageInfo : NSObject <NSCoding>
{
    NSMutableDictionary *dictionary_;
}

- (_Bool)checkExerciseImage:(id)arg1;
- (_Bool)checkCollaboImageWithMusicPack:(id)arg1 dirPath:(id)arg2 manager:(id)arg3;
- (_Bool)checkCollaboImage:(id)arg1;
- (_Bool)checkExerciseTimeLimit;
- (_Bool)checkCollaboTimeLimit;
- (_Bool)isCollaboSongTypePurchaseOrSubscription;
- (unsigned int)getCollaboSongType:(id)arg1;
- (_Bool)isExercise;
- (_Bool)isCollabo;
- (_Bool)isPrimordialCollabo;
@property(nonatomic, getter=isReady) _Bool ready;
- (id)description;
@property(readonly, nonatomic) unsigned int type;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForKey:(id)arg1;
- (id)initWithDictionary:(id)arg1 type:(unsigned int)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

