//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"

@class AVAudioPlayer, NSString;

@interface TaikoAudioPlayer : NSObject <AVAudioPlayerDelegate>
{
    AVAudioPlayer *player_;
    id <AVAudioPlayerDelegate> delegate_;
    long long numberOfArbitraryTimeLoops_;
    double loopStartTime_;
}

- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)stop;
- (_Bool)prepareToPlay;
- (_Bool)play;
@property double loopStartTime;
@property double currentTime;
@property long long numberOfLoops;
@property float volume;
@property id <AVAudioPlayerDelegate> delegate;
@property(readonly, getter=isPlaying) _Bool playing;
- (void)dealloc;
- (id)initWithData:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

