//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TaikoCacheEntry.h"

@class NSString;

@interface TaikoTextureCacheEntry : NSObject <TaikoCacheEntry>
{
    id <TaikoCacheEntrySource> source_;
    struct _AGTEXTURE texture_;
    struct _AGTEXTUREFRAMEGROUP textureFrameGroup_;
}

@property(readonly, nonatomic) struct _AGTEXTUREFRAMEGROUP *textureFrameGroup;
@property(readonly, nonatomic) struct _AGTEXTURE *texture;
- (void)destroy;
- (id)source;
- (void)dealloc;
- (id)initWithSource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

