//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class AgreementManager, ModalViewController;

@interface TOSBaseDlg : UIViewController
{
    ModalViewController *modalctrl;
    TOSBaseDlg *returndlg;
    CDStruct_08b27754 *dlglayout;
    AgreementManager *agmanager;
}

- (void)setViewController:(id)arg1 ReturnDlg:(id)arg2;
- (void)setViewController:(id)arg1;
- (id)initWithManager:(id)arg1;
- (void)loadLayout:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

