//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TwitterAccessToken : NSObject
{
    NSString *m_accessToken;
    NSString *m_accessTokenSecret;
}

@property(copy) NSString *token; // @synthesize token=m_accessToken;
@property(copy) NSString *tokenSecret; // @synthesize tokenSecret=m_accessTokenSecret;
- (_Bool)isEqualToAccessToken:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (id)initWithToken:(id)arg1 Secret:(id)arg2;

@end

