//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURLConnection, TwitterAccessToken;

@interface TwitterApiStatus : NSObject
{
    id m_delegate;
    NSString *m_consumerKey;
    NSString *m_consumerSecret;
    TwitterAccessToken *m_accessToken;
    NSURLConnection *m_urlConnection;
    int m_resStatus;
}

- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)requestUpdate:(id)arg1;
- (id)getRequest:(id)arg1 Quert:(id)arg2 Method:(id)arg3;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (id)initWithAccessToken:(id)arg1 ConsumerKey:(id)arg2 ConsumerSecuret:(id)arg3;

@end

