//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURLConnection, TwitterAccessToken;

@interface TwitterXAuth : NSObject
{
    id m_delegate;
    NSString *m_consumerKey;
    NSString *m_consumerSecret;
    NSString *m_userName;
    NSString *m_userPassword;
    NSString *m_requestToken;
    NSString *m_requestSecret;
    NSString *m_authURL;
    NSURLConnection *m_urlConnection;
    int m_resStatus;
    TwitterAccessToken *m_accessToken;
}

- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)requestAccessToken;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)initWithKey:(id)arg1 Secret:(id)arg2 Name:(id)arg3 Password:(id)arg4;

@end

