//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXBitArray, ZXGeneralAppIdDecoder;

@interface ZXAbstractExpandedDecoder : NSObject
{
    ZXGeneralAppIdDecoder *_generalDecoder;	// 8 = 0x8
    ZXBitArray *_information;	// 16 = 0x10
}

+ (id)createDecoder:(id)arg1;
@property(readonly, nonatomic) ZXBitArray *information; // @synthesize information=_information;
@property(readonly, nonatomic) ZXGeneralAppIdDecoder *generalDecoder; // @synthesize generalDecoder=_generalDecoder;
- (void).cxx_destruct;
- (id)parseInformationWithError:(id *)arg1;
- (id)initWithInformation:(id)arg1;

@end

