//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZXOneDReader.h"

@interface ZXAbstractRSSReader : ZXOneDReader
{
    unsigned int _decodeFinderCountersLen;	// 8 = 0x8
    unsigned int _dataCharacterCountersLen;	// 12 = 0xc
    unsigned int _oddRoundingErrorsLen;	// 16 = 0x10
    unsigned int _evenRoundingErrorsLen;	// 20 = 0x14
    unsigned int _oddCountsLen;	// 24 = 0x18
    unsigned int _evenCountsLen;	// 28 = 0x1c
    int *_decodeFinderCounters;	// 32 = 0x20
    int *_dataCharacterCounters;	// 40 = 0x28
    float *_oddRoundingErrors;	// 48 = 0x30
    float *_evenRoundingErrors;	// 56 = 0x38
    int *_oddCounts;	// 64 = 0x40
    int *_evenCounts;	// 72 = 0x48
}

+ (_Bool)isFinderPattern:(int *)arg1 countersLen:(unsigned int)arg2;
+ (void)decrement:(int *)arg1 arrayLen:(unsigned int)arg2 errors:(float *)arg3;
+ (void)increment:(int *)arg1 arrayLen:(unsigned int)arg2 errors:(float *)arg3;
+ (int)count:(int *)arg1 arrayLen:(unsigned int)arg2;
+ (int)parseFinderValue:(int *)arg1 countersSize:(unsigned int)arg2 finderPatternType:(int)arg3;
+ (void)initialize;
@property(readonly, nonatomic) unsigned int evenCountsLen; // @synthesize evenCountsLen=_evenCountsLen;
@property(readonly, nonatomic) int *evenCounts; // @synthesize evenCounts=_evenCounts;
@property(readonly, nonatomic) unsigned int oddCountsLen; // @synthesize oddCountsLen=_oddCountsLen;
@property(readonly, nonatomic) int *oddCounts; // @synthesize oddCounts=_oddCounts;
@property(readonly, nonatomic) unsigned int evenRoundingErrorsLen; // @synthesize evenRoundingErrorsLen=_evenRoundingErrorsLen;
@property(readonly, nonatomic) float *evenRoundingErrors; // @synthesize evenRoundingErrors=_evenRoundingErrors;
@property(readonly, nonatomic) unsigned int oddRoundingErrorsLen; // @synthesize oddRoundingErrorsLen=_oddRoundingErrorsLen;
@property(readonly, nonatomic) float *oddRoundingErrors; // @synthesize oddRoundingErrors=_oddRoundingErrors;
@property(readonly, nonatomic) unsigned int dataCharacterCountersLen; // @synthesize dataCharacterCountersLen=_dataCharacterCountersLen;
@property(readonly, nonatomic) int *dataCharacterCounters; // @synthesize dataCharacterCounters=_dataCharacterCounters;
@property(readonly, nonatomic) unsigned int decodeFinderCountersLen; // @synthesize decodeFinderCountersLen=_decodeFinderCountersLen;
@property(readonly, nonatomic) int *decodeFinderCounters; // @synthesize decodeFinderCounters=_decodeFinderCounters;
- (void)dealloc;
- (id)init;

@end

