//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZXParsedResult.h"

@class NSArray, NSString;

@interface ZXAddressBookParsedResult : ZXParsedResult
{
    NSArray *_names;	// 8 = 0x8
    NSArray *_nicknames;	// 16 = 0x10
    NSString *_pronunciation;	// 24 = 0x18
    NSArray *_phoneNumbers;	// 32 = 0x20
    NSArray *_phoneTypes;	// 40 = 0x28
    NSArray *_emails;	// 48 = 0x30
    NSArray *_emailTypes;	// 56 = 0x38
    NSString *_instantMessenger;	// 64 = 0x40
    NSString *_note;	// 72 = 0x48
    NSArray *_addresses;	// 80 = 0x50
    NSArray *_addressTypes;	// 88 = 0x58
    NSString *_title;	// 96 = 0x60
    NSString *_org;	// 104 = 0x68
    NSArray *_urls;	// 112 = 0x70
    NSString *_birthday;	// 120 = 0x78
    NSArray *_geo;	// 128 = 0x80
}

+ (id)addressBookParsedResultWithNames:(id)arg1 nicknames:(id)arg2 pronunciation:(id)arg3 phoneNumbers:(id)arg4 phoneTypes:(id)arg5 emails:(id)arg6 emailTypes:(id)arg7 instantMessenger:(id)arg8 note:(id)arg9 addresses:(id)arg10 addressTypes:(id)arg11 org:(id)arg12 birthday:(id)arg13 title:(id)arg14 urls:(id)arg15 geo:(id)arg16;
+ (id)addressBookParsedResultWithNames:(id)arg1 phoneNumbers:(id)arg2 phoneTypes:(id)arg3 emails:(id)arg4 emailTypes:(id)arg5 addresses:(id)arg6 addressTypes:(id)arg7;
@property(readonly, nonatomic) NSArray *geo; // @synthesize geo=_geo;
@property(readonly, copy, nonatomic) NSString *birthday; // @synthesize birthday=_birthday;
@property(readonly, nonatomic) NSArray *urls; // @synthesize urls=_urls;
@property(readonly, copy, nonatomic) NSString *org; // @synthesize org=_org;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSArray *addressTypes; // @synthesize addressTypes=_addressTypes;
@property(readonly, nonatomic) NSArray *addresses; // @synthesize addresses=_addresses;
@property(readonly, copy, nonatomic) NSString *note; // @synthesize note=_note;
@property(readonly, copy, nonatomic) NSString *instantMessenger; // @synthesize instantMessenger=_instantMessenger;
@property(readonly, nonatomic) NSArray *emailTypes; // @synthesize emailTypes=_emailTypes;
@property(readonly, nonatomic) NSArray *emails; // @synthesize emails=_emails;
@property(readonly, nonatomic) NSArray *phoneTypes; // @synthesize phoneTypes=_phoneTypes;
@property(readonly, nonatomic) NSArray *phoneNumbers; // @synthesize phoneNumbers=_phoneNumbers;
@property(readonly, copy, nonatomic) NSString *pronunciation; // @synthesize pronunciation=_pronunciation;
@property(readonly, nonatomic) NSArray *nicknames; // @synthesize nicknames=_nicknames;
@property(readonly, nonatomic) NSArray *names; // @synthesize names=_names;
- (void).cxx_destruct;
- (id)displayResult;
- (id)initWithNames:(id)arg1 nicknames:(id)arg2 pronunciation:(id)arg3 phoneNumbers:(id)arg4 phoneTypes:(id)arg5 emails:(id)arg6 emailTypes:(id)arg7 instantMessenger:(id)arg8 note:(id)arg9 addresses:(id)arg10 addressTypes:(id)arg11 org:(id)arg12 birthday:(id)arg13 title:(id)arg14 urls:(id)arg15 geo:(id)arg16;
- (id)initWithNames:(id)arg1 phoneNumbers:(id)arg2 phoneTypes:(id)arg3 emails:(id)arg4 emailTypes:(id)arg5 addresses:(id)arg6 addressTypes:(id)arg7;

@end

