//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, ZXBitMatrix;
@protocol ZXResultPointCallback;

@interface ZXAlignmentPatternFinder : NSObject
{
    int _startX;	// 8 = 0x8
    int _startY;	// 12 = 0xc
    int _width;	// 16 = 0x10
    int _height;	// 20 = 0x14
    float _moduleSize;	// 24 = 0x18
    ZXBitMatrix *_image;	// 32 = 0x20
    NSMutableArray *_possibleCenters;	// 40 = 0x28
    int *_crossCheckStateCount;	// 48 = 0x30
    id <ZXResultPointCallback> _resultPointCallback;	// 56 = 0x38
}

@property(nonatomic) __weak id <ZXResultPointCallback> resultPointCallback; // @synthesize resultPointCallback=_resultPointCallback;
@property(nonatomic) int *crossCheckStateCount; // @synthesize crossCheckStateCount=_crossCheckStateCount;
@property(nonatomic) float moduleSize; // @synthesize moduleSize=_moduleSize;
@property(nonatomic) int height; // @synthesize height=_height;
@property(nonatomic) int width; // @synthesize width=_width;
@property(nonatomic) int startY; // @synthesize startY=_startY;
@property(nonatomic) int startX; // @synthesize startX=_startX;
@property(retain, nonatomic) NSMutableArray *possibleCenters; // @synthesize possibleCenters=_possibleCenters;
@property(retain, nonatomic) ZXBitMatrix *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (id)handlePossibleCenter:(int *)arg1 i:(int)arg2 j:(int)arg3;
- (float)crossCheckVertical:(int)arg1 centerJ:(int)arg2 maxCount:(int)arg3 originalStateCountTotal:(int)arg4;
- (_Bool)foundPatternCross:(int *)arg1;
- (float)centerFromEnd:(int *)arg1 end:(int)arg2;
- (id)findWithError:(id *)arg1;
- (void)dealloc;
- (id)initWithImage:(id)arg1 startX:(int)arg2 startY:(int)arg3 width:(int)arg4 height:(int)arg5 moduleSize:(float)arg6 resultPointCallback:(id)arg7;

@end

