//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, ZXBitMatrix;

@interface ZXAlignmentPatternFinder : NSObject
{
    int _startX;
    int _startY;
    int _width;
    int _height;
    float _moduleSize;
    ZXBitMatrix *_image;
    NSMutableArray *_possibleCenters;
    int *_crossCheckStateCount;
    id <ZXResultPointCallback> _resultPointCallback;
}

@property(nonatomic) __weak id <ZXResultPointCallback> resultPointCallback; // @synthesize resultPointCallback=_resultPointCallback;
@property(nonatomic) int *crossCheckStateCount; // @synthesize crossCheckStateCount=_crossCheckStateCount;
@property(nonatomic) float moduleSize; // @synthesize moduleSize=_moduleSize;
@property(nonatomic) int height; // @synthesize height=_height;
@property(nonatomic) int width; // @synthesize width=_width;
@property(nonatomic) int startY; // @synthesize startY=_startY;
@property(nonatomic) int startX; // @synthesize startX=_startX;
@property(retain, nonatomic) NSMutableArray *possibleCenters; // @synthesize possibleCenters=_possibleCenters;
@property(retain, nonatomic) ZXBitMatrix *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (id)handlePossibleCenter:(int *)arg1 i:(int)arg2 j:(int)arg3;
- (float)crossCheckVertical:(int)arg1 centerJ:(int)arg2 maxCount:(int)arg3 originalStateCountTotal:(int)arg4;
- (_Bool)foundPatternCross:(int *)arg1;
- (float)centerFromEnd:(int *)arg1 end:(int)arg2;
- (id)findWithError:(id *)arg1;
- (void)dealloc;
- (id)initWithImage:(id)arg1 startX:(int)arg2 startY:(int)arg3 width:(int)arg4 height:(int)arg5 moduleSize:(float)arg6 resultPointCallback:(id)arg7;

@end

