//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXAztecDetectorResult;

@interface ZXAztecDecoder : NSObject
{
    int _codewordSize;	// 8 = 0x8
    int _invertedBitCount;	// 12 = 0xc
    int _numCodewords;	// 16 = 0x10
    ZXAztecDetectorResult *_ddata;	// 24 = 0x18
}

@property(nonatomic) int numCodewords; // @synthesize numCodewords=_numCodewords;
@property(nonatomic) int invertedBitCount; // @synthesize invertedBitCount=_invertedBitCount;
@property(retain, nonatomic) ZXAztecDetectorResult *ddata; // @synthesize ddata=_ddata;
@property(nonatomic) int codewordSize; // @synthesize codewordSize=_codewordSize;
- (void).cxx_destruct;
- (int)readCode:(_Bool *)arg1 startIndex:(int)arg2 length:(int)arg3;
- (id)removeDashedLines:(id)arg1;
- (unsigned long long)extractBits:(id)arg1 pBits:(_Bool **)arg2;
- (unsigned long long)correctBits:(_Bool *)arg1 bitsLength:(unsigned long long)arg2 pBits:(_Bool **)arg3 error:(id *)arg4;
- (id)character:(int)arg1 code:(int)arg2;
- (int)table:(unsigned short)arg1;
- (id)encodedData:(_Bool *)arg1 length:(unsigned long long)arg2 error:(id *)arg3;
- (id)decode:(id)arg1 error:(id *)arg2;

@end

