//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXBitMatrix;

@interface ZXAztecCode : NSObject
{
    _Bool _compact;	// 8 = 0x8
    int _codeWords;	// 12 = 0xc
    int _layers;	// 16 = 0x10
    int _size;	// 20 = 0x14
    ZXBitMatrix *_matrix;	// 24 = 0x18
}

@property(nonatomic) int size; // @synthesize size=_size;
@property(retain, nonatomic) ZXBitMatrix *matrix; // @synthesize matrix=_matrix;
@property(nonatomic) int layers; // @synthesize layers=_layers;
@property(nonatomic) _Bool compact; // @synthesize compact=_compact;
@property(nonatomic) int codeWords; // @synthesize codeWords=_codeWords;
- (void).cxx_destruct;

@end

