//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ZXWriter-Protocol.h"

@class NSString;

@interface ZXAztecWriter : NSObject <ZXWriter>
{
}

- (id)encode:(id)arg1 format:(int)arg2 encoding:(unsigned long long)arg3 eccPercent:(int)arg4;
- (id)encode:(id)arg1 format:(int)arg2 width:(int)arg3 height:(int)arg4 hints:(id)arg5 error:(id *)arg6;
- (id)encode:(id)arg1 format:(int)arg2 width:(int)arg3 height:(int)arg4 error:(id *)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

