//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZXBarcodeRow : NSObject
{
    int _rowLength;
    int _currentLocation;
    char *_row;
}

+ (id)barcodeRowWithWidth:(int)arg1;
@property(nonatomic) int currentLocation; // @synthesize currentLocation=_currentLocation;
@property(readonly, nonatomic) int rowLength; // @synthesize rowLength=_rowLength;
@property(readonly, nonatomic) char *row; // @synthesize row=_row;
- (char *)scaledRow:(int)arg1;
- (void)addBar:(_Bool)arg1 width:(int)arg2;
- (void)setX:(int)arg1 black:(_Bool)arg2;
- (void)setX:(int)arg1 value:(BOOL)arg2;
- (void)dealloc;
- (id)initWithWidth:(int)arg1;

@end

