//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZXBitSource : NSObject
{
    int _bitOffset;
    int _byteOffset;
    int _length;
    char *_bytes;
}

@property(nonatomic) int length; // @synthesize length=_length;
@property(nonatomic) char *bytes; // @synthesize bytes=_bytes;
@property(nonatomic) int byteOffset; // @synthesize byteOffset=_byteOffset;
@property(nonatomic) int bitOffset; // @synthesize bitOffset=_bitOffset;
- (int)available;
- (int)readBits:(int)arg1;
- (id)initWithBytes:(char *)arg1 length:(unsigned int)arg2;

@end

