//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXBlockPair : NSObject
{
    int _errorCorrectionLength;	// 8 = 0x8
    int _length;	// 12 = 0xc
    char *_dataBytes;	// 16 = 0x10
    char *_errorCorrectionBytes;	// 24 = 0x18
}

@property(readonly, nonatomic) int length; // @synthesize length=_length;
@property(readonly, nonatomic) int errorCorrectionLength; // @synthesize errorCorrectionLength=_errorCorrectionLength;
@property(readonly, nonatomic) char *errorCorrectionBytes; // @synthesize errorCorrectionBytes=_errorCorrectionBytes;
@property(readonly, nonatomic) char *dataBytes; // @synthesize dataBytes=_dataBytes;
- (void)dealloc;
- (id)initWithData:(char *)arg1 length:(unsigned int)arg2 errorCorrection:(char *)arg3 errorCorrectionLength:(unsigned int)arg4;

@end

