//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"
#import "CAAction.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, CALayer, NSString, ZXDecodeHints;

@interface ZXCapture : NSObject <CAAction, AVCaptureVideoDataOutputSampleBufferDelegate>
{
    AVCaptureSession *session;
    AVCaptureVideoPreviewLayer *layer;
    AVCaptureDevice *capture_device;
    AVCaptureDeviceInput *input;
    AVCaptureVideoDataOutput *output;
    id <ZXCaptureDelegate> delegate;
    int order_in_skip;
    int order_out_skip;
    _Bool running;
    _Bool on_screen;
    CALayer *luminance;
    CALayer *binary;
    unsigned long long width;
    unsigned long long height;
    unsigned long long reported_width;
    unsigned long long reported_height;
    NSString *captureToFilename;
    _Bool hard_stop;
    int camera;
    _Bool torch;
    _Bool mirror;
    int capture_device_index;
    struct CGAffineTransform transform;
    _Bool cameraIsReady;
    double rotation;
    ZXDecodeHints *hints;
    id <ZXReader> _reader;
    struct dispatch_queue_s *_captureQueue;
}

@property(nonatomic) struct dispatch_queue_s *captureQueue; // @synthesize captureQueue=_captureQueue;
@property(retain, nonatomic) id <ZXReader> reader; // @synthesize reader=_reader;
@property(retain, nonatomic) ZXDecodeHints *hints; // @synthesize hints;
@property(nonatomic) double rotation; // @synthesize rotation;
@property(nonatomic) struct CGAffineTransform transform; // @synthesize transform;
@property(copy, nonatomic) NSString *captureToFilename; // @synthesize captureToFilename;
@property(nonatomic) id <ZXCaptureDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
@property(nonatomic) _Bool torch;
@property(nonatomic) int camera;
@property(readonly, nonatomic) int back;
@property(readonly, nonatomic) int front;
@property(readonly, nonatomic) _Bool hasTorch;
@property(readonly, nonatomic) _Bool hasBack;
@property(readonly, nonatomic) _Bool hasFront;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)dealloc;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (void)runActionForKey:(id)arg1 object:(id)arg2 arguments:(id)arg3;
@property(readonly, nonatomic) CALayer *layer;
- (id)binary;
- (void)setBinary:(_Bool)arg1;
- (id)luminance;
- (void)setLuminance:(_Bool)arg1;
- (void)hard_stop;
- (void)start_stop;
- (void)start;
@property(readonly, nonatomic) AVCaptureVideoDataOutput *output;
- (void)setOutputAttributes;
- (void)stop;
- (id)session;
- (void)replaceInput;
@property(retain, nonatomic) AVCaptureDevice *captureDevice;
- (id)device;
- (void)order_skip;
@property(nonatomic) _Bool mirror;
@property(readonly, nonatomic) _Bool running;
- (id)init;
- (struct CGImage *)createRotatedImage:(struct CGImage *)arg1 degrees:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

