//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZXParsedResult.h"

@class NSArray, NSDate, NSString;

@interface ZXCalendarParsedResult : ZXParsedResult
{
    NSString *description_;	// 8 = 0x8
    _Bool _startAllDay;	// 16 = 0x10
    _Bool _endAllDay;	// 17 = 0x11
    NSString *_summary;	// 24 = 0x18
    NSDate *_start;	// 32 = 0x20
    NSDate *_end;	// 40 = 0x28
    NSString *_location;	// 48 = 0x30
    NSString *_organizer;	// 56 = 0x38
    NSArray *_attendees;	// 64 = 0x40
    double _latitude;	// 72 = 0x48
    double _longitude;	// 80 = 0x50
}

+ (id)calendarParsedResultWithSummary:(id)arg1 startString:(id)arg2 endString:(id)arg3 durationString:(id)arg4 location:(id)arg5 organizer:(id)arg6 attendees:(id)arg7 description:(id)arg8 latitude:(double)arg9 longitude:(double)arg10;
+ (void)initialize;
@property(readonly, nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(readonly, nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(readonly, nonatomic) NSArray *attendees; // @synthesize attendees=_attendees;
@property(readonly, nonatomic) NSString *organizer; // @synthesize organizer=_organizer;
@property(readonly, nonatomic) NSString *location; // @synthesize location=_location;
@property(readonly, nonatomic) _Bool endAllDay; // @synthesize endAllDay=_endAllDay;
@property(readonly, nonatomic) NSDate *end; // @synthesize end=_end;
@property(readonly, nonatomic) _Bool startAllDay; // @synthesize startAllDay=_startAllDay;
@property(readonly, nonatomic) NSDate *start; // @synthesize start=_start;
@property(readonly, nonatomic) NSString *summary; // @synthesize summary=_summary;
- (void).cxx_destruct;
- (long long)parseDurationMS:(id)arg1;
- (id)format:(_Bool)arg1 date:(id)arg2;
- (id)parseDate:(id)arg1;
- (id)displayResult;
- (id)description;
- (id)initWithSummary:(id)arg1 startString:(id)arg2 endString:(id)arg3 durationString:(id)arg4 location:(id)arg5 organizer:(id)arg6 attendees:(id)arg7 description:(id)arg8 latitude:(double)arg9 longitude:(double)arg10;

@end

