//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZXOneDReader.h"

@class NSMutableString;

@interface ZXCode93Reader : ZXOneDReader
{
    NSMutableString *_decodeRowResult;	// 8 = 0x8
}

@property(retain, nonatomic) NSMutableString *decodeRowResult; // @synthesize decodeRowResult=_decodeRowResult;
- (void).cxx_destruct;
- (_Bool)checkOneChecksum:(id)arg1 checkPosition:(int)arg2 weightMax:(int)arg3 error:(id *)arg4;
- (_Bool)checkChecksums:(id)arg1 error:(id *)arg2;
- (id)decodeExtended:(id)arg1;
- (unsigned short)patternToChar:(int)arg1;
- (int)toPattern:(int *)arg1 countersLen:(unsigned int)arg2;
- (_Bool)findAsteriskPattern:(id)arg1 a:(int *)arg2 b:(int *)arg3;
- (id)decodeRow:(int)arg1 row:(id)arg2 hints:(id)arg3 error:(id *)arg4;
- (id)init;

@end

