//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ZXOneDReader.h"

@class NSMutableString;

@interface ZXCodaBarReader : ZXOneDReader
{
    int _countersLen;
    int _counterLength;
    NSMutableString *_decodeRowResult;
    int *_counters;
}

+ (_Bool)arrayContains:(char *)arg1 length:(unsigned int)arg2 key:(unsigned short)arg3;
+ (void)initialize;
@property(nonatomic) int counterLength; // @synthesize counterLength=_counterLength;
@property(nonatomic) int countersLen; // @synthesize countersLen=_countersLen;
@property(nonatomic) int *counters; // @synthesize counters=_counters;
@property(retain, nonatomic) NSMutableString *decodeRowResult; // @synthesize decodeRowResult=_decodeRowResult;
- (void).cxx_destruct;
- (int)toNarrowWidePattern:(int)arg1;
- (int)findStartPattern;
- (void)counterAppend:(int)arg1;
- (_Bool)setCountersWithRow:(id)arg1;
- (_Bool)validatePattern:(int)arg1;
- (id)decodeRow:(int)arg1 row:(id)arg2 hints:(id)arg3 error:(id *)arg4;
- (void)dealloc;
- (id)init;

@end

