//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXDataCharacter : NSObject
{
    int _value;	// 8 = 0x8
    int _checksumPortion;	// 12 = 0xc
}

@property(readonly, nonatomic) int checksumPortion; // @synthesize checksumPortion=_checksumPortion;
@property(readonly, nonatomic) int value; // @synthesize value=_value;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)initWithValue:(int)arg1 checksumPortion:(int)arg2;

@end

