//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZXUPCEANReader.h"

@interface ZXEAN13Reader : ZXUPCEANReader
{
    int *_decodeMiddleCounters;	// 8 = 0x8
}

@property(nonatomic) int *decodeMiddleCounters; // @synthesize decodeMiddleCounters=_decodeMiddleCounters;
- (_Bool)determineFirstDigit:(id)arg1 lgPatternFound:(int)arg2;
- (int)barcodeFormat;
- (int)decodeMiddle:(id)arg1 startRange:(struct _NSRange)arg2 result:(id)arg3 error:(id *)arg4;
- (void)dealloc;
- (id)init;

@end

