//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface ZXEANManufacturerOrgSupport : NSObject
{
    NSMutableArray *_countryIdentifiers;	// 8 = 0x8
    NSMutableArray *_ranges;	// 16 = 0x10
}

@property(retain, nonatomic) NSMutableArray *ranges; // @synthesize ranges=_ranges;
@property(retain, nonatomic) NSMutableArray *countryIdentifiers; // @synthesize countryIdentifiers=_countryIdentifiers;
- (void).cxx_destruct;
- (void)initIfNeeded;
- (void)add:(id)arg1 identifier:(id)arg2;
- (id)lookupCountryIdentifier:(id)arg1;
- (id)init;

@end

