//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZXECI : NSObject
{
    int _value;
}

+ (id)eciByValue:(int)arg1;
@property(readonly, nonatomic) int value; // @synthesize value=_value;
- (id)initWithValue:(int)arg1;

@end

