//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, ZXDimension, ZXDimensions, ZXErrorCorrectionLevel, ZXSymbolShapeHint;

@interface ZXEncodeHints : NSObject
{
    _Bool _pdf417Compact;
    int _pdf417Compaction;
    unsigned long long _encoding;
    ZXSymbolShapeHint *_dataMatrixShape;
    ZXDimension *_minSize;
    ZXDimension *_maxSize;
    ZXErrorCorrectionLevel *_errorCorrectionLevel;
    NSNumber *_errorCorrectionPercent;
    NSNumber *_margin;
    ZXDimensions *_pdf417Dimensions;
}

+ (id)hints;
@property(retain, nonatomic) ZXDimensions *pdf417Dimensions; // @synthesize pdf417Dimensions=_pdf417Dimensions;
@property(nonatomic) int pdf417Compaction; // @synthesize pdf417Compaction=_pdf417Compaction;
@property(nonatomic) _Bool pdf417Compact; // @synthesize pdf417Compact=_pdf417Compact;
@property(retain, nonatomic) NSNumber *margin; // @synthesize margin=_margin;
@property(retain, nonatomic) NSNumber *errorCorrectionPercent; // @synthesize errorCorrectionPercent=_errorCorrectionPercent;
@property(retain, nonatomic) ZXErrorCorrectionLevel *errorCorrectionLevel; // @synthesize errorCorrectionLevel=_errorCorrectionLevel;
@property(retain, nonatomic) ZXDimension *maxSize; // @synthesize maxSize=_maxSize;
@property(retain, nonatomic) ZXDimension *minSize; // @synthesize minSize=_minSize;
@property(retain, nonatomic) ZXSymbolShapeHint *dataMatrixShape; // @synthesize dataMatrixShape=_dataMatrixShape;
@property(nonatomic) unsigned long long encoding; // @synthesize encoding=_encoding;
- (void).cxx_destruct;

@end

