//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZXImage : NSObject
{
    struct CGImage *_cgimage;
}

+ (id)imageWithMatrix:(id)arg1;
@property(nonatomic) struct CGImage *cgimage; // @synthesize cgimage=_cgimage;
- (void)dealloc;
- (unsigned long long)height;
- (unsigned long long)width;
- (id)initWithURL:(id)arg1;
- (id)initWithCGImageRef:(struct CGImage *)arg1;

@end

