//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXLuminanceSource : NSObject
{
    _Bool _cropSupported;	// 8 = 0x8
    _Bool _rotateSupported;	// 9 = 0x9
    int _width;	// 12 = 0xc
    int _height;	// 16 = 0x10
}

@property(readonly, nonatomic) _Bool rotateSupported; // @synthesize rotateSupported=_rotateSupported;
@property(readonly, nonatomic) _Bool cropSupported; // @synthesize cropSupported=_cropSupported;
@property(readonly, nonatomic) int height; // @synthesize height=_height;
@property(readonly, nonatomic) int width; // @synthesize width=_width;
- (id)description;
- (id)rotateCounterClockwise45;
- (id)rotateCounterClockwise;
- (id)invert;
- (id)crop:(int)arg1 top:(int)arg2 width:(int)arg3 height:(int)arg4;
- (char *)matrix;
- (char *)row:(int)arg1;
- (id)initWithWidth:(int)arg1 height:(int)arg2;

@end

