//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZXMaxiCodeDecodedBitStreamParser : NSObject
{
}

+ (id)message:(char *)arg1 length:(unsigned int)arg2 start:(int)arg3 len:(int)arg4;
+ (id)postCode3:(char *)arg1 length:(unsigned int)arg2;
+ (int)postCode2:(char *)arg1 length:(unsigned int)arg2;
+ (int)postCode2Length:(char *)arg1 length:(unsigned int)arg2;
+ (int)serviceClass:(char *)arg1 length:(unsigned int)arg2;
+ (int)country:(char *)arg1 length:(unsigned int)arg2;
+ (int)integer:(char *)arg1 length:(unsigned int)arg2 x:(char *)arg3 xLength:(unsigned int)arg4;
+ (int)bit:(int)arg1 bytes:(char *)arg2 length:(unsigned int)arg3;
+ (id)decode:(char *)arg1 length:(unsigned int)arg2 mode:(int)arg3;

@end

