//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXModulusGF;

@interface ZXModulusPoly : NSObject
{
    int _coefficientsLen;	// 8 = 0x8
    int *_coefficients;	// 16 = 0x10
    ZXModulusGF *_field;	// 24 = 0x18
}

@property(nonatomic) __weak ZXModulusGF *field; // @synthesize field=_field;
@property(nonatomic) int coefficientsLen; // @synthesize coefficientsLen=_coefficientsLen;
@property(nonatomic) int *coefficients; // @synthesize coefficients=_coefficients;
- (void).cxx_destruct;
- (id)description;
- (id)divide:(id)arg1;
- (id)multiplyByMonomial:(int)arg1 coefficient:(int)arg2;
- (id)multiplyScalar:(int)arg1;
- (id)negative;
- (id)multiply:(id)arg1;
- (id)subtract:(id)arg1;
- (id)add:(id)arg1;
- (int)evaluateAt:(int)arg1;
- (int)coefficient:(int)arg1;
- (_Bool)zero;
- (int)degree;
- (void)dealloc;
- (id)initWithField:(id)arg1 coefficients:(int *)arg2 coefficientsLen:(int)arg3;

@end

