//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ZXWriter.h"

@class NSString;

@interface ZXPDF417Writer : NSObject <ZXWriter>
{
}

- (char **)rotateArray:(char **)arg1 height:(int)arg2 width:(int)arg3;
- (id)bitMatrixFrombitArray:(char **)arg1 height:(int)arg2 width:(int)arg3;
- (id)bitMatrixFromEncoder:(id)arg1 contents:(id)arg2 width:(int)arg3 height:(int)arg4 error:(id *)arg5;
- (id)encode:(id)arg1 format:(int)arg2 width:(int)arg3 height:(int)arg4 error:(id *)arg5;
- (id)encode:(id)arg1 format:(int)arg2 width:(int)arg3 height:(int)arg4 hints:(id)arg5 error:(id *)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

