//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXPDF417Common : NSObject
{
}

+ (int)findCodewordIndex:(long long)arg1;
+ (int)codeword:(long long)arg1;
+ (int)bitCountSum:(id)arg1;

@end

