//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXPDF417Codeword : NSObject
{
    int _startX;	// 8 = 0x8
    int _endX;	// 12 = 0xc
    int _bucket;	// 16 = 0x10
    int _value;	// 20 = 0x14
    int _rowNumber;	// 24 = 0x18
}

@property(nonatomic) int rowNumber; // @synthesize rowNumber=_rowNumber;
@property(readonly, nonatomic) int value; // @synthesize value=_value;
@property(readonly, nonatomic) int bucket; // @synthesize bucket=_bucket;
@property(readonly, nonatomic) int endX; // @synthesize endX=_endX;
@property(readonly, nonatomic) int startX; // @synthesize startX=_startX;
- (id)description;
- (int)width;
- (void)setRowNumberAsRowIndicatorColumn;
- (_Bool)isValidRowNumber:(int)arg1;
- (_Bool)hasValidRowNumber;
- (id)initWithStartX:(int)arg1 endX:(int)arg2 bucket:(int)arg3 value:(int)arg4;

@end

