//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface ZXPDF417BarcodeValue : NSObject
{
    NSMutableDictionary *_values;	// 8 = 0x8
}

@property(retain, nonatomic) NSMutableDictionary *values; // @synthesize values=_values;
- (void).cxx_destruct;
- (id)confidence:(int)arg1;
- (id)value;
- (void)setValue:(int)arg1;
- (id)init;

@end

