//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ZXLuminanceSource.h"

@interface ZXPlanarYUVLuminanceSource : ZXLuminanceSource
{
    int _yuvDataLen;
    int _dataWidth;
    int _dataHeight;
    int _left;
    int _top;
    char *_yuvData;
}

@property(nonatomic) int top; // @synthesize top=_top;
@property(nonatomic) int left; // @synthesize left=_left;
@property(nonatomic) int dataHeight; // @synthesize dataHeight=_dataHeight;
@property(nonatomic) int dataWidth; // @synthesize dataWidth=_dataWidth;
@property(nonatomic) int yuvDataLen; // @synthesize yuvDataLen=_yuvDataLen;
@property(nonatomic) char *yuvData; // @synthesize yuvData=_yuvData;
- (void)reverseHorizontal:(int)arg1 height:(int)arg2;
@property(readonly, nonatomic) int thumbnailHeight;
@property(readonly, nonatomic) int thumbnailWidth;
- (int *)renderThumbnail;
- (id)crop:(int)arg1 top:(int)arg2 width:(int)arg3 height:(int)arg4;
- (_Bool)cropSupported;
- (char *)matrix;
- (char *)row:(int)arg1;
- (void)dealloc;
- (id)initWithYuvData:(char *)arg1 yuvDataLen:(int)arg2 dataWidth:(int)arg3 dataHeight:(int)arg4 left:(int)arg5 top:(int)arg6 width:(int)arg7 height:(int)arg8 reverseHorizontal:(_Bool)arg9;

@end

