//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ZXByteMatrix, ZXErrorCorrectionLevel, ZXMode, ZXQRCodeVersion;

@interface ZXQRCode : NSObject
{
    int _maskPattern;
    ZXMode *_mode;
    ZXErrorCorrectionLevel *_ecLevel;
    ZXQRCodeVersion *_version;
    ZXByteMatrix *_matrix;
}

+ (_Bool)isValidMaskPattern:(int)arg1;
@property(retain, nonatomic) ZXByteMatrix *matrix; // @synthesize matrix=_matrix;
@property(nonatomic) int maskPattern; // @synthesize maskPattern=_maskPattern;
@property(retain, nonatomic) ZXQRCodeVersion *version; // @synthesize version=_version;
@property(retain, nonatomic) ZXErrorCorrectionLevel *ecLevel; // @synthesize ecLevel=_ecLevel;
@property(retain, nonatomic) ZXMode *mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

