//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ZXUPCEANExtension5Support : NSObject
{
}

- (id)parseExtension5String:(id)arg1;
- (id)parseExtensionString:(id)arg1;
- (int)determineCheckDigit:(int)arg1;
- (int)extensionChecksum:(id)arg1;
- (int)decodeMiddle:(id)arg1 startRange:(struct _NSRange)arg2 result:(id)arg3 error:(id *)arg4;
- (id)decodeRow:(int)arg1 row:(id)arg2 extensionStartRange:(struct _NSRange)arg3 error:(id *)arg4;

@end

