//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZXC40Encoder.h"

@interface ZXX12Encoder : ZXC40Encoder
{
}

- (void)handleEOD:(id)arg1 buffer:(id)arg2;
- (int)encodeChar:(unsigned short)arg1 buffer:(id)arg2;
- (void)encode:(id)arg1;
- (int)encodingMode;

@end

