//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKSessionDelegate.h"

@class GKSession, NSMutableArray, NSString;

@interface GKTaikoBattle : NSObject <GKSessionDelegate>
{
    GKSession *m_pGKSession;
    id <GKTaikoBattleDelegate> m_pDelegate;
    NSMutableArray *m_pArrListServer;
    NSMutableArray *m_arpArrRecieveData[4];
    NSMutableArray *m_arpArrMusicIDList[4];
    NSString *m_arszPeerID[4];
    NSString *m_arszUserName[4];
    NSString *m_szMyName;
    unsigned long m_arnRecieveCount[4];
    unsigned long m_arnScore[4];
    unsigned long m_arnCombo[4];
    unsigned long m_arnRank[4];
    unsigned long m_arnWinCount[4];
    unsigned long m_nPlayerNum;
    unsigned long m_nOriginalPlayerNum;
    unsigned long m_nSecurePlayerNum;
    unsigned long m_nMyArr;
    unsigned long m_nSendCount;
    unsigned long m_nBattleType;
    unsigned long m_nLevel;
    unsigned long m_nMyBeforeScore;
    unsigned long m_nMyBeforeCombo;
    unsigned long m_nScoreSendCount;
    _Bool m_arbClientsReady[4];
    _Bool m_arbRouletteReady[4];
    _Bool m_arbRouletteActivated[4];
    _Bool m_arbClientsOjamaMotion[4];
    _Bool m_arbNewDevice[4];
    _Bool m_bServer;
    _Bool m_bEndAdva;
    _Bool m_bUpdateServerList;
    _Bool m_bSafeDisconnect;
    _Bool m_bReSetting;
    _Bool m_bConnected;
    _Bool m_bStarted;
    _Bool m_bEnableItem;
    _Bool m_bEnableCom;
    _Bool m_bMyDeviceIsNew;
    _Bool m_bOjamaCantUse;
    _Bool m_bDisconnectAllPeers;
    unsigned long m_nVSGameVersion[4];
    unsigned int m_nGameOptions;
    BOOL m_bDiscontinued;
    unsigned long m_nPlayingVersion;
    BOOL m_bServerResultReady;
}

@property(readonly) BOOL serverResultReady; // @synthesize serverResultReady=m_bServerResultReady;
@property(readonly) BOOL discontinued; // @synthesize discontinued=m_bDiscontinued;
@property(readonly) unsigned int gameOptions; // @synthesize gameOptions=m_nGameOptions;
@property(readonly) _Bool disconnectStac; // @synthesize disconnectStac=m_bDisconnectAllPeers;
@property(readonly) _Bool enableCom; // @synthesize enableCom=m_bEnableCom;
@property(readonly) _Bool enableItem; // @synthesize enableItem=m_bEnableItem;
@property(readonly) _Bool connected; // @synthesize connected=m_bConnected;
@property(readonly) _Bool started; // @synthesize started=m_bStarted;
@property(readonly) _Bool advaEnd; // @synthesize advaEnd=m_bEndAdva;
@property(readonly) _Bool updateServerList; // @synthesize updateServerList=m_bUpdateServerList;
@property(readonly) _Bool server; // @synthesize server=m_bServer;
@property(readonly) unsigned long battleType; // @synthesize battleType=m_nBattleType;
@property(readonly) unsigned long myArr; // @synthesize myArr=m_nMyArr;
@property(readonly) unsigned long playerNum; // @synthesize playerNum=m_nPlayerNum;
@property(readonly) unsigned long originalPlayerNum; // @synthesize originalPlayerNum=m_nOriginalPlayerNum;
- (void)test;
- (int)getRecordFourthCountWithLevel:(unsigned long)arg1;
- (int)getRecordThirdCountWithLevel:(unsigned long)arg1;
- (int)getRecordSecondCountWithLevel:(unsigned long)arg1;
- (int)getRecordFirstCountWithLevel:(unsigned long)arg1;
- (int)getRecordDrawCountWithLevel:(unsigned long)arg1;
- (int)getRecordLoseCountWithLevel:(unsigned long)arg1;
- (int)getRecordWinCountWithLevel:(unsigned long)arg1;
- (void)checkRecordMonth;
- (void)endBattleFromServer;
- (void)regameStartFromServer;
- (void)changeSettingFromServer;
- (int)isWinOrLose;
- (void)readyResultStartFromServer;
- (void)readyResultStartFromClient;
- (void)updateResult;
- (void)readyGameEndFromServer;
- (void)readyGameEndFromClient;
- (void)submitLastScoresFromServer;
- (void)endOjamaMotionFromComWithArr:(unsigned long)arg1;
- (void)endOjamaMotion;
- (_Bool)checkOjamaUseFromComWithArr:(unsigned long)arg1;
- (void)checkOjamaUse;
- (void)discontinueGame;
- (void)notifyImperfect;
- (void)update;
- (void)submitOjamaItemFromCom:(unsigned long)arg1 Arr:(unsigned long)arg2;
- (void)submitOjamaItem:(unsigned long)arg1;
- (void)itemSubmitFromServer;
- (void)itemRouletteStartWithArr:(unsigned long)arg1 flag:(BOOL)arg2;
- (void)itemRouletteStartFromClient:(BOOL)arg1;
- (void)setComScore:(unsigned long)arg1 Combo:(unsigned long)arg2 Arr:(unsigned long)arg3;
- (void)setMyScore:(unsigned long)arg1 Combo:(unsigned long)arg2;
- (void)readyGameStartFromServer:(unsigned int *)arg1;
- (void)clearAllGameScore;
- (void)delayCheckFromClient;
- (void)delayCheckFromServer;
- (void)submitBattleSettingFromServerWithMusicID:(id)arg1 Level:(unsigned long)arg2 BattleType:(unsigned long)arg3 isItem:(_Bool)arg4 gameOptions:(unsigned int)arg5;
- (void)nowBattleSettingFromServerWithMusicID:(id)arg1 Level:(unsigned long)arg2 BattleType:(unsigned long)arg3 isItem:(_Bool)arg4 gameOptions:(unsigned int)arg5;
- (void)endBattleFromServerInRoom;
- (_Bool)checkClientsMusicID:(id)arg1;
- (void)sendMusicIDList;
- (void)addMusicID:(id)arg1;
- (void)sendVSGameVersion;
- (void)endAdvaFromServer;
- (_Bool)checkNextSettingFromServer;
- (void)setEnableCom:(_Bool)arg1;
- (void)submitConnectServerWithPeerID:(id)arg1;
- (id)getNameFromPeerID:(id)arg1;
- (id)getServerPeerIDList;
- (_Bool)startConnectIsServer:(_Bool)arg1;
- (_Bool)isComWithArr:(unsigned long)arg1;
- (_Bool)isReSetting;
- (unsigned long)getWinCountWithArr:(unsigned long)arg1;
- (unsigned long)getRankWithArr:(unsigned long)arg1;
- (unsigned long)getComboWithArr:(unsigned long)arg1;
- (unsigned long)getScoreWithArr:(unsigned long)arg1;
- (id)getUserNameWithArr:(unsigned long)arg1;
- (void)setMyDeviceIsNew:(_Bool)arg1;
- (void)setMyName:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)disconectProcessFromClient:(_Bool)arg1;
- (void)backClientInRoom;
- (void)allClear:(_Bool)arg1;
- (void)dealloc;
- (id)init;
- (void)session:(id)arg1 peer:(id)arg2 didChangeState:(int)arg3;
- (void)session:(id)arg1 didReceiveConnectionRequestFromPeer:(id)arg2;
- (void)session:(id)arg1 connectionWithPeerFailed:(id)arg2 withError:(id)arg3;
- (void)receiveData:(id)arg1 fromPeer:(id)arg2 inSession:(id)arg3 context:(void *)arg4;
- (void)addRecordFourthCountWithLevel:(unsigned long)arg1;
- (void)addRecordThirdCountWithLevel:(unsigned long)arg1;
- (void)addRecordSecondCountWithLevel:(unsigned long)arg1;
- (void)addRecordFirstCountWithLevel:(unsigned long)arg1;
- (void)addRecordDrawCountWithLevel:(unsigned long)arg1;
- (void)addRecordLoseCountWithLevel:(unsigned long)arg1;
- (void)addRecordWinCountWithLevel:(unsigned long)arg1;
- (void)notifyRouletteReady;
- (void)mathPlayerRank;
- (void)checkServerListIsDead;
- (void)clearParam;
@property(readonly) unsigned long version;

@end

