//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneManagerVDrums.h"

@class ISceneLinkage, ISceneManagerLinkageAlertViewDelegate, NSDictionary, NSMutableArray, NSString, TaikoCoverView, UIActivityIndicatorView;

@interface ISceneManagerLinkage : ISceneManagerVDrums
{
    NSString *linkageDirectory_;
    ISceneLinkage *sceneLinkage_;
    TaikoCoverView *coverView_;
    BOOL covered_;
    BOOL coverTouched_;
    struct _TOUCH alternativeTouches_[10];
    NSDictionary *preservedInfo_;
    int queryCount_;
    NSMutableArray *processingLinkageProducts_;
    NSMutableArray *completedLinkageProducts_;
    BOOL waitingForAlertview_;
    NSString *linkageQuery_;
    UIActivityIndicatorView *activityIndicatorView_;
    int musicIndex_;
    ISceneManagerLinkageAlertViewDelegate *alertViewDelegate_;
    BOOL _canOpenLinkageDialog;
    NSString *_addedLinkageMusicID;
    CDUnknownBlockType _linkageInfoUpdatedCallback;
}

@property(copy, nonatomic) CDUnknownBlockType linkageInfoUpdatedCallback; // @synthesize linkageInfoUpdatedCallback=_linkageInfoUpdatedCallback;
@property(copy, nonatomic) NSString *addedLinkageMusicID; // @synthesize addedLinkageMusicID=_addedLinkageMusicID;
@property(nonatomic) BOOL canOpenLinkageDialog; // @synthesize canOpenLinkageDialog=_canOpenLinkageDialog;
- (id)horizontalTitleImageFilePathWithLinkage:(id)arg1 targetProductID:(id)arg2 atIndex:(int)arg3;
- (id)musicIDWithLinkage:(id)arg1 targetProductID:(id)arg2 atIndex:(int)arg3;
- (void)showActivityIndicator:(BOOL)arg1;
- (id)activityIndicatorView;
- (void)notifyLinkageInfoUpdatedWithLinkageProduct:(id)arg1;
- (void)clearAddedLinkageMusicID;
- (void)openLinkageAnotherURL;
- (void)openLinkageURL;
- (BOOL)canOpenLinkageURL;
- (void)tapLinkageButtonWithNumber:(int)arg1;
- (id)linkageButtonImageAndMaskImage:(id *)arg1;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (BOOL)finalizeProcessingLinkageWithDownload:(id)arg1 error:(int)arg2;
- (void)startCheckingLinkageButtonInfo;
- (void)updateLinkageInfo:(id)arg1 code:(id)arg2;
- (void)checkAndDownloadForLinkageProduct:(id)arg1 inDirectory:(id)arg2 fileName:(id)arg3 URLString:(id)arg4;
- (void)startCheckingServerRenewalInfo;
- (void)applicationDidEnterBackground;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)registerLinkageQuery:(id)arg1;
- (id)parseQueryString:(id)arg1;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)ISceneManagerLinkage_alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)processCompletedLinkage;
- (void)showAlertWithSubtitle:(id)arg1 message:(id)arg2 tag:(int)arg3;
- (BOOL)openDialogWithLinkageProduct:(id)arg1;
- (void)processLinkageQuery;
- (void)endQuery;
- (void)beginQuery;
- (void)renderLast;
- (BOOL)needsCover;
- (BOOL)isProcessing;
- (void)update;
- (struct _TOUCH *)allTouches;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 options:(id)arg2;
- (BOOL)isBusyWithLinkage;

@end

