//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "BGSNSInterfaceDelegate.h"

@interface ISceneNameEntry : ISceneBase <BGSNSInterfaceDelegate>
{
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BigCharFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_CharBoxFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_RemoveButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DecideButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;
    struct _AGOBJECT m_BackObject;
    struct _AGOBJECT m_TitleObject;
    struct _AGOBJECT m_BigCharObject[87];
    struct _AGOBJECT m_CharBoxObject[5];
    struct _AGOBJECT m_NameCharObject[5];
    struct _AGOBJECT m_RemoveButtonObject;
    struct _AGOBJECT m_DecideButtonObject;
    struct _AGOBJECT m_BackButtonObject;
    int m_CurrentChar;
    int m_NextScene;
    int m_FadeCounter;
}

- (int)stateWait;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)alertWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3;
- (int)stateRun;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

@end

