//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneManagerTaikoController.h"

#import "MidiInputDelegate.h"

@class MidiInput;

@interface ISceneManagerVDrums : ISceneManagerTaikoController <MidiInputDelegate>
{
    MidiInput *midiInput_;
    long currentMIDIUniqueID_;
    unsigned char vDrumsHitInputTypes_[128];
    unsigned char defaultHitInputTypes_[128];
    BOOL isAlreadyOpened_;
    int pressedNoteNumber_;
    BOOL shouldShowDisconnectionAlert_;
    BOOL needsIdleTimerResetting_;
    BOOL _vDrumsInputEnabled;
    BOOL _vDrumsNonSupportedNoteNumberAlertEnabled;
    double _vDrumsScoreDelayTime;
}

@property(nonatomic) double vDrumsScoreDelayTime; // @synthesize vDrumsScoreDelayTime=_vDrumsScoreDelayTime;
@property(nonatomic) BOOL vDrumsNonSupportedNoteNumberAlertEnabled; // @synthesize vDrumsNonSupportedNoteNumberAlertEnabled=_vDrumsNonSupportedNoteNumberAlertEnabled;
@property(readonly, nonatomic) BOOL vDrumsInputEnabled; // @synthesize vDrumsInputEnabled=_vDrumsInputEnabled;
@property(readonly, nonatomic) int pressedNoteNumber; // @synthesize pressedNoteNumber=pressedNoteNumber_;
- (unsigned char)defaultHitInputTypeAtIndex:(unsigned int)arg1;
- (unsigned char)vDrumsHitInputTypeAtIndex:(unsigned int)arg1;
- (void)midiInputSendMessage:(id)arg1;
- (void)noteOff:(int)arg1 offVelocity:(int)arg2;
- (void)noteOn:(int)arg1 onVelocity:(int)arg2;
- (void)midiInputError:(long)arg1;
- (void)removeSourceWithSourceInfo:(id)arg1;
- (BOOL)addSourceWithSourceInfo:(id)arg1;
- (long)selectSourceWithSourceInfoArray:(id)arg1;
- (unsigned int)taikoControllerInputReleased;
- (unsigned int)taikoControllerInputPressed;
- (unsigned int)taikoControllerInputRaw;
- (BOOL)checkNoteNumberSupport:(int)arg1;
- (void)verifyVDrums;
@property(readonly, nonatomic) int vDrumsMandatoryCodeInputted;
@property(readonly, nonatomic) BOOL vDrumsReady;
@property(readonly, nonatomic) BOOL vDrumsConnected;
- (BOOL)taikoControllerInputEnabled;
- (void)loadVDrumsDelayJSON;
- (void)update;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 options:(id)arg2;
- (void)loadVDrumsConfig;

@end

