//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "BGSNSInterfaceDelegate.h"

@class UIButton;

@interface ISceneTitle : ISceneBase <BGSNSInterfaceDelegate>
{
    struct _AASAMPLE m_TitleSample;
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTUREFRAMEGROUP m_TFGBack;
    struct _AGTEXTUREFRAMEGROUP m_TFGVersion;
    struct _AGTEXTUREFRAMEGROUP m_TFGStart;
    struct _AGTEXTURE m_TitleTexture;
    struct _AGOBJECT m_BackObject;
    struct _AGOBJECT m_VersionObject;
    struct _AGOBJECT m_ButtonObject;
    int m_State;
    int m_Counter;
    UIButton *bannerButton_;
}

- (void)SNSInterfaceNumber:(unsigned int)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)touchUpInsideOfBannerButton;
- (int)stateRun;
- (void)loadBanner;
- (void)render;
- (int)update;
- (void)updateInput;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

@end

