//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "BGSNSInterfaceDelegate.h"
#import "SceneDialogDelegate.h"
#import "TwitterApiDelegate.h"

@class BGSNSInterfaceError, GameOptionIcons, ISceneDialog, IScenePlayBonusDialog, NSURL, TwitterApiStatus;

@interface ISceneResult : ISceneBase <TwitterApiDelegate, BGSNSInterfaceDelegate, SceneDialogDelegate>
{
    struct _AASAMPLE m_NewRecordSample;
    struct _AASAMPLE m_FullComboSample;
    struct _AASAMPLE m_ScoreSample;
    struct _AASAMPLE m_ResultSample;
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BoardFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_CourseIconFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_ScoreNumFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_CommonNumFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_MeterFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_FireFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DonCommonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_DonCustomFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_EmblemFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_PersonalBestFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_FullComboFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_FlowersFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_CloudFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_WaterFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_RainFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_WormFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SongTitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_WindowFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_WindowContentsFrameGroup;
    struct _AGOBJECT m_BackObject;
    struct _AGOBJECT m_TextObject;
    struct _AGOBJECT m_BoardObject[3];
    struct _AGOBJECT m_CourseIconObject;
    struct _AGOBJECT m_ScoreNumObject[8];
    struct _AGOBJECT m_MaxComboNumObject[4];
    struct _AGOBJECT m_HitRateNumObject[3];
    struct _AGOBJECT m_MeterObject[5];
    struct _AGOBJECT m_EmblemObject;
    struct _AGOBJECT m_PersonalBestObject[3];
    struct _AGOBJECT m_FullComboObject;
    struct _AGOBJECT m_DonObject;
    struct _AGOBJECT m_FlowersObject;
    struct _AGOBJECT m_CloudObject;
    struct _AGOBJECT m_WaterObject;
    struct _AGOBJECT m_RainObject[24];
    struct _AGOBJECT m_WormObject;
    struct _AGOBJECT m_SongTitleObject;
    BOOL m_TwitterEnabled;
    BOOL m_UpdateTwitter;
    int m_NextScene;
    int m_Meter;
    int m_MeterMax;
    int m_MeterLimit;
    BOOL m_KanpekiFailed;
    int m_ScoreTextLength;
    int m_ScoreText[7];
    int m_MaxComboTextLength;
    int m_MaxComboText[4];
    int m_HitRateTextLength;
    int m_HitRateText[3];
    int m_MeterLength;
    int m_Counter;
    int m_EmblemAnimationCounter;
    float m_EmblemPosition;
    float m_EmblemSpeed;
    int m_PersonalBestAnimationCounter;
    int m_FullComboAnimationCounter;
    int m_FireAnimationCounter;
    int m_DonAnimationCounter;
    int m_DonAnimation;
    float m_DonPosition;
    float m_DonJumpHeight;
    int m_FlowersAnimationCounter;
    float m_FlowersPosition;
    float m_RainPosition;
    float m_RainSpace;
    int m_FailedAnimationCounter;
    int m_TextAnimationCounter;
    int m_SubmitSelect;
    BOOL m_ShowFire;
    BOOL m_ShowFlowers;
    BOOL m_ShowFailed;
    BOOL m_ShowSubmit;
    int m_URLRequestType;
    TwitterApiStatus *m_twitterApi;
    GameOptionIcons *m_GameOptionIcons;
    struct _AGOBJECT m_NumJudgeNumObject[3][4];
    int m_NumJudgeTextLength[3];
    int m_NumJudgeText[3][4];
    int m_JudgeIndex;
    int m_PauseState;
    NSURL *m_CollaboURL;
    struct _AGTEXTUREFRAMEGROUP m_SubmitDialogWindowFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SubmitDialogMessageFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SubmitDialogButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_SubmitDialogChoiceFrameGroup;
    ISceneDialog *m_SubmitDialog;
    struct _AGTEXTUREFRAMEGROUP m_BonusDialogWindowFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BonusDialogMessageFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BonusDialogButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BonusDialogChoiceFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BonusDialogDigitFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BonusDialogGetFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_BonusDialogPraiseFrameGroup;
    IScenePlayBonusDialog *m_BonusDialog;
    BOOL m_PlayNotified;
    id m_PlayNotificationObject;
    BGSNSInterfaceError *m_PlayNotificationError;
    BOOL m_AchievedGoal;
    BOOL m_IsGotoRanking;
    struct _AGTEXTUREFRAMEGROUP m_ExerciseDialogMessageFrameGroup;
    ISceneDialog *m_ExerciseDialog;
}

- (void)sceneDialog:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (int)stateExerciseDialog;
- (void)changeStateExercise;
- (void)updateCollaboBonus;
- (int)stateCollaboIdle;
- (int)stateTwitterIdle;
- (int)stateRankingIdle;
- (int)stateBonusDialog;
- (int)stateWaitResponse;
- (int)stateIdle;
- (int)stateWaitUserInteraction;
- (void)changeStateFromIdle;
- (int)stateSubmit;
- (void)updateRanking;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)twitterApiFailed:(int)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)twitterApiSuccess;
- (void)updateTwitter;
- (int)stateFadeOut;
- (int)stateFullCombo;
- (int)stateCountMeter;
- (int)stateCountNumJudge;
- (int)stateCountHitRate;
- (int)stateCountMaxCombo;
- (int)stateCountScore;
- (int)stateFadeIn;
- (void)updateAnimation;
- (void)render;
- (int)update;
- (void)updateInput;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

@end

