//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneManager.h"

#import "UIKeyInput.h"
#import "UITextInputTraits.h"

@class ISceneTaikoController, ISceneVDrumsDialog, NSTimer, TaikoAction, TaikoCoverView, TaikoSceneNode;

@interface ISceneManagerTaikoController : ISceneManager <UIKeyInput, UITextInputTraits>
{
    CDStruct_42c778cc workingTaikoControllerInput_;
    CDStruct_42c778cc fixedTaikoControllerInput_;
    unsigned int previousTaikoControllerInput_;
    unsigned int taikoControllerInputPreserveCounts_[4];
    BOOL taikoControllerInputted_;
    BOOL batteryAlertShown_;
    struct _AGTEXTURE texture_;
    struct _AGTEXTUREFRAMEGROUP batteryTextureFrameGroup_;
    TaikoSceneNode *batteryNode_;
    TaikoAction *lowBatteryAnimation_;
    struct _AGTEXTUREFRAMEGROUP cautionTextureFrameGroup_;
    TaikoSceneNode *cautionNode_;
    TaikoAction *cautionAnimation_;
    TaikoCoverView *coverView_;
    BOOL covered_;
    BOOL coverTouched_;
    struct _TOUCH alternativeTouches_[10];
    ISceneTaikoController *sceneTaikoController_;
    ISceneVDrumsDialog *sceneVDrumsDialog_;
    unsigned int numberOfcharacters_;
    BOOL mayBecomeFirstResponder_;
    BOOL canBecomeFirstResponder_;
    BOOL taikoControllerReady_;
    BOOL shouldShowDisconnectionAlert_;
    BOOL firstResponder_;
    NSTimer *timer_;
    BOOL _taikoControllerConnected;
    BOOL needsTryToEnableTaikoController_;
    BOOL taikoControllerPollingStarted_;
    BOOL taikoControllerPollingEnabled_;
    BOOL keyWindow_;
    BOOL taikoControllerInputKeeping_;
    BOOL taikoControllerInputCleared_;
    BOOL _taikoControllerPollingStopped;
    BOOL _canOpenTaikoControllerConnectionDialog;
    BOOL _canConnectTaikoController;
    BOOL _taikoControllerInputEnabled;
    BOOL _taikoControllerCautionShowing;
    double _taikoControllerScoreDelayTime;
}

@property(readonly, nonatomic) BOOL taikoControllerCautionShowing; // @synthesize taikoControllerCautionShowing=_taikoControllerCautionShowing;
@property(readonly, nonatomic) BOOL taikoControllerInputEnabled; // @synthesize taikoControllerInputEnabled=_taikoControllerInputEnabled;
@property(readonly, nonatomic) BOOL taikoControllerConnected; // @synthesize taikoControllerConnected=_taikoControllerConnected;
@property(nonatomic) BOOL canConnectTaikoController; // @synthesize canConnectTaikoController=_canConnectTaikoController;
@property(nonatomic) BOOL canOpenTaikoControllerConnectionDialog; // @synthesize canOpenTaikoControllerConnectionDialog=_canOpenTaikoControllerConnectionDialog;
@property(nonatomic) BOOL taikoControllerPollingStopped; // @synthesize taikoControllerPollingStopped=_taikoControllerPollingStopped;
@property(nonatomic) double taikoControllerScoreDelayTime; // @synthesize taikoControllerScoreDelayTime=_taikoControllerScoreDelayTime;
- (BOOL)canUseTaikoController;
- (void)loadTaikoControllerDelayJSON;
- (id)mostAppropriateVersion:(id)arg1 inVersions:(id)arg2;
- (void)stopTaikoControllerPolling;
- (void)startTaikoControllerPolling;
- (void)pollTaikoController;
- (void)setNeedsTryToEnableTaikoController;
- (void)tryToEnableTaikoController;
- (void)hideKeyboard;
@property(nonatomic) BOOL taikoControllerPollingEnabled;
@property(readonly, nonatomic) BOOL mandatoryCodeInputted;
- (unsigned int)fixedTaikoControllerInput_released;
- (unsigned int)fixedTaikoControllerInput_pressed;
- (unsigned int)fixedTaikoControllerInput_raw;
@property(readonly, nonatomic) unsigned int taikoControllerInputReleased;
@property(readonly, nonatomic) unsigned int taikoControllerInputPressed;
@property(readonly, nonatomic) unsigned int taikoControllerInputRaw;
- (void)flipControllerInputs;
@property(nonatomic) int spellCheckingType;
@property(nonatomic) int autocorrectionType;
@property(nonatomic) int autocapitalizationType;
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
- (void)deleteBackward;
- (void)insertText:(id)arg1;
- (BOOL)hasText;
- (BOOL)canBecomeFirstResponder;
- (void)applicationWillResignActive;
- (void)evaluateInput:(unsigned short)arg1;
- (void)resetTaikoController;
- (void)keepTaikoControllerInput;
- (void)verifyTaikoController;
- (void)disableTaikoController;
- (BOOL)enableTaikoController;
- (void)showNonSupportedNoteNumberAlert;
- (void)hideTaikoControllerCaution;
- (void)showTaikoControllerCaution;
- (void)render;
- (void)renderLast;
- (void)openTaikoControllerGuide;
- (void)update;
- (void)updateWithoutTaikoController;
- (void)nextSceneDidLoadWithTaikoController;
- (void)clearTaikoControllerInput;
- (void)waitUntilInputIdle;
- (struct _TOUCH *)allTouches;
- (void)disconnectTaikoController;
- (void)windowDidResignKey;
- (void)windowDidBecomeKey;
- (BOOL)attemptToBecomeFirstResponder;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 options:(id)arg2;

// Remaining properties
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(nonatomic) int keyboardAppearance;
@property(nonatomic) int keyboardType;
@property(nonatomic) int returnKeyType;

@end

