//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString, SKProduct, UIImage;

@interface IStorePackage : NSObject
{
    NSString *m_ProductIdentifier;
    NSString *m_Title;
    NSString *m_Description;
    NSString *m_Price;
    NSMutableArray *m_SongArray;
    BOOL m_BuyFlag;
    NSString *m_IconURL;
    BOOL m_Downloaded;
    BOOL m_Restored;
    int m_BonusDoncoin;
    NSString *m_SampleAllowedFlags;
    BOOL _descriptionImageDownloadFailed;
    NSString *_descriptionURL;
    UIImage *_descriptionImage;
    SKProduct *_skProduct;
}

@property(retain, nonatomic) SKProduct *skProduct; // @synthesize skProduct=_skProduct;
@property(nonatomic) BOOL descriptionImageDownloadFailed; // @synthesize descriptionImageDownloadFailed=_descriptionImageDownloadFailed;
@property(retain, nonatomic) UIImage *descriptionImage; // @synthesize descriptionImage=_descriptionImage;
@property(copy, nonatomic) NSString *descriptionURL; // @synthesize descriptionURL=_descriptionURL;
@property(copy, nonatomic) NSString *sampleAllowedFlags; // @synthesize sampleAllowedFlags=m_SampleAllowedFlags;
@property(nonatomic) int bonusDoncoin; // @synthesize bonusDoncoin=m_BonusDoncoin;
@property(nonatomic) BOOL restored; // @synthesize restored=m_Restored;
@property(nonatomic) BOOL downloaded; // @synthesize downloaded=m_Downloaded;
@property(copy, nonatomic) NSString *iconURL; // @synthesize iconURL=m_IconURL;
@property(nonatomic) BOOL buyFlag; // @synthesize buyFlag=m_BuyFlag;
@property(readonly, nonatomic) NSArray *songArray; // @synthesize songArray=m_SongArray;
@property(readonly, nonatomic) NSString *price; // @synthesize price=m_Price;
@property(copy, nonatomic) NSString *description; // @synthesize description=m_Description;
@property(readonly, nonatomic) NSString *title; // @synthesize title=m_Title;
@property(readonly, nonatomic) NSString *productIdentifier; // @synthesize productIdentifier=m_ProductIdentifier;
- (void)setTitle:(id)arg1 price:(id)arg2;
- (unsigned int)songCount;
- (id)songList;
- (void)addSong:(id)arg1;
- (void)dealloc;
- (id)initWithProductIdentifier:(id)arg1 description:(id)arg2;

@end

