//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MidiInputSourceInfo, NSArray, NSString;

@protocol MidiInputDelegate <NSObject>
- (void)midiInputSendMessage:(NSString *)arg1;
- (void)noteOff:(int)arg1 offVelocity:(int)arg2;
- (void)noteOn:(int)arg1 onVelocity:(int)arg2;
- (void)midiInputError:(long)arg1;
- (void)removeSourceWithSourceInfo:(MidiInputSourceInfo *)arg1;
- (BOOL)addSourceWithSourceInfo:(MidiInputSourceInfo *)arg1;
- (long)selectSourceWithSourceInfoArray:(NSArray *)arg1;
@end

