//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BGSNSInterfaceDelegate.h"

@class BGSNSInterfaceError;

@interface TaikoUpdateChecker : NSObject <BGSNSInterfaceDelegate>
{
    BGSNSInterfaceError *error_;
    id <TaikoUpdateCheckerDelegate> delegate_;
    BOOL _checking;
    BOOL _finished;
    int _result;
}

@property(readonly, nonatomic) int result; // @synthesize result=_result;
@property(readonly, nonatomic, getter=isFinished) BOOL finished; // @synthesize finished=_finished;
@property(readonly, nonatomic, getter=isChecking) BOOL checking; // @synthesize checking=_checking;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)openAppStore;
- (void)showForcedUpdateAlert;
- (void)showRecommendedUpdateAlert;
- (BOOL)processResultWithDelegate:(id)arg1;
- (void)start;
- (void)dealloc;

@end

