//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TaikoPrize.h"

@class NSString, TaikoNumberLabel, TaikoSceneNode;

@interface TaikoLoginBonusItem : TaikoPrize
{
    struct _AGTEXTUREFRAMEGROUP *itemNameFrameGroup_;
    TaikoSceneNode *plateLeftNode_;
    TaikoSceneNode *plateMiddleNode_;
    TaikoSceneNode *plateRightNode_;
    TaikoSceneNode *nameNode_;
    TaikoNumberLabel *pointNumberNode_;
    TaikoSceneNode *pointTextNode_;
    unsigned int type_;
    BOOL _startupBonus;
    int _point;
    int _totalLogin;
    NSString *_nameImageURLString;
    float _x;
    float _y;
    float _width;
}

@property(readonly, nonatomic) float width; // @synthesize width=_width;
@property(readonly, nonatomic) float y; // @synthesize y=_y;
@property(readonly, nonatomic) float x; // @synthesize x=_x;
@property(copy, nonatomic) NSString *nameImageURLString; // @synthesize nameImageURLString=_nameImageURLString;
@property(nonatomic) int totalLogin; // @synthesize totalLogin=_totalLogin;
@property(nonatomic) BOOL startupBonus; // @synthesize startupBonus=_startupBonus;
@property(nonatomic) int point; // @synthesize point=_point;
- (unsigned int)type;
- (void)setType:(unsigned int)arg1;
- (id)imageURLStringWithType:(unsigned int)arg1;
- (void)addNodesTo:(id)arg1;
- (BOOL)setupWithTextureCache:(id)arg1 centerX:(float)arg2 y:(float)arg3 additionalWidth:(float)arg4;
- (void)setupPointWithCenterX:(float)arg1 y:(float)arg2 additionalWidth:(float)arg3;
- (void)setupNameWithTextureFrameIndex:(int)arg1 centerX:(float)arg2 y:(float)arg3 additionalWidth:(float)arg4;
- (void)setupPlateWithX:(float)arg1 y:(float)arg2 width:(float)arg3;
- (float)plateWidth:(float)arg1;
- (id)initWithIdentifier:(id)arg1 digitFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg2 itemPlateFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3 itemNameFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg4;
- (void)dealloc;

@end

