//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TaikoProgressIndicator : NSObject
{
    struct _AGOBJECT plateObject_;
    struct _AGOBJECT digitObjects_[3];
    int _percent;
    unsigned int _backgroundColor;
}

@property(readonly, nonatomic) unsigned int backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) int percent; // @synthesize percent=_percent;
- (void)render;
- (void)setAlpha:(float)arg1;
- (id)initWithTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1;

@end

