//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class ISceneManager;

@interface TaikoViewController : UIViewController
{
    int currentInterfaceOrientation_;
    ISceneManager *_sceneManager;
}

@property(nonatomic) ISceneManager *sceneManager; // @synthesize sceneManager=_sceneManager;
@property(readonly, nonatomic) int orientation; // @synthesize orientation=currentInterfaceOrientation_;
- (int)preferredInterfaceOrientationForPresentation;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (id)init;
- (void)orientationChanged:(id)arg1;

@end

