//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

@interface ISongInfo : NSObject
{
    unsigned int m_Version; // 8 = 0x8
    NSString *m_PackageID;  // 16 = 0x10
    NSString *m_Path;   // 24 = 0x18
    NSString *m_ImagePackPath;  // 32 = 0x20
    NSString *m_Identifier; // 40 = 0x28
    NSString *m_Title;  // 48 = 0x30
    unsigned int m_Genre;   // 56 = 0x38
    double m_PreviewStartTime;  // 64 = 0x40
    int m_CourseDifficulties[5];    // 72 = 0x48
    unsigned int m_MusicDataOffset; // 92 = 0x5c
    unsigned int m_MusicDataLength; // 96 = 0x60
    unsigned int m_ScoreDataOffset[5];  // 100 = 0x64
    unsigned int m_ScoreDataLength[5];  // 120 = 0x78
    unsigned int m_ImagePackDataOffset; // 140 = 0x8c
    unsigned int m_nSongPackSortNum;    // 144 = 0x90
    int m_AnimationType;    // 148 = 0x94
    int m_DancerCount[5];   // 152 = 0x98
    int m_ChibiCount[5];    // 172 = 0xac
    int m_BgCount[2];   // 192 = 0xc0
    unsigned int m_AnimationDataOffset; // 200 = 0xc8
    unsigned int m_AnimationDataLength; // 204 = 0xcc
    double m_ScoreDelayTime;    // 208 = 0xd0
    _Bool m_HasBranch[5];   // 216 = 0xd8
    unsigned int m_Length;  // 224 = 0xe0
    unsigned int m_CheckSum;    // 228 = 0xe4
    _Bool m_IsValid;    // 232 = 0xe8
    NSString *m_Pronunciation;  // 240 = 0xf0
    unsigned int m_Generation;  // 248 = 0xf8
    double m_HookStart; // 256 = 0x100
    double m_HookEnd;   // 264 = 0x108
    int m_NumberOfCourses;  // 272 = 0x110
    _Bool m_Purchased;  // 276 = 0x114
    _Bool _corrupt; // 277 = 0x115
    _Bool _subscribed;  // 278 = 0x116
}

+ (unsigned int)hashCode:(id)arg1 length:(unsigned int)arg2;
+ (void)setAdditionalInfoDictionary:(id)arg1;
+ (void)initialize;
@property(nonatomic) _Bool subscribed; // @synthesize subscribed=_subscribed;
@property(readonly, nonatomic) _Bool corrupt; // @synthesize corrupt=_corrupt;
@property(readonly, nonatomic) int numberOfCourses; // @synthesize numberOfCourses=m_NumberOfCourses;
@property(readonly, nonatomic) double hookStart; // @synthesize hookStart=m_HookStart;
@property(readonly, nonatomic) _Bool purchased; // @synthesize purchased=m_Purchased;
@property(readonly, nonatomic) double scoreDelayTime; // @synthesize scoreDelayTime=m_ScoreDelayTime;
@property(readonly, nonatomic) int animationType; // @synthesize animationType=m_AnimationType;
@property(readonly, nonatomic) unsigned int imagePackDataOffset; // @synthesize imagePackDataOffset=m_ImagePackDataOffset;
@property(readonly, nonatomic) double previewStartTime; // @synthesize previewStartTime=m_PreviewStartTime;
@property(readonly, nonatomic) unsigned int generation; // @synthesize generation=m_Generation;
@property(readonly, nonatomic) unsigned int genre; // @synthesize genre=m_Genre;
@property(readonly, nonatomic) NSString *pronunciation; // @synthesize pronunciation=m_Pronunciation;
@property(readonly, nonatomic) NSString *title; // @synthesize title=m_Title;
@property(readonly, nonatomic) NSString *imagePackPath; // @synthesize imagePackPath=m_ImagePackPath;
@property(readonly, nonatomic) NSString *path; // @synthesize path=m_Path;
@property(readonly, nonatomic) NSString *packageID; // @synthesize packageID=m_PackageID;
@property(readonly, nonatomic) unsigned int genuineVersion; // @synthesize genuineVersion=m_Version;
- (_Bool)isSameMetadataWithFileAtPath:(id)arg1 packageID:(id)arg2 length:(unsigned int)arg3 checkSum:(unsigned int)arg4 packsortnum:(unsigned int)arg5 purchased:(_Bool)arg6;
- (int)generationSortValue;
- (int)genreSortValue;
- (id)animationData;
- (id)identifier;
- (int)getBgCount:(int)arg1;
- (int)getChibiCount:(int)arg1;
- (int)getDancerCount:(int)arg1;
- (struct __sFILE *)scoreFilePointerOfCourse:(unsigned int)arg1;
- (id)binDataOfCourse:(unsigned int)arg1;
- (int)difficultyOfCourse:(unsigned int)arg1;
- (id)musicData;
- (void)dealloc;
- (id)initWithFileAtPath:(id)arg1 packageID:(id)arg2 length:(unsigned int)arg3 checkSum:(unsigned int)arg4 packsortnum:(unsigned int)arg5 purchased:(_Bool)arg6;
- (_Bool)isValid;
- (_Bool)hasBranch:(int)arg1;
- (void)setupWithTaikoMusicData:(id)arg1;
- (void)updateInfo;
- (void)checkIPKBundled;
@property(readonly, nonatomic) _Bool titleImagesUnified;
- (_Bool)IPKBundled;
@property(readonly, nonatomic) _Bool shouldUpdate;
- (_Bool)hasUnifiedIPK;
@property(readonly, nonatomic) unsigned int version;
- (_Bool)hasAnimation;
@property(readonly, nonatomic) unsigned int songPackSortNum;

@end

