//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXMLParserDelegate-Protocol.h"

@class BGAnimation, BGFunction, BGPath, NSDictionary, NSMutableArray, NSString;

@interface BGAnimationFactory : NSObject <NSXMLParserDelegate>
{
    BGAnimation *animation_;	// 8 = 0x8
    _Bool inAnimation_;	// 16 = 0x10
    _Bool inVariable_;	// 17 = 0x11
    _Bool inPath_;	// 18 = 0x12
    _Bool inEdge_;	// 19 = 0x13
    _Bool inFunction_;	// 20 = 0x14
    NSDictionary *animationAttributes_;	// 24 = 0x18
    NSDictionary *variableAttributes_;	// 32 = 0x20
    NSDictionary *pathAttributes_;	// 40 = 0x28
    NSDictionary *edgeAttributes_;	// 48 = 0x30
    NSDictionary *functionAttributes_;	// 56 = 0x38
    NSDictionary *indicatorAttributes_;	// 64 = 0x40
    BGPath *path_;	// 72 = 0x48
    NSMutableArray *edges_;	// 80 = 0x50
    BGFunction *function_;	// 88 = 0x58
    NSMutableArray *indicators_;	// 96 = 0x60
}

+ (id)animationForFile:(id)arg1;
- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

