//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BGAnimation, BGObject;

@interface BGSceneObject : NSObject
{
    struct _AGTEXTUREFRAMEGROUP *group_;	// 8 = 0x8
    struct _AGOBJECT agObject_;	// 16 = 0x10
    BGObject *bgObject_;	// 72 = 0x48
    BGSceneObject *parent_;	// 80 = 0x50
    BGAnimation *animations_[4];	// 88 = 0x58
    unsigned long long flags_;	// 120 = 0x78
    float t_;	// 128 = 0x80
    float x_;	// 132 = 0x84
    float y_;	// 136 = 0x88
    float z_;	// 140 = 0x8c
    float w_;	// 144 = 0x90
    float h_;	// 148 = 0x94
    float ft_;	// 152 = 0x98
    float fx_;	// 156 = 0x9c
    float fy_;	// 160 = 0xa0
    float fsx_;	// 164 = 0xa4
    float fsy_;	// 168 = 0xa8
    int frameIndex_;	// 172 = 0xac
    _Bool hidden_;	// 176 = 0xb0
    _Bool userInteractionEnabled_;	// 177 = 0xb1
    unsigned long long vertexIndex_;	// 184 = 0xb8
    int id_;	// 192 = 0xc0
    struct CGSize hitRectSize_;	// 200 = 0xc8
    CDStruct_83984b6f color_;	// 216 = 0xd8
    unsigned long long numberOfSiblings_;	// 232 = 0xe8
}

+ (id)objectArrayWithObjectInfo:(id)arg1 textureMap:(id)arg2 objectMap:(id)arg3 animationMap:(id)arg4 groupMap:(id)arg5 index:(unsigned long long)arg6;
+ (id)objectWithObjectInfo:(id)arg1 textureMap:(id)arg2 objectMap:(id)arg3 animationMap:(id)arg4 groupMap:(id)arg5 index:(unsigned long long)arg6 sibling:(unsigned long long)arg7;
@property(nonatomic) CDStruct_83984b6f color; // @synthesize color=color_;
@property(readonly, nonatomic) unsigned long long numberOfSiblings; // @synthesize numberOfSiblings=numberOfSiblings_;
@property(nonatomic) int frameIndex; // @synthesize frameIndex=frameIndex_;
@property(nonatomic) struct CGSize hitRectSize; // @synthesize hitRectSize=hitRectSize_;
@property(nonatomic) int id; // @synthesize id=id_;
@property(nonatomic) float h; // @synthesize h=h_;
@property(nonatomic) float w; // @synthesize w=w_;
@property(nonatomic) float z; // @synthesize z=z_;
@property(nonatomic) float y; // @synthesize y=y_;
@property(nonatomic) float x; // @synthesize x=x_;
@property(nonatomic) _Bool userInteractionEnabled; // @synthesize userInteractionEnabled=userInteractionEnabled_;
@property(nonatomic) _Bool hidden; // @synthesize hidden=hidden_;
@property(retain, nonatomic) BGSceneObject *parent; // @synthesize parent=parent_;
- (_Bool)isInfiniteOrFinishedAtTime:(float)arg1;
- (_Bool)isFinishedAtTime:(float)arg1;
- (_Bool)hasAnimation;
- (void)setLooping:(_Bool)arg1;
- (float)durationOfAnimationPart:(unsigned long long)arg1;
- (_Bool)hasAnimationPart:(unsigned long long)arg1;
- (void)updateAtTime:(float)arg1;
- (_Bool)containsPoint:(struct CGPoint)arg1;
- (void)render;
- (void)startAnimationFromTime:(float)arg1 part:(unsigned long long)arg2;
- (void)startAnimation:(id)arg1 fromTime:(float)arg2;
- (void)dealloc;
@property(readonly, nonatomic) float alpha;
@property(readonly, nonatomic) struct _AGOBJECT *agObject;
@property(nonatomic) struct _AGTEXTUREFRAMEGROUP *group;
- (void)setupAGObject;
- (_Bool)hasTexture;

@end

