//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GameOptionIcons : NSObject
{
    struct _AGTEXTUREFRAMEGROUP textureFrameGroup_;	// 8 = 0x8
    struct _AGOBJECT objects_[4];	// 32 = 0x20
    _Bool configured_;	// 256 = 0x100
    int numberOfIcons_;	// 260 = 0x104
    float x_;	// 264 = 0x108
    float y_;	// 268 = 0x10c
    float dx_;	// 272 = 0x110
    unsigned long long alignment_;	// 280 = 0x118
}

- (void)setColor:(unsigned int)arg1;
- (void)renderRelativeX:(float)arg1;
- (void)render;
- (void)setOptions:(unsigned int)arg1;
- (void)convertGameOptions:(unsigned int)arg1 toIndices:(char *)arg2;
- (void)configure;
- (id)initWithTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1 x:(float)arg2 y:(float)arg3 dx:(float)arg4 alignment:(unsigned long long)arg5 gameOptions:(unsigned int)arg6;
- (id)initWithTexture:(struct _AGTEXTURE *)arg1 x:(float)arg2 y:(float)arg3 dx:(float)arg4 alignment:(unsigned long long)arg5 gameOptions:(unsigned int)arg6;
- (id)initWithTexture:(struct _AGTEXTURE *)arg1 textureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg2 x:(float)arg3 y:(float)arg4 dx:(float)arg5 alignment:(unsigned long long)arg6 gameOptions:(unsigned int)arg7;

@end

