//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IMemberInfoForVSSettings : NSObject
{
    NSString *m_strMemberName;	// 8 = 0x8
    unsigned long long m_intMemberName;	// 16 = 0x10
    int m_memberLength;	// 24 = 0x18
}

@property(nonatomic) int memberLength; // @synthesize memberLength=m_memberLength;
@property(nonatomic) unsigned long long intMemberName; // @synthesize intMemberName=m_intMemberName;
@property(retain, nonatomic) NSString *strMemberName; // @synthesize strMemberName=m_strMemberName;
- (void)dealloc;
- (id)init;

@end

