//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMemberInfoForVSResult : NSObject
{
    unsigned long long m_name;	// 8 = 0x8
    int m_color;	// 16 = 0x10
    int m_type;	// 20 = 0x14
    int m_score;	// 24 = 0x18
    int m_hitCount;	// 28 = 0x1c
    int m_winCount;	// 32 = 0x20
    int m_rank;	// 36 = 0x24
    int m_nameLength;	// 40 = 0x28
    unsigned char m_nameImageIndex[5];	// 44 = 0x2c
    int m_scoreTextLength;	// 52 = 0x34
    int m_scoreTextImageIndex[7];	// 56 = 0x38
    unsigned int m_nGKTBArr;	// 84 = 0x54
}

@property(nonatomic) unsigned int arrGKTB; // @synthesize arrGKTB=m_nGKTBArr;
@property(nonatomic) int scoreTextLength; // @synthesize scoreTextLength=m_scoreTextLength;
@property(nonatomic) int userNameLength; // @synthesize userNameLength=m_nameLength;
@property(nonatomic) int rank; // @synthesize rank=m_rank;
@property(nonatomic) int winCount; // @synthesize winCount=m_winCount;
@property(nonatomic) int hitCount; // @synthesize hitCount=m_hitCount;
@property(nonatomic) int score; // @synthesize score=m_score;
@property(nonatomic) int type; // @synthesize type=m_type;
@property(nonatomic) int userColor; // @synthesize userColor=m_color;
@property(nonatomic) unsigned long long userName; // @synthesize userName=m_name;
- (long long)compareDescScore:(id)arg1;
- (long long)compareAscScore:(id)arg1;
- (void)setScoreTextImageIndex:(int)arg1 WithIndex:(int)arg2;
- (int)getScoreTextImageIndex:(int)arg1;
- (int)getScoreTextLength;
- (void)setUserNameImageIndex:(int)arg1 WithIndex:(int)arg2;
- (int)getUserNameImageIndex:(int)arg1;
- (int)getUserNameLength;
- (void)dealloc;
- (id)init;

@end

