//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneBase.h"

#import "GKTaikoBattleDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface ISceneVSResult : ISceneBase <GKTaikoBattleDelegate, UIAlertViewDelegate>
{
    struct _AASAMPLE m_oSampleDrumRoll;	// 72 = 0x48
    struct _AASAMPLE m_oSampleDrumSubmit;	// 96 = 0x60
    struct _AGTEXTURE m_MainTexture;	// 120 = 0x78
    struct _AGTEXTURE m_BackTexture;	// 176 = 0xb0
    struct _AGTEXTURE m_FontTexture;	// 232 = 0xe8
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;	// 288 = 0x120
    struct _AGTEXTUREFRAMEGROUP m_ScoreNumFrameGroup;	// 312 = 0x138
    struct _AGTEXTUREFRAMEGROUP m_NameFrameGroup;	// 336 = 0x150
    struct _AGTEXTUREFRAMEGROUP m_WinCountFrameGroup;	// 360 = 0x168
    struct _AGTEXTUREFRAMEGROUP m_PedestalFrameGroup;	// 384 = 0x180
    struct _AGTEXTUREFRAMEGROUP m_DonGroup[4];	// 408 = 0x198
    struct _AGTEXTUREFRAMEGROUP m_WindowFrameGroup;	// 504 = 0x1f8
    struct _AGTEXTUREFRAMEGROUP m_WindowContentsFrameGroup;	// 528 = 0x210
    struct _AGTEXTUREFRAMEGROUP m_ComNameGroup;	// 552 = 0x228
    struct _AGTEXTUREFRAMEGROUP m_ConnectErrorGroup;	// 576 = 0x240
    struct _AGOBJECT m_BackObject;	// 600 = 0x258
    struct _AGOBJECT m_BackWordObject;	// 656 = 0x290
    struct _AGOBJECT m_ScoreNumObject[4][7];	// 712 = 0x2c8
    struct _AGOBJECT m_NameObject[4][5];	// 2280 = 0x8e8
    struct _AGOBJECT m_WinCountObject[4][3];	// 3400 = 0xd48
    struct _AGOBJECT m_PedestalObject[4];	// 4072 = 0xfe8
    struct _AGOBJECT m_PedestalInfoObject[4];	// 4296 = 0x10c8
    struct _AGOBJECT m_DonObject[4];	// 4520 = 0x11a8
    struct _AGOBJECT m_WindowObject[3];	// 4744 = 0x1288
    struct _AGOBJECT m_WindowContentsObject[5];	// 4912 = 0x1330
    struct _AGOBJECT m_oObjPleaseWait;	// 5192 = 0x1448
    struct _AGOBJECT m_aroObjComName[4];	// 5248 = 0x1480
    struct _AGOBJECT m_aroObjWindowConnectError[3];	// 5472 = 0x1560
    struct _AGOBJECT m_oObjTextConnectError;	// 5640 = 0x1608
    _Bool m_isDraw;	// 5696 = 0x1640
    int m_Counter;	// 5700 = 0x1644
    _Bool m_PedestalAnimationFlag[4];	// 5704 = 0x1648
    float m_PedestalDestY[4];	// 5708 = 0x164c
    float m_PedestalSpeedY[4];	// 5724 = 0x165c
    int m_DonAnimationMode[4];	// 5740 = 0x166c
    int m_DonAnimationCounter[4];	// 5756 = 0x167c
    float m_DonJumpHeight[4];	// 5772 = 0x168c
    struct CGPoint m_DonPosition;	// 5792 = 0x16a0
    int m_ReplySelect;	// 5808 = 0x16b0
    NSMutableArray *m_members;	// 5816 = 0x16b8
    int m_gameResult;	// 5824 = 0x16c0
    unsigned int m_nWindowEnableCount;	// 5828 = 0x16c4
    int m_NextScene;	// 5832 = 0x16c8
    _Bool m_nRecieveWait;	// 5836 = 0x16cc
    _Bool m_nErrorAlert;	// 5837 = 0x16cd
    _Bool m_nShowConnectError;	// 5838 = 0x16ce
    _Bool m_nShowWindow;	// 5839 = 0x16cf
    _Bool m_bEndIdle;	// 5840 = 0x16d0
    _Bool m_bAllClientsReady;	// 5841 = 0x16d1
}

- (void)didPresentAlertView:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)disconnectAllPeer;
- (void)recieveData:(id)arg1 Scene:(unsigned int)arg2 Order:(unsigned int)arg3 Arr:(unsigned int)arg4;
- (void)applicationWillResignActive;
- (int)stateAlert;
- (int)stateRecieveWait;
- (int)stateFadeOutFromAlert;
- (int)stateFadeOut;
- (int)stateReplay;
- (int)stateIdleForClient;
- (int)stateWaitServerReady;
- (int)stateWaitAllClientsReady;
- (int)stateIdle;
- (int)stateCountScore;
- (void)setWaitRoutine;
- (int)stateFadeIn;
- (int)stateFadeInBefore;
- (void)updateAnimation;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

