//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneDialog.h"

@class NSDictionary, TaikoLoginBonusItem, TaikoPrizeManager, TaikoSceneNode;

@interface ISceneStartBonusDialog : ISceneDialog
{
    TaikoSceneNode *todaysGetNode_;	// 72 = 0x48
    TaikoSceneNode *footerNode_;	// 80 = 0x50
    TaikoLoginBonusItem *startupItem_;	// 88 = 0x58
    TaikoLoginBonusItem *firstItem_;	// 96 = 0x60
    _Bool todaysItemSetup_;	// 104 = 0x68
    _Bool _startupBonus;	// 105 = 0x69
    int _totalLogin;	// 108 = 0x6c
    TaikoPrizeManager *_prizeManager;	// 112 = 0x70
    NSDictionary *_responseDictionary;	// 120 = 0x78
}

@property(readonly, nonatomic) int totalLogin; // @synthesize totalLogin=_totalLogin;
@property(readonly, nonatomic) _Bool startupBonus; // @synthesize startupBonus=_startupBonus;
@property(copy, nonatomic) NSDictionary *responseDictionary; // @synthesize responseDictionary=_responseDictionary;
@property(nonatomic) TaikoPrizeManager *prizeManager; // @synthesize prizeManager=_prizeManager;
- (_Bool)prepare;
- (_Bool)setupItems;
- (void)setupStartupBonusDialog;
- (_Bool)setupTodaysItem;
- (void)start;
- (void)clearFlags;
- (void)reset;
- (id)initWithManager:(id)arg1 windowFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg2 messageFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3 buttonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg4 choiceFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 digitFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg6 miscFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg7 itemPlateFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg8 itemNameFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg9;
- (void)dealloc;

@end

