//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BGSceneBase.h"

@class BGSceneObject;

@interface ISceneOptionButton : BGSceneBase
{
    BGSceneObject *buttonObject_;	// 112 = 0x70
    _Bool appearing_;	// 120 = 0x78
    _Bool hidden_;	// 121 = 0x79
}

@property(nonatomic) _Bool hidden; // @synthesize hidden=hidden_;
- (void)setColor:(unsigned int)arg1;
- (_Bool)isPressed:(struct CGPoint)arg1;
- (void)appear:(_Bool)arg1;
- (int)stateRun;
- (void)sceneStart;
- (void)render;
- (int)update;
- (void)sceneDestroy;
- (void)sceneLoad;
- (id)initWithManager:(id)arg1 frameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg2 frameIndex:(int)arg3;

@end

