//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneBase.h"

#import "BGDownloadDelegate-Protocol.h"
#import "BGSNSInterfaceDelegate-Protocol.h"
#import "LicenseViewControllerDelegate-Protocol.h"
#import "SKProductsRequestDelegate-Protocol.h"
#import "SceneDialogDelegate-Protocol.h"

@class BGDownload, ISceneDialog, ISceneNamePlate, ISceneOptionButton, ISceneOptionSelectDialog, ISceneScoreDialog, ISceneSortSelectDialog, ISceneSubscriptionMenu, NSArray, NSData, NSDateFormatter, NSMutableArray, NSMutableDictionary, NSString, SongCoursePlate, TaikoAction, TaikoButton, TaikoNumberLabel, TaikoProgressIndicator, TaikoRestore, TaikoSceneNode, TaikoTextureCache, UIActivityIndicatorView;

@interface ISceneSongSelect : ISceneBase <BGSNSInterfaceDelegate, SKProductsRequestDelegate, SceneDialogDelegate, BGDownloadDelegate, LicenseViewControllerDelegate>
{
    struct _AASAMPLE m_StartSample;	// 72 = 0x48
    struct _AASAMPLE m_SongSelectedSample;	// 96 = 0x60
    struct _AGTEXTURE m_MainTexture;	// 120 = 0x78
    struct _AGTEXTURE m_BarTexture;	// 176 = 0xb0
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;	// 232 = 0xe8
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;	// 256 = 0x100
    struct _AGTEXTUREFRAMEGROUP m_BarFrameGroup;	// 280 = 0x118
    struct _AGTEXTUREFRAMEGROUP m_ExpandingBarFrameGroup;	// 304 = 0x130
    struct _AGTEXTUREFRAMEGROUP m_OptionLabelTitleGroup;	// 328 = 0x148
    struct _AGTEXTUREFRAMEGROUP m_OptionLabelCharGroup;	// 352 = 0x160
    struct _AGTEXTUREFRAMEGROUP m_OptionLabelSongAddTitleGroup;	// 376 = 0x178
    struct _AGTEXTUREFRAMEGROUP m_CrownFrameGroup;	// 400 = 0x190
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;	// 424 = 0x1a8
    struct _AGTEXTUREFRAMEGROUP m_OkButtonFrameGroup;	// 448 = 0x1c0
    struct _AGTEXTUREFRAMEGROUP m_CloseButtonFrameGroup;	// 472 = 0x1d8
    struct _AGTEXTUREFRAMEGROUP m_SortFrameGroup;	// 496 = 0x1f0
    struct _AGTEXTUREFRAMEGROUP m_PopupWindow1FrameGroup;	// 520 = 0x208
    struct _AGTEXTUREFRAMEGROUP m_PopupWindow2FrameGroup;	// 544 = 0x220
    struct _AGTEXTUREFRAMEGROUP m_DownloadFrameGroup;	// 568 = 0x238
    struct _AGTEXTUREFRAMEGROUP m_UpdateTitleFrameGroup;	// 592 = 0x250
    struct _AGTEXTUREFRAMEGROUP m_UpdateImageFrameGroup;	// 616 = 0x268
    struct _AGTEXTUREFRAMEGROUP m_NewIconFrameGroup;	// 640 = 0x280
    struct _AGTEXTUREFRAMEGROUP m_NewMessageFrameGroup;	// 664 = 0x298
    struct _AGTEXTUREFRAMEGROUP m_ToneBackFrameGroup;	// 688 = 0x2b0
    struct _AGOBJECT m_BackObject;	// 712 = 0x2c8
    struct _AGOBJECT m_TitleObject;	// 768 = 0x300
    struct _AGOBJECT m_BarObject;	// 824 = 0x338
    struct _AGOBJECT m_ExpandingBarObject[3];	// 880 = 0x370
    struct _AGOBJECT m_CrownObject;	// 1048 = 0x418
    struct _AGOBJECT m_OptionLabelCharObject;	// 1104 = 0x450
    struct _AGOBJECT m_ExerciseCharObject;	// 1160 = 0x488
    struct _AGOBJECT m_BackButtonObject;	// 1216 = 0x4c0
    struct _AGOBJECT m_SortButtonObject;	// 1272 = 0x4f8
    struct _AGOBJECT m_SongTitleObject;	// 1328 = 0x530
    struct _AGOBJECT m_UpdateImageObject;	// 1384 = 0x568
    struct _AGTEXTUREFRAMEGROUP m_OptionButtonFrameGroup;	// 1440 = 0x5a0
    ISceneOptionButton *m_SceneOptionButton;	// 1464 = 0x5b8
    int m_OptionState;	// 1472 = 0x5c0
    ISceneOptionSelectDialog *m_SceneOptionSelectDialog;	// 1480 = 0x5c8
    struct _AGTEXTUREFRAMEGROUP m_OptionSelectDialogFrameGroup;	// 1488 = 0x5d0
    struct _AGTEXTUREFRAMEGROUP m_DogFrameGroup[2];	// 1512 = 0x5e8
    struct _AGTEXTUREFRAMEGROUP m_ScoreButtonFrameGroup;	// 1560 = 0x618
    struct _AGOBJECT m_ScoreButtonObject;	// 1584 = 0x630
    struct _AGTEXTUREFRAMEGROUP m_OnlineRankingButtonFrameGroup;	// 1640 = 0x668
    struct _AGTEXTUREFRAMEGROUP m_ScoreDialogFrameGroup;	// 1664 = 0x680
    struct _AGTEXTUREFRAMEGROUP m_NumberFixFrameGroup;	// 1688 = 0x698
    struct _AGTEXTUREFRAMEGROUP m_NumberWfixFrameGroup;	// 1712 = 0x6b0
    struct _AGTEXTUREFRAMEGROUP m_OptionIconFrameGroup;	// 1736 = 0x6c8
    ISceneScoreDialog *m_SceneScoreDialog;	// 1760 = 0x6e0
    struct _AGTEXTUREFRAMEGROUP m_ResetScoreDialogWindowFrameGroup;	// 1768 = 0x6e8
    struct _AGTEXTUREFRAMEGROUP m_ResetScoreDialogMessageFrameGroup;	// 1792 = 0x700
    struct _AGTEXTUREFRAMEGROUP m_ResetScoreDialogButtonFrameGroup;	// 1816 = 0x718
    struct _AGTEXTUREFRAMEGROUP m_ResetScoreDialogChoiceFrameGroup;	// 1840 = 0x730
    ISceneDialog *m_ResetScoreDialog;	// 1864 = 0x748
    ISceneSortSelectDialog *m_SceneSortSelectDialog;	// 1872 = 0x750
    struct _AGTEXTUREFRAMEGROUP m_SortSelectDialogFrameGroup;	// 1880 = 0x758
    struct _AGTEXTUREFRAMEGROUP m_DownloadSongDialogWindowFrameGroup;	// 1904 = 0x770
    struct _AGTEXTUREFRAMEGROUP m_DownloadSongDialogMessageFrameGroup;	// 1928 = 0x788
    ISceneDialog *m_DownloadSongDialog;	// 1952 = 0x7a0
    struct _AGTEXTUREFRAMEGROUP m_UpdateSongsDialogWindowFrameGroup;	// 1960 = 0x7a8
    struct _AGTEXTUREFRAMEGROUP m_UpdateSongsDialogMessageFrameGroup;	// 1984 = 0x7c0
    ISceneDialog *m_UpdateSongsDialog;	// 2008 = 0x7d8
    struct _AGTEXTUREFRAMEGROUP m_RestoreSongsDialogWindowFrameGroup;	// 2016 = 0x7e0
    struct _AGTEXTUREFRAMEGROUP m_RestoreSongsDialogMessageFrameGroup;	// 2040 = 0x7f8
    ISceneDialog *m_RestoreSongsDialog;	// 2064 = 0x810
    NSMutableDictionary *m_Record;	// 2072 = 0x818
    int m_SelectedCourse;	// 2080 = 0x820
    int m_LastSelectedCourse;	// 2084 = 0x824
    int m_ScrollSong;	// 2088 = 0x828
    int m_SortState;	// 2092 = 0x82c
    _Bool m_HideDisabledBar;	// 2096 = 0x830
    float m_BackStartPosition;	// 2100 = 0x834
    struct CGPoint m_BarCenter;	// 2104 = 0x838
    float m_BarSpace;	// 2120 = 0x848
    struct CGPoint m_SongTitlePosition;	// 2128 = 0x850
    struct CGPoint m_CrownPosition;	// 2144 = 0x860
    struct CGPoint m_OptionLabelCharPosition;	// 2160 = 0x870
    struct CGPoint m_OptionLabelCharOfs;	// 2176 = 0x880
    float m_ScrollMinSpeed;	// 2192 = 0x890
    float m_ExpandingBarWidth;	// 2196 = 0x894
    float m_ExpandingBarSize;	// 2200 = 0x898
    int m_ExpandingBarWaitDuration;	// 2204 = 0x89c
    struct CGPoint m_ScrollPosition;	// 2208 = 0x8a0
    float m_ScrollSpeed;	// 2224 = 0x8b0
    float m_BarSplitPosition;	// 2228 = 0x8b4
    struct CGPoint m_StartTouchPoint;	// 2232 = 0x8b8
    int m_SongSelectedCounter;	// 2248 = 0x8c8
    int m_FadeCounter;	// 2252 = 0x8cc
    int m_ExpandWaitCounter;	// 2256 = 0x8d0
    int m_ExpandingBarExpandingDuration;	// 2260 = 0x8d4
    int m_NextScene;	// 2264 = 0x8d8
    int m_PauseState;	// 2268 = 0x8dc
    int m_PauseCounter;	// 2272 = 0x8e0
    int m_PauseSelect;	// 2276 = 0x8e4
    struct CGRect m_PauseCollisions[6];	// 2280 = 0x8e8
    _Bool m_TouchActive;	// 2472 = 0x9a8
    _Bool m_TouchScroll;	// 2473 = 0x9a9
    _Bool m_LoadBGM;	// 2474 = 0x9aa
    _Bool m_PlayedBGM;	// 2475 = 0x9ab
    NSArray *m_SortGroupRangeList;	// 2480 = 0x9b0
    const int *m_SortGroupFrameIndices;	// 2488 = 0x9b8
    float m_MaxScrollSpeed;	// 2496 = 0x9c0
    unsigned long long m_PreservedGameOptions;	// 2504 = 0x9c8
    _Bool m_DontamaPressed;	// 2512 = 0x9d0
    NSString *purchasingProductIdentifier_;	// 2520 = 0x9d8
    NSString *resumingProductIdentifier_;	// 2528 = 0x9e0
    int m_ReturnToMenuOnError;	// 2536 = 0x9e8
    _Bool m_Destroyed;	// 2540 = 0x9ec
    struct CGPoint m_CollaboLabelCharOfs;	// 2544 = 0x9f0
    unsigned long long m_TotalFileSize;	// 2560 = 0xa00
    unsigned long long m_DownloadedSize;	// 2568 = 0xa08
    _Bool m_DownloadError;	// 2576 = 0xa10
    int m_BarLoopMinNum;	// 2580 = 0xa14
    struct _AGTEXTURE m_DialogTexture;	// 2584 = 0xa18
    _Bool m_ShowRestoreDialog;	// 2640 = 0xa50
    _Bool m_ShowRestoreSystemDialog;	// 2641 = 0xa51
    TaikoRestore *m_TaikoRestore;	// 2648 = 0xa58
    struct _AGTEXTURE m_PrimordialCollaboTexture;	// 2656 = 0xa60
    struct _AGTEXTUREFRAMEGROUP m_PrimordialCollaboFrameGroup;	// 2712 = 0xa98
    struct _AGTEXTUREFRAMEGROUP m_CourseButtonFrameGroup;	// 2736 = 0xab0
    struct _AGTEXTUREFRAMEGROUP m_CourseIconFrameGroup;	// 2760 = 0xac8
    struct _AGTEXTUREFRAMEGROUP m_CourseTitleFrameGroup;	// 2784 = 0xae0
    struct _AGTEXTUREFRAMEGROUP m_CourseCrownFrameGroup;	// 2808 = 0xaf8
    struct _AGTEXTUREFRAMEGROUP m_CourseDifficultyFrameGroup;	// 2832 = 0xb10
    struct _AGTEXTUREFRAMEGROUP m_CourseStarFrameGroup;	// 2856 = 0xb28
    SongCoursePlate *m_CoursePlates[5];	// 2880 = 0xb40
    SongCoursePlate *m_PressedCoursePlate;	// 2920 = 0xb68
    _Bool m_CourseDecided;	// 2928 = 0xb70
    ISceneNamePlate *m_SceneNamePlate;	// 2936 = 0xb78
    struct _AGTEXTUREFRAMEGROUP m_BarTopLeftFrameGroup;	// 2944 = 0xb80
    struct _AGTEXTUREFRAMEGROUP m_BarTopMiddleFrameGroup;	// 2968 = 0xb98
    struct _AGTEXTUREFRAMEGROUP m_BarTopRightFrameGroup;	// 2992 = 0xbb0
    struct _AGTEXTUREFRAMEGROUP m_BarTopTitleFrameGroups[6];	// 3016 = 0xbc8
    struct _AGOBJECT m_BarTopLeftObject;	// 3160 = 0xc58
    struct _AGOBJECT m_BarTopMiddleObject;	// 3216 = 0xc90
    struct _AGOBJECT m_BarTopRightObject;	// 3272 = 0xcc8
    struct _AGOBJECT m_BarTopTitleObject;	// 3328 = 0xd00
    NSMutableArray *m_BarInfoArray;	// 3384 = 0xd38
    _Bool m_BarTopRendering;	// 3392 = 0xd40
    struct _AGTEXTUREFRAMEGROUP m_GroupButtonLeftFrameGroup;	// 3400 = 0xd48
    struct _AGTEXTUREFRAMEGROUP m_GroupButtonRightFrameGroup;	// 3424 = 0xd60
    TaikoButton *m_GroupButtonLeft;	// 3448 = 0xd78
    TaikoButton *m_GroupButtonRight;	// 3456 = 0xd80
    int m_NextTitleObjectFrameIndex;	// 3464 = 0xd88
    int m_CurrentTitleObjectFrameIndex;	// 3468 = 0xd8c
    _Bool m_ScoreDialogPrepared;	// 3472 = 0xd90
    _Bool m_OptionSelectDialogPrepared;	// 3473 = 0xd91
    TaikoTextureCache *m_TextureCache;	// 3480 = 0xd98
    struct _AGTEXTUREFRAMEGROUP m_CourseOverlayFrameGroup;	// 3488 = 0xda0
    TaikoSceneNode *m_CourseOverlays[4];	// 3512 = 0xdb8
    struct _AGOBJECT m_Cursor;	// 3544 = 0xdd8
    TaikoAction *m_CursorAnimation;	// 3600 = 0xe10
    _Bool m_SongSelected;	// 3608 = 0xe18
    int m_BGMWaitCounter;	// 3612 = 0xe1c
    int m_BGMWaitCounterMax;	// 3616 = 0xe20
    struct dispatch_queue_s *m_BGMDispatchQueue;	// 3624 = 0xe28
    float m_ScrollSpeedTouchBegan;	// 3632 = 0xe30
    float m_InitialDX;	// 3636 = 0xe34
    float m_EvaluatedScrollX;	// 3640 = 0xe38
    unsigned int m_KatsuInputs;	// 3644 = 0xe3c
    int m_SongSelectionWait;	// 3648 = 0xe40
    BGDownload *m_SongDownload;	// 3656 = 0xe48
    _Bool m_NeedsReenter;	// 3664 = 0xe50
    struct _AGTEXTUREFRAMEGROUP m_EndDateDigitFrameGroup;	// 3672 = 0xe58
    struct _AGOBJECT m_EndDateDigitObject;	// 3696 = 0xe70
    TaikoProgressIndicator *m_ProgressIndicator;	// 3752 = 0xea8
    struct _AGTEXTURE m_SubscriptionMenuTexture;	// 3760 = 0xeb0
    struct _AGTEXTUREFRAMEGROUP m_TFGSubscriptionMenuMain;	// 3816 = 0xee8
    struct _AGTEXTUREFRAMEGROUP m_TFGSubscriptionMenuWindow[4];	// 3840 = 0xf00
    struct _AGTEXTUREFRAMEGROUP m_TFGCloseButton;	// 3936 = 0xf60
    struct _AGTEXTUREFRAMEGROUP m_TFGRestoreButton;	// 3960 = 0xf78
    struct _AGTEXTUREFRAMEGROUP m_TFGDialogButton;	// 3984 = 0xf90
    struct _AGTEXTUREFRAMEGROUP m_TFGDialogChoice;	// 4008 = 0xfa8
    struct _AGTEXTUREFRAMEGROUP m_TFGDeleteCheckBox;	// 4032 = 0xfc0
    struct _AGOBJECT m_CheckBoxObject;	// 4056 = 0xfd8
    ISceneSubscriptionMenu *m_SceneSubscriptionMenu;	// 4112 = 0x1010
    _Bool m_SceneSubscriptionMenuStarted;	// 4120 = 0x1018
    _Bool m_SubscribedWhenSceneStart;	// 4121 = 0x1019
    _Bool m_SubscriptionSelectSong;	// 4122 = 0x101a
    int m_CheckingSongNum;	// 4124 = 0x101c
    ISceneDialog *m_SubscriptionDeleteFinishDialog;	// 4128 = 0x1020
    struct _AGTEXTUREFRAMEGROUP m_TFGDeleteFinishDialog;	// 4136 = 0x1028
    struct _AGTEXTUREFRAMEGROUP m_TFGDeleteFinishDialogMessage;	// 4160 = 0x1040
    TaikoSceneNode *m_DeleteMessageNode[2];	// 4184 = 0x1058
    TaikoNumberLabel *m_DeleteMessageNumLabel;	// 4200 = 0x1068
    struct _AGTEXTUREFRAMEGROUP m_TFGSubscriptionStock;	// 4208 = 0x1070
    struct _AGOBJECT m_StockLabelObject;	// 4232 = 0x1088
    struct _AGOBJECT m_StockNumberObject[3];	// 4288 = 0x10c0
    NSData *m_TrialListenDownloadedData;	// 4456 = 0x1168
    BGDownload *m_TrialListenBgDownload;	// 4464 = 0x1170
    struct _AGTEXTUREFRAMEGROUP m_TFGSubscription;	// 4472 = 0x1178
    struct _AGOBJECT m_SubscriptionButtonObject;	// 4496 = 0x1190
    struct _AGOBJECT m_SubscriptionButtonTextObject;	// 4552 = 0x11c8
    struct _AGTEXTUREFRAMEGROUP m_TFGSongAdd;	// 4608 = 0x1200
    struct _AGOBJECT m_SongAddSumiObject;	// 4632 = 0x1218
    struct _AGOBJECT m_SongAddNewObject;	// 4688 = 0x1250
    struct _AGOBJECT m_SongAddTrialListenObject;	// 4744 = 0x1288
    struct _AGOBJECT m_SongAddTrialListenTextObject;	// 4800 = 0x12c0
    struct _AGOBJECT m_SongAddTrialListenAnime;	// 4856 = 0x12f8
    struct _AGOBJECT m_SongAddUpdateObject;	// 4912 = 0x1330
    struct _AGTEXTUREFRAMEGROUP m_TFGSongAddDialog;	// 4968 = 0x1368
    struct _AGTEXTUREFRAMEGROUP m_TFGSongAddDialog2;	// 4992 = 0x1380
    struct _AGTEXTUREFRAMEGROUP m_TFGSongAddDialogMessage;	// 5016 = 0x1398
    ISceneDialog *m_SongAddCheckOverDialog;	// 5040 = 0x13b0
    ISceneDialog *m_SongAddUpdateConfirmDialog;	// 5048 = 0x13b8
    ISceneDialog *m_SongAddUpdateFinishDialog;	// 5056 = 0x13c0
    ISceneDialog *m_SongAddCheckSongNumDialog;	// 5064 = 0x13c8
    _Bool m_TrialListenOnlyMode;	// 5072 = 0x13d0
    int m_TrialListenTextCounter;	// 5076 = 0x13d4
    NSString *m_TrialListenDownloadingSongID;	// 5080 = 0x13d8
    NSString *m_TrialListenPlayingSongID;	// 5088 = 0x13e0
    int m_CheckBoxNum;	// 5096 = 0x13e8
    int m_SubscriptionDownloadedSongsNum;	// 5100 = 0x13ec
    _Bool m_WaitingSubscriptionDistributeInfo;	// 5104 = 0x13f0
    UIActivityIndicatorView *m_TrialListenIndicator;	// 5112 = 0x13f8
    int m_TrialListenCounter;	// 5120 = 0x1400
    _Bool m_ShowSubsciptionValidationFailedAlert;	// 5124 = 0x1404
    _Bool m_SongAddUpdateDownloadFinished;	// 5125 = 0x1405
    int m_SubscriptionButtonTextCounter;	// 5128 = 0x1408
    _Bool m_SubscriptionButtonEnabled;	// 5132 = 0x140c
    _Bool m_TrialListenStartAfterScroll;	// 5133 = 0x140d
    _Bool m_RecommendOpenSubscriptionMenu;	// 5134 = 0x140e
    _Bool m_ShowNewSongs;	// 5135 = 0x140f
    struct _AGTEXTUREFRAMEGROUP m_NewSongsDialogMessageFrameGroup;	// 5136 = 0x1410
    ISceneDialog *m_NewSongsDialog;	// 5160 = 0x1428
    _Bool m_ShowExerciseUpdated;	// 5168 = 0x1430
    _Bool m_ShowExerciseImageError;	// 5169 = 0x1431
    _Bool m_ShowExerciseRetry;	// 5170 = 0x1432
    _Bool m_ExerciseRetryWaiting;	// 5171 = 0x1433
    struct _AGTEXTUREFRAMEGROUP m_ExerciseDialogFrameGroup;	// 5176 = 0x1438
    struct _AGTEXTUREFRAMEGROUP m_ExerciseDialogMessageFrameGroup;	// 5200 = 0x1450
    ISceneDialog *m_ExerciseUpdatedDialog;	// 5224 = 0x1468
    NSDateFormatter *dateFormatter_;	// 5232 = 0x1470
    NSMutableArray *boxList_;	// 5240 = 0x1478
    NSMutableArray *collaboBoxList_;	// 5248 = 0x1480
    int currentBoxIndex_;	// 5256 = 0x1488
    unsigned int _subscriptionMode;	// 5260 = 0x148c
}

@property(nonatomic) unsigned int subscriptionMode; // @synthesize subscriptionMode=_subscriptionMode;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)startDownloadingTrialListen:(id)arg1;
- (void)restoreTransactionsFailedWithError:(id)arg1;
- (void)restoreTransactionsCompleted;
- (void)transactionFailedWithTransaction:(id)arg1;
- (_Bool)transactionCompletedWithTransaction:(id)arg1;
- (void)restoreTransactionsFailedWithError_Local:(id)arg1;
- (void)restoreTransactionsCompleted_Local;
- (_Bool)transactionCompletedWithTransaction_Local:(id)arg1;
- (void)moveNextGroup:(id)arg1;
- (void)movePreviousGroup:(id)arg1;
- (int)sortGroupIndexWithBoxIndex:(int)arg1;
- (int)sortGroupIndexWithSongInfo:(id)arg1 type:(int)arg2;
- (void)groupBoxListWithType:(int)arg1;
- (void)sortBox_Generation;
- (void)sortBox_LatestPlay;
- (int)playDateWithSongInfo:(id)arg1 playTime:(int *)arg2;
- (void)sortBox_PlayCount;
- (unsigned int)totalPlayCountWithSongInfo:(id)arg1;
- (void)sortBox_Genre;
- (void)sortBox_Pronunciation;
- (void)sortBox_Pack;
- (void)sortBoxListWithType:(int)arg1;
- (void)renderBoxSubscription:(id)arg1 position:(struct CGPoint *)arg2 boxIndex:(int)arg3;
- (void)renderBoxNormalSong:(id)arg1 position:(struct CGPoint *)arg2 boxIndex:(int)arg3;
- (void)renderBoxCollaboDownload:(id)arg1 position:(struct CGPoint *)arg2 boxIndex:(int)arg3;
- (void)renderBoxGotoSongAdd:(id)arg1 position:(struct CGPoint *)arg2 boxIndex:(int)arg3;
- (void)renderBoxGotoStore:(id)arg1 position:(struct CGPoint *)arg2 boxIndex:(int)arg3;
- (_Bool)decreaseBoxIndex:(int *)arg1;
- (_Bool)increaseBoxIndex:(int *)arg1;
- (void)loadCurrentBoxIndex:(_Bool)arg1;
- (void)saveCurrentBoxIndex;
- (_Bool)isOptionLabelWithBoxIndex:(int)arg1;
- (_Bool)isOptionLabelSelected;
- (id)getCollaboInfoWithSongID:(id)arg1;
- (int)getBoxIndexWithSongInfo:(id)arg1;
- (int)getBoxIndexWithObject:(id)arg1;
- (int)getBoxIndexWithSongID:(id)arg1 type:(unsigned int)arg2;
- (int)getBoxIndexWithType:(unsigned int)arg1;
- (int)getBoxNum:(unsigned int)arg1;
- (void)addBoxInfo:(unsigned int)arg1 info:(id)arg2;
- (id)currentBoxInfo;
- (void)makeCollaboBox;
- (void)sceneDialog:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)resetGameResultScoreWithSongInfo:(id)arg1 course:(unsigned long long)arg2;
- (_Bool)enableScoreButton;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)setupFrameIndicesWithType:(int)arg1;
- (id)dateLatestPlayWithSongInfo:(id)arg1;
- (const CDStruct_6cc9a17f *)getSongRecordWithSongID:(id)arg1;
- (int)stateFadeOut;
- (void)changeState;
- (int)stateFadeIn;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)resumeFromError:(int)arg1 buttonIndex:(long long)arg2;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)musicDataDownloadDidFailWithObject:(id)arg1;
- (void)downloadDidFinish:(id)arg1;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)checkDownloadedCollaboMusicData:(id)arg1;
- (_Bool)checkDownloadedMusicData:(id)arg1 song:(id)arg2;
- (int)stateWaitingSubscriptionDistributeInfo;
- (int)stateSongAddUpdateFinishDialog;
- (int)stateWaitingSubscriptionUpdateSongDownload;
- (int)stateWaitingSubscriptionUpdateIF64;
- (int)stateSongAddUpdateConfirmDialog;
- (int)stateSongAddCheckSongNumDialog;
- (int)stateSongAddCheckOverDialog;
- (int)stateSubscriptionDeleteFinish;
- (int)stateSubscriptionDeleting;
- (int)stateExerciseRetryDialog;
- (int)stateExerciseImageErrorDialog;
- (int)stateExerciseUpdatedDialog;
- (int)stateCollaboInfoDownloading;
- (int)stateIdle;
- (int)stateWait;
- (int)stateDownload;
- (int)stateDialogDownload;
- (int)stateDialogRestore;
- (void)startRestoration;
- (int)stateCollaboDownloadCompleted;
- (int)stateCollaboDownloading;
- (void)returnToStateRunWithDownloadError;
- (int)stateCollaboDialog;
- (void)startDownloadingCollaboSong:(id)arg1;
- (int)stateSongSelected;
- (void)prepareSubscriptionMenu;
- (int)stateSubscriptionMenu;
- (int)stateScoreDialog;
- (void)prepareScoreDialogFromRanking:(_Bool)arg1;
- (int)stateSortSelectDialog;
- (int)stateOptionSelectDialog;
- (int)stateNewSongsDialog;
- (void)startScene;
- (void)resumeScene;
- (int)stateRun;
- (void)startBGMAfterCountdown;
- (void)stopBGM:(_Bool)arg1;
- (void)stateRun_processTouch;
- (_Bool)isMoving;
- (void)evaluateScrollX;
- (void)adjustLeftEdge;
- (void)adjustRightEdge;
- (void)stopScrolling;
- (_Bool)isScrolledOverLeftEdge;
- (_Bool)isScrolledOverRightEdge;
- (_Bool)selectsLeftEdgeSong;
- (_Bool)selectsRightEdgeSong;
- (_Bool)isLoopable;
- (void)renderSongSelectCursor;
- (void)stateRun_processTaikoControllerInput;
- (_Bool)decideExpandinbBar;
- (void)decideOnSubscriptionPlateWithMusicID;
- (void)decideOnPurchasePlateWithMusicID;
- (void)decideOnCollaboPlateWithMusicID;
- (void)decideDeleteSubscriptionSongs;
- (void)licenseViewControllerClosed;
- (void)decideDeleteButton:(_Bool)arg1;
- (_Bool)startDownloadSubscriptionSongs:(id)arg1;
- (void)decideSongAddButton:(_Bool)arg1;
- (void)decideAllSelectButton;
- (_Bool)decideBarSongAdd:(int)arg1 center:(_Bool)arg2;
- (void)configureCoursePlates;
- (void)configureCoursePlatePositionWithNumberOfCourses:(int)arg1;
- (void)arrangeExpandingBarWidth;
- (void)loadBGM;
- (void)goToVDrumsSettings;
- (void)reenter;
- (void)goToSongSelect;
- (void)goToGame;
- (void)prepareStateToFadeOut:(_Bool)arg1;
- (void)goToMenu;
- (void)goToOut;
- (void)render;
- (void)updateAnimation;
- (void)updateTitleObject;
- (int)titleObjectFrameIndex;
- (_Bool)isScrolling;
- (void)renderBarsAtPosition:(struct CGPoint)arg1;
- (void)renderBarTopsAtPosition:(struct CGPoint)arg1;
- (void)renderBarTops;
- (void)renderBarTopWithBarInfo:(id)arg1;
- (void)addBarInfoWithFrameIndex:(int)arg1 left:(float)arg2 right:(float)arg3;
- (void)renderCrownWithSongInfo:(id)arg1 x:(double)arg2 y:(double)arg3 alpha:(unsigned long long)arg4;
- (void)renderSongTitleWithFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1 x:(float)arg2 y:(float)arg3 unified:(_Bool)arg4 shouldUpdate:(_Bool)arg5 center:(_Bool)arg6 boxIndex:(int)arg7;
- (void)renderCollaboSongTitleWitInfo:(id)arg1 x:(float)arg2 y:(float)arg3;
- (void)renderSongEndDateWithBoxInfo:(id)arg1 x:(float)arg2 y:(float)arg3;
- (void)renderSongEndDateDigitString:(id)arg1 begin:(int)arg2 end:(int)arg3 y:(float)arg4 x:(float)arg5 ax:(float)arg6 dx:(float)arg7;
- (void)renderEndDateDigitWithFrameIndex:(int)arg1 x:(float)arg2 y:(float)arg3;
- (void)touchCheckBox:(int)arg1;
- (void)renderCheckBox:(id)arg1 x:(float)arg2 y:(float)arg3 center:(_Bool)arg4;
- (void)sceneStart;
- (void)sceneDestroy;
- (int)update;
- (void)updateInput;
- (void)deselectCourse;
- (void)selectCourse:(id)arg1;
- (void)disableToSelectCourse:(id)arg1;
- (void)enableToSelectCourse:(id)arg1;
- (void)enableCoursePlates;
- (id)plateComposedOfButton:(id)arg1;
- (void)changeBGM;
- (void)enableGroupButton:(id)arg1;
- (id)setupGroupButtonWithTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1 originX:(double)arg2 bounds:(struct CGRect)arg3 touchDownSelector:(SEL)arg4 moveLeft:(_Bool)arg5;
- (void)sceneLoad;
- (_Bool)skipCollabo:(id)arg1;
- (id)recordDataWithSongInfo:(id)arg1;
- (int)collaboIDStringToIndex:(id)arg1;
- (void)alertFailureWithTitle:(id)arg1 message:(id)arg2 tag:(int)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

