//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BGSceneBase.h"

@class TaikoWindow;

@interface ISceneSortSelectDialog : BGSceneBase
{
    int pauseState_;	// 108 = 0x6c
    int pauseCounter_;	// 112 = 0x70
    int beginningSortState_;	// 116 = 0x74
    unsigned int pauseBackColor_;	// 120 = 0x78
    _Bool isShortMode_;	// 124 = 0x7c
    _Bool isHideDisabledBarMode_;	// 125 = 0x7d
    int *currentTitleObjectFrameIndex_;	// 128 = 0x80
    int *nextTitleObjectFrameIndex_;	// 136 = 0x88
    int savedTitleObjectFrameIndex_;	// 144 = 0x90
    struct CGRect yesNoCollisions_[2];	// 152 = 0x98
    struct _AGOBJECT headObject_[2];	// 216 = 0xd8
    struct _AGOBJECT textObject_[7];	// 328 = 0x148
    struct _AGOBJECT yesNoObject_[2];	// 720 = 0x2d0
    struct _AGOBJECT textBackObject_[2];	// 832 = 0x340
    struct _AGOBJECT yesNoBackObject_[2];	// 944 = 0x3b0
    struct _AGOBJECT okButtonObject_;	// 1056 = 0x420
    TaikoWindow *window_;	// 1112 = 0x458
    _Bool _hideDisabledBar;	// 1120 = 0x460
    int _sortState;	// 1124 = 0x464
}

@property(nonatomic) _Bool hideDisabledBar; // @synthesize hideDisabledBar=_hideDisabledBar;
@property(nonatomic) int sortState; // @synthesize sortState=_sortState;
- (_Bool)isUserInteractionEnabled;
- (int)stateRun;
- (void)render;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)dealloc;
- (id)initWithManager:(id)arg1 isShortMode:(_Bool)arg2 isHideDisabledBarMode:(_Bool)arg3 currentTitleObjectFrameIndex:(int *)arg4 nextTitleObjectFrameIndex:(int *)arg5 frameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg6 okButtonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg7 popupWindowFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg8;

@end

