//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneGame.h"

@interface ISceneGame (TaikoCore)
- (void)pushSimpleDrawWithX:(float)arg1 y:(float)arg2 textureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3 frameIndex:(unsigned int)arg4 color:(unsigned int)arg5 flags:(unsigned int)arg6;
- (void)pushSimpleDrawShiftedWithX:(float)arg1 y:(float)arg2 tx:(float)arg3 ty:(float)arg4 textureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 frameIndex:(unsigned int)arg6 color:(unsigned int)arg7 flags:(unsigned int)arg8;
- (void)pushSimpleDrawScaledWithX:(float)arg1 y:(float)arg2 sx:(float)arg3 sy:(float)arg4 textureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 frameIndex:(unsigned int)arg6 color:(unsigned int)arg7 flags:(unsigned int)arg8;
- (void)pushSimpleDrawComplexWithX:(float)arg1 y:(float)arg2 sx:(float)arg3 sy:(float)arg4 tx:(float)arg5 ty:(float)arg6 textureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg7 frameIndex:(unsigned int)arg8 color:(unsigned int)arg9 flags:(unsigned int)arg10;
- (void)pushSimpleDrawBarWithX:(float)arg1 y:(float)arg2 textureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3 frameIndex:(unsigned int)arg4 color:(unsigned int)arg5 flags:(unsigned int)arg6;
- (void)renderLane;
- (void)renderOnpu:(const struct GameDrawInfo *)arg1 sx:(float)arg2 sy:(float)arg3 syousetsuWidth:(float)arg4;
- (_Bool)isTaikoCoreFinished;
- (void)HitResultCallBack:(const struct HitResultInfo *)arg1;
- (void)processTaikoCore:(float)arg1 LaneFlashType_p:(int *)arg2 isKanpeki_p:(_Bool *)arg3;
- (void)setTouchInfo;
- (void)destroyTaikoCore;
- (void)createTaikoCore:(id)arg1;
@end

