//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BGSceneBase.h"

#import "TaikoUpdateCheckerDelegate-Protocol.h"

@class TaikoButton, TaikoWindow, UIButton;

@interface ISceneOtanoshimiDialog : BGSceneBase <TaikoUpdateCheckerDelegate>
{
    int m_PauseState;	// 108 = 0x6c
    int m_PauseCounter;	// 112 = 0x70
    unsigned int m_OtanoshimiBackColor;	// 116 = 0x74
    _Bool m_RequestPageChange;	// 120 = 0x78
    UIButton *m_RequestPageChangeSender;	// 128 = 0x80
    UIButton *m_PushingSender;	// 136 = 0x88
    int m_SelectedIndex;	// 144 = 0x90
    struct _AGOBJECT m_OtanoshimiCloseObject;	// 152 = 0x98
    struct _AGOBJECT m_OtanoshimiDialogObject[4];	// 208 = 0xd0
    struct _AGOBJECT m_HeadObject;	// 432 = 0x1b0
    struct _AGOBJECT m_NewIconObject;	// 488 = 0x1e8
    TaikoWindow *m_OtanoshimiWindow;	// 544 = 0x220
    TaikoButton *m_OtanoshimiDialogButton[4];	// 552 = 0x228
    _Bool _isShowNewIcon;	// 584 = 0x248
}

@property(nonatomic) _Bool isShowNewIcon; // @synthesize isShowNewIcon=_isShowNewIcon;
- (void)updateChecker:(id)arg1 didFinishWithType:(unsigned int)arg2;
- (int)stateIdle;
- (int)stateCheckUpdate;
- (_Bool)isUserInteractionEnabled;
- (void)onTouchDownButton:(id)arg1;
- (void)onTouchUpOutsideButton:(id)arg1;
- (void)onTouchUpInsideButton:(id)arg1;
- (int)stateRoot;
- (void)resume;
- (void)render;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;
- (void)dealloc;
- (id)initWithManager:(id)arg1 tfgBackButton:(struct _AGTEXTUREFRAMEGROUP *)arg2 frameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3 dialogFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg4 dialogItemFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 tfgNewIcon:(struct _AGTEXTUREFRAMEGROUP *)arg6;

@end

