//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneBase.h"

#import "BGSNSInterfaceDelegate-Protocol.h"

@class NSString;

@interface ISceneNameEntry : ISceneBase <BGSNSInterfaceDelegate>
{
    struct _AGTEXTURE m_MainTexture;	// 72 = 0x48
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;	// 128 = 0x80
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;	// 152 = 0x98
    struct _AGTEXTUREFRAMEGROUP m_BigCharFrameGroup;	// 176 = 0xb0
    struct _AGTEXTUREFRAMEGROUP m_CharBoxFrameGroup;	// 200 = 0xc8
    struct _AGTEXTUREFRAMEGROUP m_RemoveButtonFrameGroup;	// 224 = 0xe0
    struct _AGTEXTUREFRAMEGROUP m_DecideButtonFrameGroup;	// 248 = 0xf8
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;	// 272 = 0x110
    struct _AGOBJECT m_BackObject;	// 296 = 0x128
    struct _AGOBJECT m_TitleObject;	// 352 = 0x160
    struct _AGOBJECT m_BigCharObject[87];	// 408 = 0x198
    struct _AGOBJECT m_CharBoxObject[5];	// 5280 = 0x14a0
    struct _AGOBJECT m_NameCharObject[5];	// 5560 = 0x15b8
    struct _AGOBJECT m_RemoveButtonObject;	// 5840 = 0x16d0
    struct _AGOBJECT m_DecideButtonObject;	// 5896 = 0x1708
    struct _AGOBJECT m_BackButtonObject;	// 5952 = 0x1740
    int m_CurrentChar;	// 6008 = 0x1778
    int m_NextScene;	// 6012 = 0x177c
    int m_FadeCounter;	// 6016 = 0x1780
}

- (int)stateWait;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)SNSInterfaceNumber:(unsigned long long)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3;
- (int)stateRun;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

