//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneBase.h"

#import "GKTaikoBattleDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class ISceneNamePlate, NSArray, NSMutableArray, NSString, UIActivityIndicatorView, UISwitch;

@interface ISceneVSSettings : ISceneBase <GKTaikoBattleDelegate, UIAlertViewDelegate>
{
    struct _AASAMPLE m_oSoundDonMake;	// 72 = 0x48
    struct _AASAMPLE m_oSoundDonFind;	// 96 = 0x60
    struct _AGTEXTURE m_MainTexture;	// 120 = 0x78
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;	// 176 = 0xb0
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;	// 200 = 0xc8
    struct _AGTEXTUREFRAMEGROUP m_BarFrameGroup;	// 224 = 0xe0
    struct _AGTEXTUREFRAMEGROUP m_MainBoardFrameGroup;	// 248 = 0xf8
    struct _AGTEXTUREFRAMEGROUP m_SubBoardFrameGroup;	// 272 = 0x110
    struct _AGTEXTUREFRAMEGROUP m_ExpandingBarGroup;	// 296 = 0x128
    struct _AGTEXTUREFRAMEGROUP m_ArrowGroup;	// 320 = 0x140
    struct _AGTEXTUREFRAMEGROUP m_NameFrameGroup;	// 344 = 0x158
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;	// 368 = 0x170
    struct _AGTEXTUREFRAMEGROUP m_TFGDon;	// 392 = 0x188
    struct _AGTEXTUREFRAMEGROUP m_TFGSpeechBubble;	// 416 = 0x1a0
    struct _AGTEXTUREFRAMEGROUP m_InviteMemberGroup;	// 440 = 0x1b8
    struct _AGTEXTUREFRAMEGROUP m_MemberNameFontGroup;	// 464 = 0x1d0
    struct _AGTEXTUREFRAMEGROUP m_ButtleSettingsGroup;	// 488 = 0x1e8
    struct _AGTEXTUREFRAMEGROUP m_RuleSwitchGroup;	// 512 = 0x200
    struct _AGTEXTUREFRAMEGROUP m_RatingGroup;	// 536 = 0x218
    struct _AGTEXTUREFRAMEGROUP m_CourseIconGroup;	// 560 = 0x230
    struct _AGTEXTUREFRAMEGROUP m_GameOptionGroup;	// 584 = 0x248
    struct _AGTEXTURE m_SongTexture;	// 608 = 0x260
    struct _AGTEXTUREFRAMEGROUP m_SongGroup;	// 664 = 0x298
    struct _AGTEXTUREFRAMEGROUP m_RoomSelectGroup;	// 688 = 0x2b0
    struct _AGTEXTUREFRAMEGROUP m_NumberFontGroup;	// 712 = 0x2c8
    struct _AGTEXTUREFRAMEGROUP m_ComNameGroup;	// 736 = 0x2e0
    struct _AGTEXTUREFRAMEGROUP m_ConnectErrorGroup;	// 760 = 0x2f8
    struct _AGOBJECT m_BackObject;	// 784 = 0x310
    struct _AGOBJECT m_TitleObject;	// 840 = 0x348
    struct _AGOBJECT m_BackButtonObject;	// 896 = 0x380
    struct _AGOBJECT m_BarObject[3];	// 952 = 0x3b8
    struct _AGOBJECT m_MainBoardObject[3];	// 1120 = 0x460
    struct _AGOBJECT m_SubBoardObject[3];	// 1288 = 0x508
    struct _AGOBJECT m_ExpandingBarObject[3];	// 1456 = 0x5b0
    struct _AGOBJECT m_ArrowObject[2];	// 1624 = 0x658
    struct _AGOBJECT m_DonObject;	// 1736 = 0x6c8
    struct _AGOBJECT m_SpeechBubbleObject[2];	// 1792 = 0x700
    struct _AGOBJECT m_InviteMemberObject[4];	// 1904 = 0x770
    struct _AGOBJECT m_MemberNameObject[4][5];	// 2128 = 0x850
    struct _AGOBJECT m_aroObjComName[3];	// 3248 = 0xcb0
    struct _AGOBJECT m_ButtleSettings_SongTitle;	// 3416 = 0xd58
    struct _AGOBJECT m_ButtleSettings_StartButtle;	// 3472 = 0xd90
    struct _AGOBJECT m_ButtleSettings_Words[4];	// 3528 = 0xdc8
    struct _AGOBJECT m_ButtleSettings_Rule[2];	// 3752 = 0xea8
    struct _AGOBJECT m_ButtleSettings_CourseIcon;	// 3864 = 0xf18
    struct _AGOBJECT m_ButtleSettings_Rating;	// 3920 = 0xf50
    struct _AGOBJECT m_ButtleSettings_PleaseWait;	// 3976 = 0xf88
    struct _AGOBJECT m_ButtleSettings_BackWaku[2];	// 4032 = 0xfc0
    struct _AGOBJECT m_ButtleSettings_Arrows[8];	// 4144 = 0x1030
    struct _AGOBJECT m_ButtleSettings_GameOption[2];	// 4592 = 0x11f0
    _Bool m_ButtleSettings_GameOptionEnabled;	// 4704 = 0x1260
    struct CGPoint m_aroArrowBasePos[8];	// 4712 = 0x1268
    struct _AGOBJECT m_RoomSelect_Words[2];	// 4840 = 0x12e8
    struct _AGOBJECT m_RoomSelect_Name[5];	// 4952 = 0x1358
    struct _AGOBJECT m_aroObjWindowConnectError[3];	// 5232 = 0x1470
    struct _AGOBJECT m_oObjTextConnectError;	// 5400 = 0x1518
    UISwitch *m_ItemEnabledSwitch;	// 5456 = 0x1550
    UISwitch *m_ItemComSwitch;	// 5464 = 0x1558
    UIActivityIndicatorView *m_pIndCommunication;	// 5472 = 0x1560
    int m_BarState[3];	// 5480 = 0x1568
    float m_BoardAnimationSpeed;	// 5492 = 0x1574
    float m_BoardMaxWidth;	// 5496 = 0x1578
    float m_BarSpace;	// 5500 = 0x157c
    float m_BarUpSpeed;	// 5504 = 0x1580
    float m_BarDownSpeed;	// 5508 = 0x1584
    float m_BarMaxPosition;	// 5512 = 0x1588
    float m_BarMinPosition;	// 5516 = 0x158c
    float m_BarSelectUpSpeed;	// 5520 = 0x1590
    float m_BarSelectDownSpeed;	// 5524 = 0x1594
    float m_BarStartPosition;	// 5528 = 0x1598
    float m_BarChoosePosition;	// 5532 = 0x159c
    float m_BarHideChoosePosition;	// 5536 = 0x15a0
    float m_MainBoardSize;	// 5540 = 0x15a4
    struct CGPoint m_MainBoardPosition;	// 5544 = 0x15a8
    float m_SubBoardSize;	// 5560 = 0x15b8
    struct CGPoint m_SubBoardPosition;	// 5568 = 0x15c0
    struct CGPoint m_ExpandingBarPosition;	// 5584 = 0x15d0
    float m_ExpandingBarSpace;	// 5600 = 0x15e0
    float m_ArrowMinPosition;	// 5604 = 0x15e4
    float m_ArrowMaxPosition;	// 5608 = 0x15e8
    int m_ArrowAnimationCounter;	// 5612 = 0x15ec
    int m_MainSelect;	// 5616 = 0x15f0
    int m_AnimationState;	// 5620 = 0x15f4
    int m_AnimationCounter;	// 5624 = 0x15f8
    int m_NextScene;	// 5628 = 0x15fc
    int m_FadeCounter;	// 5632 = 0x1600
    _Bool m_MainBoardFront;	// 5636 = 0x1604
    _Bool m_SubBoardFront;	// 5637 = 0x1605
    _Bool m_ShowInviteMember;	// 5638 = 0x1606
    _Bool m_ShowButtleSettings;	// 5639 = 0x1607
    _Bool m_ShowRoomSelect;	// 5640 = 0x1608
    int m_DonChanCounter;	// 5644 = 0x160c
    int m_SpeechBubbleCounter;	// 5648 = 0x1610
    float m_DonAppearDistance;	// 5652 = 0x1614
    float m_DonAppearAmount;	// 5656 = 0x1618
    float m_DonAppearIncrement;	// 5660 = 0x161c
    struct CGPoint m_RatingStarPos;	// 5664 = 0x1620
    float m_RatingStarSpace;	// 5680 = 0x1630
    struct CGPoint m_RoomSelect_NamePos;	// 5688 = 0x1638
    float m_RoomSelect_NameSpace;	// 5704 = 0x1648
    float m_ScrollSpeed;	// 5708 = 0x164c
    float m_ScrollStartPosition;	// 5712 = 0x1650
    float m_ScrollPosition;	// 5716 = 0x1654
    float m_MaxScrollPosition;	// 5720 = 0x1658
    struct CGPoint m_ScrollTouchPoint;	// 5728 = 0x1660
    struct CGRect m_ScrollAreaRect;	// 5744 = 0x1670
    _Bool m_ScrollEnabled;	// 5776 = 0x1690
    _Bool m_Scrolling;	// 5777 = 0x1691
    unsigned long long m_Member[4];	// 5784 = 0x1698
    int m_MemberLength[4];	// 5816 = 0x16b8
    int m_Rule;	// 5832 = 0x16c8
    _Bool m_useItem;	// 5836 = 0x16cc
    NSMutableArray *m_rooms;	// 5840 = 0x16d0
    NSMutableArray *m_members;	// 5848 = 0x16d8
    NSMutableArray *m_pArrMusicID;	// 5856 = 0x16e0
    NSString *m_songID;	// 5864 = 0x16e8
    int m_course;	// 5872 = 0x16f0
    unsigned int m_nSelectSongArr;	// 5876 = 0x16f4
    _Bool m_loadSongTexture;	// 5880 = 0x16f8
    _Bool m_isServer;	// 5881 = 0x16f9
    unsigned int m_nIndCount;	// 5884 = 0x16fc
    unsigned int m_nGrayOverColor;	// 5888 = 0x1700
    unsigned int m_nSendSettingCount;	// 5892 = 0x1704
    unsigned int m_nConnectWaitCount;	// 5896 = 0x1708
    unsigned int m_nWaitGameStartCount;	// 5900 = 0x170c
    unsigned int m_ObiColor;	// 5904 = 0x1710
    float m_fArrowDeltaPoint;	// 5908 = 0x1714
    _Bool m_nShowConnectError;	// 5912 = 0x1718
    _Bool m_nErrorAlert;	// 5913 = 0x1719
    _Bool m_nSettingBefore;	// 5914 = 0x171a
    ISceneNamePlate *m_SceneNamePlate;	// 5920 = 0x1720
    struct _AGTEXTUREFRAMEGROUP m_TaisenTextGroup;	// 5928 = 0x1728
    struct _AGTEXTUREFRAMEGROUP m_TaisenBackGroup;	// 5952 = 0x1740
    struct _AGTEXTUREFRAMEGROUP m_CourseIconFrameGroup;	// 5976 = 0x1758
    struct _AGOBJECT m_oObjTaisenCource;	// 6000 = 0x1770
    struct _AGOBJECT m_aroObjTaisenText[9];	// 6056 = 0x17a8
    struct _AGOBJECT m_aroObjTaisenBack[2];	// 6560 = 0x19a0
    struct _AGOBJECT m_aroObjTaisenTop[3];	// 6672 = 0x1a10
    struct _AGOBJECT m_aroObjTaisenBottom[4];	// 6840 = 0x1ab8
    struct _AGOBJECT m_NumObject[7];	// 7064 = 0x1b98
    struct _AGOBJECT m_RecordArrowObject[2];	// 7456 = 0x1d20
    unsigned int m_ararnTopCount[4][3];	// 7568 = 0x1d90
    unsigned int m_ararnTopPar[4][3];	// 7616 = 0x1dc0
    unsigned int m_ararnBottomCount[4][4];	// 7664 = 0x1df0
    unsigned int m_ararnBottomPar[4][4];	// 7728 = 0x1e30
    unsigned int m_nSelectCource;	// 7792 = 0x1e70
    unsigned int m_nBeforeCource;	// 7796 = 0x1e74
    float m_BoardScrollPosition;	// 7800 = 0x1e78
    int m_BoardScrollCounter;	// 7804 = 0x1e7c
    struct CGPoint m_StartTouchPoint;	// 7808 = 0x1e80
    _Bool m_TouchActive;	// 7824 = 0x1e90
    float m_ScoreCourseSpace;	// 7828 = 0x1e94
    float m_ArrowDeltaPosition;	// 7832 = 0x1e98
    _Bool m_ShowTaisen;	// 7836 = 0x1e9c
    NSArray *m_SongList;	// 7840 = 0x1ea0
}

- (void)didPresentAlertView:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)disconnectAllPeer;
- (void)recieveData:(id)arg1 Scene:(unsigned int)arg2 Order:(unsigned int)arg3 Arr:(unsigned int)arg4;
- (void)enableGameOption;
- (void)connectErrorProcess;
- (void)applicationWillResignActive;
- (int)stateAlert;
- (void)sendButtleSettingsWithSubmit:(_Bool)arg1;
- (void)enableCom;
- (void)enableItem;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (int)stateFadeInBefore;
- (int)stateSelectRoom;
- (int)stateButtleSettingsS;
- (int)stateButtleSettingsC;
- (int)stateInviteMemberS;
- (int)stateInviteMemberC;
- (int)stateAnimate;
- (int)stateTaisen;
- (int)stateMain;
- (void)updateAnimation;
- (void)render;
- (void)renderTaisenBoardAtPosition:(float)arg1 cource:(unsigned int)arg2;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

