//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISceneBase.h"

#import "UIScrollViewDelegate-Protocol.h"

@class HowtoScrollView, NSString;

@interface ISceneHowTo : ISceneBase <UIScrollViewDelegate>
{
    struct _AGTEXTURE m_MainTexture;	// 72 = 0x48
    struct _AGTEXTURE m_TextTexture[12];	// 128 = 0x80
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;	// 800 = 0x320
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;	// 824 = 0x338
    struct _AGTEXTUREFRAMEGROUP m_TextFrameGroup[12];	// 848 = 0x350
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;	// 1136 = 0x470
    struct _AGTEXTUREFRAMEGROUP m_LicenseButtonFrameGroup;	// 1160 = 0x488
    struct _AGOBJECT m_BackObject;	// 1184 = 0x4a0
    struct _AGOBJECT m_UpperBackObject;	// 1240 = 0x4d8
    struct _AGOBJECT m_LowerBackObject;	// 1296 = 0x510
    struct _AGOBJECT m_TitleObject;	// 1352 = 0x548
    struct _AGOBJECT m_ScrollBarObject;	// 1408 = 0x580
    struct _AGOBJECT m_BackButtonObject;	// 1464 = 0x5b8
    struct _AGOBJECT m_LicenseButtonObject;	// 1520 = 0x5f0
    struct CGPoint m_ScrollTouchPoint;	// 1576 = 0x628
    float m_ScrollSpeed;	// 1592 = 0x638
    float m_ScrollStartPosition;	// 1596 = 0x63c
    int m_NextScene;	// 1600 = 0x640
    float m_yOffset;	// 1604 = 0x644
    float m_yMax;	// 1608 = 0x648
    float m_MaxScrollPosition;	// 1612 = 0x64c
    float m_ScrollPosition;	// 1616 = 0x650
    float m_ScroolBarWidth;	// 1620 = 0x654
    float m_ScrollBarHeight;	// 1624 = 0x658
    float m_ScrollBarPosition;	// 1628 = 0x65c
    int m_FadeCounter;	// 1632 = 0x660
    _Bool m_Scrolling;	// 1636 = 0x664
    HowtoScrollView *m_ScrollView;	// 1640 = 0x668
    unsigned int m_nTextMax;	// 1648 = 0x670
}

- (int)stateRun;
- (void)scrollViewDidScroll:(id)arg1;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

