//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSValue.h>

@interface NSValue (Geometry)
+ (id)valueWithSize:(struct CGSize)arg1;
+ (id)valueWithPoint:(struct CGPoint)arg1;
+ (id)valueWithRect:(struct CGRect)arg1;
- (struct CGSize)sizeValue;
- (struct CGPoint)pointValue;
- (struct CGRect)rectValue;
@end

