//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface OARequestParameter : NSObject
{
    NSString *name;	// 8 = 0x8
    NSString *value;	// 16 = 0x10
}

+ (id)requestParameter:(id)arg1 value:(id)arg2;
@property(copy) NSString *value; // @synthesize value;
@property(copy) NSString *name; // @synthesize name;
- (_Bool)isEqualToRequestParameter:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)URLEncodedNameValuePair;
- (id)URLEncodedValue;
- (id)URLEncodedName;
- (void)dealloc;
- (id)initWithName:(id)arg1 value:(id)arg2;

@end

