//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary, NSOperationQueue;

@interface TaikoCache : NSObject
{
    unsigned long long maxEntry_;	// 8 = 0x8
    NSMutableArray *identifiers_;	// 16 = 0x10
    NSMutableDictionary *entries_;	// 24 = 0x18
    NSMutableArray *operationHistory_;	// 32 = 0x20
    NSMutableDictionary *operations_;	// 40 = 0x28
    NSOperationQueue *operationQueue_;	// 48 = 0x30
    CDUnknownBlockType creationBlock_;	// 56 = 0x38
    CDUnknownBlockType cancellingBlock_;	// 64 = 0x40
    _Bool terminated_;	// 72 = 0x48
}

- (void)purgeExceptSources:(id)arg1;
- (void)purge;
- (void)updateCacheWithEntry:(id)arg1;
- (id)entryOrNilWithSource:(id)arg1;
- (void)createEntryInOtherThreadWithSource:(id)arg1;
- (void)terminate;
- (void)dealloc;
- (id)initWithMaxEntry:(unsigned long long)arg1 create:(CDUnknownBlockType)arg2 cancel:(CDUnknownBlockType)arg3;
- (id)initWithMaxEntry:(unsigned long long)arg1 create:(CDUnknownBlockType)arg2;

@end

