//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BGDownload, NSData, NSError, NSString;

@interface TaikoPrizeImageInfo : NSObject
{
    BGDownload *_download;	// 8 = 0x8
    NSData *_data;	// 16 = 0x10
    NSError *_error;	// 24 = 0x18
    NSString *_cacheKey;	// 32 = 0x20
}

@property(copy, nonatomic) NSString *cacheKey; // @synthesize cacheKey=_cacheKey;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) BGDownload *download; // @synthesize download=_download;
- (void)purge;
- (void)removeCache;
- (void)dealloc;

@end

