//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UITouch;

@interface TaikoCoverView : UIView
{
    int _sceneLayer;	// 92 = 0x5c
    UITouch *_touch;	// 96 = 0x60
}

@property(nonatomic) int sceneLayer; // @synthesize sceneLayer=_sceneLayer;
@property(retain, nonatomic) UITouch *touch; // @synthesize touch=_touch;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;

@end

