//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class EAGLContext;

@interface TaikoRenderer : NSObject
{
    EAGLContext *context_;	// 8 = 0x8
    unsigned int programs_[3];	// 16 = 0x10
    unsigned int defaultFramebuffer_;	// 28 = 0x1c
    unsigned int colorRenderbuffer_;	// 32 = 0x20
    int uniforms_[3][2];	// 36 = 0x24
    int backingWidth_;	// 60 = 0x3c
    int backingHeight_;	// 64 = 0x40
    int frameWidth_;	// 68 = 0x44
    int frameHeight_;	// 72 = 0x48
    float contentScaleFactor_;	// 76 = 0x4c
    int currentShader_;	// 80 = 0x50
    int currentBlendMode_;	// 84 = 0x54
    _Bool postscaling_;	// 88 = 0x58
    unsigned int postscalingFramebuffer_;	// 92 = 0x5c
    unsigned int postscalingTexture_;	// 96 = 0x60
    struct _AGVERTEX postscalingVertices_[4];	// 100 = 0x64
    int backingWidthPostscaling_;	// 180 = 0xb4
    int backingHeightPostscaling_;	// 184 = 0xb8
    int frameWidthPostscaling_;	// 188 = 0xbc
    int frameHeightPostscaling_;	// 192 = 0xc0
    float _postscaleFactor;	// 196 = 0xc4
}

@property(nonatomic) float postscaleFactor; // @synthesize postscaleFactor=_postscaleFactor;
- (void)setBlendMode:(int)arg1;
- (void)setShader:(int)arg1;
- (void)display;
- (void)flush;
- (void)initState:(int)arg1 frameHeight:(int)arg2 screenWidth:(int)arg3 screenHeight:(int)arg4;
- (void)setViewport:(int)arg1 frameHeight:(int)arg2 screenWidth:(int)arg3 screenHeight:(int)arg4;
- (_Bool)resize:(id)arg1;
- (_Bool)validateProgram:(unsigned int)arg1;
- (_Bool)linkProgram:(unsigned int)arg1;
- (_Bool)compileShader:(unsigned int *)arg1 type:(unsigned int)arg2 count:(int)arg3 sourcePath:(id)arg4;
- (void)destroyShaders:(unsigned int *)arg1 fragShader:(unsigned int *)arg2 prog:(unsigned int *)arg3;
- (_Bool)loadShader:(int)arg1;
- (void)setContentScaleFactor:(float)arg1;
- (void)setFrameSize:(int)arg1 height:(int)arg2;
- (void)dealloc;
- (id)init;

@end

