//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TaikoAction : NSObject
{
    int type_;	// 8 = 0x8
    NSArray *frameIndices_;	// 16 = 0x10
    NSArray *keyFrames_;	// 24 = 0x18
    struct CGPoint destination_;	// 32 = 0x20
    unsigned long long targetValue_;	// 48 = 0x30
    float targetValueF_;	// 56 = 0x38
    unsigned long long duration_;	// 64 = 0x40
    unsigned long long count_;	// 72 = 0x48
    _Bool completed_;	// 80 = 0x50
}

+ (id)group:(id)arg1;
+ (id)repeatActionForever:(id)arg1;
+ (id)repeatAction:(id)arg1 count:(unsigned long long)arg2;
+ (id)sequence:(id)arg1;
+ (id)scaleYTo:(float)arg1 duration:(unsigned long long)arg2;
+ (id)scaleXTo:(float)arg1 duration:(unsigned long long)arg2;
+ (id)fadeAlphaTo:(unsigned long long)arg1 duration:(unsigned long long)arg2;
+ (id)moveTo:(struct CGPoint)arg1 duration:(unsigned long long)arg2;
+ (id)animateWithFrameIndices:(id)arg1 durations:(id)arg2;
+ (id)animateWithFrameIndices:(id)arg1 durationPerFrame:(unsigned long long)arg2;
+ (id)fadeOutWithDuration:(unsigned long long)arg1;
+ (id)fadeInWithDuration:(unsigned long long)arg1;
+ (id)waitForDuration:(unsigned long long)arg1;
@property(readonly, nonatomic) _Bool completed; // @synthesize completed=completed_;
@property(readonly, nonatomic) unsigned long long duration; // @synthesize duration=duration_;
- (void)rewind;
- (_Bool)updateAGObject:(struct _AGOBJECT *)arg1;
- (void)dealloc;

@end

