//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TaikoSceneNode.h"

@class UIButton, UIView;
@protocol TaikoButtonDelegate;

@interface TaikoButton : TaikoSceneNode
{
    UIButton *uibutton_;	// 80 = 0x50
    struct CGRect bounds_;	// 88 = 0x58
    int frameIndices_[3];	// 120 = 0x78
    _Bool originChanged_;	// 132 = 0x84
    _Bool _enabledEvenIfTransparent;	// 133 = 0x85
    id <TaikoButtonDelegate> _delegate;	// 136 = 0x88
}

@property(nonatomic) id <TaikoButtonDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool enabledEvenIfTransparent; // @synthesize enabledEvenIfTransparent=_enabledEvenIfTransparent;
- (_Bool)isComposedOfUIButton:(id)arg1;
- (void)sendActionsForControlEvents:(unsigned long long)arg1;
- (void)removeTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(unsigned long long)arg3;
- (void)addTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(unsigned long long)arg3;
- (void)update;
@property(nonatomic) _Bool selected;
@property(nonatomic) _Bool enabled;
@property(nonatomic) UIView *superview;
- (void)setBounds:(struct CGRect)arg1;
- (void)setOrigin:(struct CGPoint)arg1;
- (void)updateUIButtonCenter;
- (void)setFrameIndex:(int)arg1 forState:(int)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)changeFrameIndex;
- (void)dealloc;
- (id)initWithTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1 touchTransparent:(_Bool)arg2;
- (id)initWithTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1;

@end

