//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class TaikoCache;
@protocol TaikoCacheEntrySource;

@interface TaikoCacheOperation : NSOperation
{
    _Bool runnable_;	// 24 = 0x18
    TaikoCache *_cache;	// 32 = 0x20
    id <TaikoCacheEntrySource> _source;	// 40 = 0x28
    CDUnknownBlockType _creationBlock;	// 48 = 0x30
    CDUnknownBlockType _cancellingBlock;	// 56 = 0x38
}

@property(copy, nonatomic) CDUnknownBlockType cancellingBlock; // @synthesize cancellingBlock=_cancellingBlock;
@property(copy, nonatomic) CDUnknownBlockType creationBlock; // @synthesize creationBlock=_creationBlock;
@property(retain, nonatomic) id <TaikoCacheEntrySource> source; // @synthesize source=_source;
@property(nonatomic) TaikoCache *cache; // @synthesize cache=_cache;
- (void)stop;
- (void)main;
- (void)dealloc;
- (id)init;

@end

