//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BGDownloadDelegate-Protocol.h"
#import "NSCoding-Protocol.h"

@class NSMutableDictionary, NSString, TaikoPrizeImageInfo;

@interface TaikoPrize : NSObject <BGDownloadDelegate, NSCoding>
{
    NSMutableDictionary *dictionary_;	// 8 = 0x8
    TaikoPrizeImageInfo *images_[3];	// 16 = 0x10
    _Bool _new;	// 40 = 0x28
    _Bool _duplicate;	// 41 = 0x29
    _Bool _secret;	// 42 = 0x2a
    unsigned int _type;	// 44 = 0x2c
    int _refundBonuspoint;	// 48 = 0x30
    NSString *_identifier;	// 56 = 0x38
    NSString *_expireDate;	// 64 = 0x40
}

@property(readonly, nonatomic, getter=isSecret) _Bool secret; // @synthesize secret=_secret;
@property(readonly, nonatomic) NSString *expireDate; // @synthesize expireDate=_expireDate;
@property(readonly, nonatomic) int refundBonuspoint; // @synthesize refundBonuspoint=_refundBonuspoint;
@property(readonly, nonatomic, getter=isDuplicate) _Bool duplicate; // @synthesize duplicate=_duplicate;
@property(readonly, nonatomic, getter=isNew) _Bool new; // @synthesize new=_new;
@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (void)removeCacheWithType:(unsigned int)arg1;
- (void)purgeImageDataWithType:(unsigned int)arg1;
- (id)imageDataWithType:(unsigned int)arg1 error:(id *)arg2;
- (id)imageURLStringWithType:(unsigned int)arg1;
- (void)setup;
- (id)initWithDictionary:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

