//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class AgreementManager, ModalViewController;

@interface TOSBaseDlg : UIViewController
{
    ModalViewController *modalctrl;	// 320 = 0x140
    TOSBaseDlg *returndlg;	// 328 = 0x148
    CDStruct_08b27754 *dlglayout;	// 336 = 0x150
    AgreementManager *agmanager;	// 344 = 0x158
}

- (void)setViewController:(id)arg1 ReturnDlg:(id)arg2;
- (void)setViewController:(id)arg1;
- (id)initWithManager:(id)arg1;
- (void)loadLayout:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

