//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURLConnection, TwitterAccessToken;

@interface TwitterXAuth : NSObject
{
    id m_delegate;	// 8 = 0x8
    NSString *m_consumerKey;	// 16 = 0x10
    NSString *m_consumerSecret;	// 24 = 0x18
    NSString *m_userName;	// 32 = 0x20
    NSString *m_userPassword;	// 40 = 0x28
    NSString *m_requestToken;	// 48 = 0x30
    NSString *m_requestSecret;	// 56 = 0x38
    NSString *m_authURL;	// 64 = 0x40
    NSURLConnection *m_urlConnection;	// 72 = 0x48
    int m_resStatus;	// 80 = 0x50
    TwitterAccessToken *m_accessToken;	// 88 = 0x58
}

- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)requestAccessToken;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)initWithKey:(id)arg1 Secret:(id)arg2 Name:(id)arg3 Password:(id)arg4;

@end

