//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXBitMatrix, ZXDataMatrixVersion;

@interface ZXDataMatrixBitMatrixParser : NSObject
{
    ZXDataMatrixVersion *_version;	// 8 = 0x8
    ZXBitMatrix *_mappingBitMatrix;	// 16 = 0x10
    ZXBitMatrix *_readMappingMatrix;	// 24 = 0x18
}

@property(retain, nonatomic) ZXBitMatrix *readMappingMatrix; // @synthesize readMappingMatrix=_readMappingMatrix;
@property(retain, nonatomic) ZXBitMatrix *mappingBitMatrix; // @synthesize mappingBitMatrix=_mappingBitMatrix;
@property(readonly, nonatomic) ZXDataMatrixVersion *version; // @synthesize version=_version;
- (void).cxx_destruct;
- (id)extractDataRegion:(id)arg1;
- (int)readCorner4:(int)arg1 numColumns:(int)arg2;
- (int)readCorner3:(int)arg1 numColumns:(int)arg2;
- (int)readCorner2:(int)arg1 numColumns:(int)arg2;
- (int)readCorner1:(int)arg1 numColumns:(int)arg2;
- (int)readUtah:(int)arg1 column:(int)arg2 numRows:(int)arg3 numColumns:(int)arg4;
- (_Bool)readModule:(int)arg1 column:(int)arg2 numRows:(int)arg3 numColumns:(int)arg4;
- (id)readCodewords;
- (id)readVersion:(id)arg1;
- (id)initWithBitMatrix:(id)arg1 error:(id *)arg2;

@end

