//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXReedSolomonDecoder;

@interface ZXDataMatrixDecoder : NSObject
{
    ZXReedSolomonDecoder *_rsDecoder;	// 8 = 0x8
}

@property(retain, nonatomic) ZXReedSolomonDecoder *rsDecoder; // @synthesize rsDecoder=_rsDecoder;
- (void).cxx_destruct;
- (_Bool)correctErrors:(id)arg1 numDataCodewords:(int)arg2 error:(id *)arg3;
- (id)decodeMatrix:(id)arg1 error:(id *)arg2;
- (id)decode:(_Bool **)arg1 length:(unsigned int)arg2 error:(id *)arg3;
- (id)init;

@end

