//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSMutableArray;
@protocol ZXResultPointCallback;

@interface ZXDecodeHints : NSObject <NSCopying>
{
    _Bool _assumeCode39CheckDigit;	// 8 = 0x8
    _Bool _assumeGS1;	// 9 = 0x9
    _Bool _pureBarcode;	// 10 = 0xa
    _Bool _tryHarder;	// 11 = 0xb
    NSArray *_allowedLengths;	// 16 = 0x10
    unsigned long long _encoding;	// 24 = 0x18
    id _other;	// 32 = 0x20
    id <ZXResultPointCallback> _resultPointCallback;	// 40 = 0x28
    NSMutableArray *_barcodeFormats;	// 48 = 0x30
}

+ (id)hints;
@property(retain, nonatomic) NSMutableArray *barcodeFormats; // @synthesize barcodeFormats=_barcodeFormats;
@property(nonatomic) _Bool tryHarder; // @synthesize tryHarder=_tryHarder;
@property(retain, nonatomic) id <ZXResultPointCallback> resultPointCallback; // @synthesize resultPointCallback=_resultPointCallback;
@property(nonatomic) _Bool pureBarcode; // @synthesize pureBarcode=_pureBarcode;
@property(retain, nonatomic) id other; // @synthesize other=_other;
@property(nonatomic) unsigned long long encoding; // @synthesize encoding=_encoding;
@property(retain, nonatomic) NSArray *allowedLengths; // @synthesize allowedLengths=_allowedLengths;
@property(nonatomic) _Bool assumeGS1; // @synthesize assumeGS1=_assumeGS1;
@property(nonatomic) _Bool assumeCode39CheckDigit; // @synthesize assumeCode39CheckDigit=_assumeCode39CheckDigit;
- (void).cxx_destruct;
- (void)removePossibleFormat:(int)arg1;
- (int)numberOfPossibleFormats;
- (_Bool)containsFormat:(int)arg1;
- (void)addPossibleFormat:(int)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

