//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXECI : NSObject
{
    int _value;	// 8 = 0x8
}

+ (id)eciByValue:(int)arg1;
@property(readonly, nonatomic) int value; // @synthesize value=_value;
- (id)initWithValue:(int)arg1;

@end

