//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXQRCodeFinderPattern;

@interface ZXFinderPatternInfo : NSObject
{
    ZXQRCodeFinderPattern *_bottomLeft;	// 8 = 0x8
    ZXQRCodeFinderPattern *_topLeft;	// 16 = 0x10
    ZXQRCodeFinderPattern *_topRight;	// 24 = 0x18
}

@property(readonly, nonatomic) ZXQRCodeFinderPattern *topRight; // @synthesize topRight=_topRight;
@property(readonly, nonatomic) ZXQRCodeFinderPattern *topLeft; // @synthesize topLeft=_topLeft;
@property(readonly, nonatomic) ZXQRCodeFinderPattern *bottomLeft; // @synthesize bottomLeft=_bottomLeft;
- (void).cxx_destruct;
- (id)initWithPatternCenters:(id)arg1;

@end

