//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXMaskUtil : NSObject
{
}

+ (int)applyMaskPenaltyRule1Internal:(id)arg1 isHorizontal:(_Bool)arg2;
+ (_Bool)dataMaskBit:(int)arg1 x:(int)arg2 y:(int)arg3;
+ (int)applyMaskPenaltyRule4:(id)arg1;
+ (int)applyMaskPenaltyRule3:(id)arg1;
+ (int)applyMaskPenaltyRule2:(id)arg1;
+ (int)applyMaskPenaltyRule1:(id)arg1;

@end

