//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXByteMatrix, ZXErrorCorrectionLevel, ZXMode, ZXQRCodeVersion;

@interface ZXQRCode : NSObject
{
    int _maskPattern;	// 8 = 0x8
    ZXMode *_mode;	// 16 = 0x10
    ZXErrorCorrectionLevel *_ecLevel;	// 24 = 0x18
    ZXQRCodeVersion *_version;	// 32 = 0x20
    ZXByteMatrix *_matrix;	// 40 = 0x28
}

+ (_Bool)isValidMaskPattern:(int)arg1;
@property(retain, nonatomic) ZXByteMatrix *matrix; // @synthesize matrix=_matrix;
@property(nonatomic) int maskPattern; // @synthesize maskPattern=_maskPattern;
@property(retain, nonatomic) ZXQRCodeVersion *version; // @synthesize version=_version;
@property(retain, nonatomic) ZXErrorCorrectionLevel *ecLevel; // @synthesize ecLevel=_ecLevel;
@property(retain, nonatomic) ZXMode *mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

