//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXQRCodeDecodedBitStreamParser : NSObject
{
}

+ (int)parseECIValue:(id)arg1;
+ (_Bool)decodeNumericSegment:(id)arg1 result:(id)arg2 count:(int)arg3;
+ (_Bool)decodeAlphanumericSegment:(id)arg1 result:(id)arg2 count:(int)arg3 fc1InEffect:(_Bool)arg4;
+ (unsigned short)toAlphaNumericChar:(int)arg1;
+ (_Bool)decodeByteSegment:(id)arg1 result:(id)arg2 count:(int)arg3 currentCharacterSetECI:(id)arg4 byteSegments:(id)arg5 hints:(id)arg6;
+ (_Bool)decodeKanjiSegment:(id)arg1 result:(id)arg2 count:(int)arg3;
+ (_Bool)decodeHanziSegment:(id)arg1 result:(id)arg2 count:(int)arg3;
+ (id)decode:(char *)arg1 length:(unsigned int)arg2 version:(id)arg3 ecLevel:(id)arg4 hints:(id)arg5 error:(id *)arg6;

@end

