//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZXLuminanceSource.h"

@interface ZXRGBLuminanceSource : ZXLuminanceSource
{
    int _luminancesCount;	// 8 = 0x8
    int _dataWidth;	// 12 = 0xc
    int _dataHeight;	// 16 = 0x10
    int _left;	// 20 = 0x14
    int _top;	// 24 = 0x18
    char *_luminances;	// 32 = 0x20
}

@property(nonatomic) int top; // @synthesize top=_top;
@property(nonatomic) int left; // @synthesize left=_left;
@property(nonatomic) int dataHeight; // @synthesize dataHeight=_dataHeight;
@property(nonatomic) int dataWidth; // @synthesize dataWidth=_dataWidth;
@property(nonatomic) int luminancesCount; // @synthesize luminancesCount=_luminancesCount;
@property(nonatomic) char *luminances; // @synthesize luminances=_luminances;
- (id)crop:(int)arg1 top:(int)arg2 width:(int)arg3 height:(int)arg4;
- (_Bool)cropSupported;
- (char *)matrix;
- (char *)row:(int)arg1;
- (id)initWithPixels:(char *)arg1 pixelsLen:(int)arg2 dataWidth:(int)arg3 dataHeight:(int)arg4 left:(int)arg5 top:(int)arg6 width:(int)arg7 height:(int)arg8;
- (id)initWithWidth:(int)arg1 height:(int)arg2 pixels:(int *)arg3 pixelsLen:(int)arg4;

@end

