//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXRSSUtils : NSObject
{
}

+ (id)elements:(id)arg1 N:(int)arg2 K:(int)arg3;
+ (int)combins:(int)arg1 r:(int)arg2;
+ (int)rssValue:(int *)arg1 widthsLen:(unsigned int)arg2 maxWidth:(int)arg3 noNarrow:(_Bool)arg4;
+ (id)rssWidths:(int)arg1 n:(int)arg2 elements:(int)arg3 maxWidth:(int)arg4 noNarrow:(_Bool)arg5;

@end

