//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface ZXRSSFinderPattern : NSObject
{
    int _value;	// 8 = 0x8
    NSMutableArray *_startEnd;	// 16 = 0x10
    NSMutableArray *_resultPoints;	// 24 = 0x18
}

@property(readonly, nonatomic) NSMutableArray *resultPoints; // @synthesize resultPoints=_resultPoints;
@property(readonly, nonatomic) NSMutableArray *startEnd; // @synthesize startEnd=_startEnd;
@property(readonly, nonatomic) int value; // @synthesize value=_value;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithValue:(int)arg1 startEnd:(id)arg2 start:(int)arg3 end:(int)arg4 rowNumber:(int)arg5;

@end

