//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZXSymbolInfo : NSObject
{
    _Bool _rectangular;	// 8 = 0x8
    int _errorCodewords;	// 12 = 0xc
    int _dataCapacity;	// 16 = 0x10
    int _dataRegions;	// 20 = 0x14
    int _matrixWidth;	// 24 = 0x18
    int _matrixHeight;	// 28 = 0x1c
    int _rsBlockData;	// 32 = 0x20
    int _rsBlockError;	// 36 = 0x24
}

+ (id)lookup:(int)arg1 shape:(id)arg2 minSize:(id)arg3 maxSize:(id)arg4 fail:(_Bool)arg5;
+ (id)lookup:(int)arg1 shape:(id)arg2 fail:(_Bool)arg3;
+ (id)lookup:(int)arg1 allowRectangular:(_Bool)arg2 fail:(_Bool)arg3;
+ (id)lookup:(int)arg1 shape:(id)arg2;
+ (id)lookup:(int)arg1;
+ (void)overrideSymbolSet:(id)arg1;
+ (id)prodSymbols;
+ (void)initialize;
@property(nonatomic) int rsBlockError; // @synthesize rsBlockError=_rsBlockError;
@property(nonatomic) int rsBlockData; // @synthesize rsBlockData=_rsBlockData;
@property(nonatomic) int matrixHeight; // @synthesize matrixHeight=_matrixHeight;
@property(nonatomic) int matrixWidth; // @synthesize matrixWidth=_matrixWidth;
@property(nonatomic) int dataRegions; // @synthesize dataRegions=_dataRegions;
@property(nonatomic) int dataCapacity; // @synthesize dataCapacity=_dataCapacity;
@property(nonatomic) int errorCodewords; // @synthesize errorCodewords=_errorCodewords;
@property(nonatomic) _Bool rectangular; // @synthesize rectangular=_rectangular;
- (id)description;
- (int)errorLengthForInterleavedBlock:(int)arg1;
- (int)dataLengthForInterleavedBlock:(int)arg1;
- (int)interleavedBlockCount;
- (int)codewordCount;
- (int)symbolHeight;
- (int)symbolWidth;
- (int)symbolDataHeight;
- (int)symbolDataWidth;
- (int)verticalDataRegions;
- (int)horizontalDataRegions;
- (id)initWithRectangular:(_Bool)arg1 dataCapacity:(int)arg2 errorCodewords:(int)arg3 matrixWidth:(int)arg4 matrixHeight:(int)arg5 dataRegions:(int)arg6 rsBlockData:(int)arg7 rsBlockError:(int)arg8;
- (id)initWithRectangular:(_Bool)arg1 dataCapacity:(int)arg2 errorCodewords:(int)arg3 matrixWidth:(int)arg4 matrixHeight:(int)arg5 dataRegions:(int)arg6;

@end

