//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ZXUPCEANExtension2Support, ZXUPCEANExtension5Support;

@interface ZXUPCEANExtensionSupport : NSObject
{
    ZXUPCEANExtension2Support *_twoSupport;	// 8 = 0x8
    ZXUPCEANExtension5Support *_fiveSupport;	// 16 = 0x10
}

@property(retain, nonatomic) ZXUPCEANExtension5Support *fiveSupport; // @synthesize fiveSupport=_fiveSupport;
@property(retain, nonatomic) ZXUPCEANExtension2Support *twoSupport; // @synthesize twoSupport=_twoSupport;
- (void).cxx_destruct;
- (id)decodeRow:(int)arg1 row:(id)arg2 rowOffset:(int)arg3 error:(id *)arg4;
- (id)init;

@end

