//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CollaboInfo, ISceneSongSelect, ISongInfo;

@interface BoxInfo : NSObject
{
    unsigned int _type;
    ISongInfo *_songInfo;
    CollaboInfo *_collaboInfo;
    ISceneSongSelect *_delegate;
}

@property(nonatomic) ISceneSongSelect *delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CollaboInfo *collaboInfo; // @synthesize collaboInfo=_collaboInfo;
@property(retain, nonatomic) ISongInfo *songInfo; // @synthesize songInfo=_songInfo;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
- (void)render:(struct CGPoint *)arg1 boxIndex:(int)arg2;
- (int)getWidth;
- (void)dealloc;

@end

