//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@protocol GKTaikoBattleDelegate <NSObject>
- (void)disconnectAllPeer;
- (void)recieveData:(NSData *)arg1 Scene:(unsigned long)arg2 Order:(unsigned long)arg3 Arr:(unsigned long)arg4;
@end

