//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IRoomInfoForVSSettings : NSObject
{
    NSString *m_peerID;
    NSString *m_strRoomMaster;
    unsigned long long m_intRoomMaster;
    int m_roomMasterLength;
    int m_memberCount;
}

@property(nonatomic) int memberCount; // @synthesize memberCount=m_memberCount;
@property(nonatomic) int roomMasterLength; // @synthesize roomMasterLength=m_roomMasterLength;
@property(nonatomic) unsigned long long intRoomMaster; // @synthesize intRoomMaster=m_intRoomMaster;
@property(retain, nonatomic) NSString *strRoomMaster; // @synthesize strRoomMaster=m_strRoomMaster;
@property(retain, nonatomic) NSString *peerID; // @synthesize peerID=m_peerID;
- (void)dealloc;
- (id)init;

@end

