//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneDialog.h"

@class NSDictionary, TaikoLoginBonusItem, TaikoNumberLabel, TaikoPrizeManager, TaikoSceneNode, TaikoTextureCache;

@interface ISceneLoginBonusDialog : ISceneDialog
{
    TaikoSceneNode *todaysGetNode_;
    TaikoSceneNode *tomorrowTextNode_;
    TaikoSceneNode *tomorrowGetNode_;
    TaikoSceneNode *specialTextNode_;
    TaikoNumberLabel *daysNode_;
    TaikoSceneNode *specialGetNode_;
    TaikoSceneNode *footerNode_;
    TaikoLoginBonusItem *startupItem_;
    TaikoLoginBonusItem *todaysItem_;
    TaikoLoginBonusItem *tomorrowItem_;
    TaikoLoginBonusItem *specialItem_;
    TaikoLoginBonusItem *firstItem_;
    TaikoTextureCache *textureCache_;
    BOOL todaysItemSetup_;
    BOOL tomorrowItemSetup_;
    BOOL specialItemSetup_;
    BOOL tomorrowItemExists_;
    BOOL specialItemExists_;
    int numberOfStarts_;
    BOOL _startupBonus;
    TaikoPrizeManager *_prizeManager;
    NSDictionary *_responseDictionary;
    int _totalLogin;
}

@property(readonly, nonatomic) int totalLogin; // @synthesize totalLogin=_totalLogin;
@property(readonly, nonatomic) BOOL startupBonus; // @synthesize startupBonus=_startupBonus;
@property(copy, nonatomic) NSDictionary *responseDictionary; // @synthesize responseDictionary=_responseDictionary;
@property(nonatomic) TaikoPrizeManager *prizeManager; // @synthesize prizeManager=_prizeManager;
- (BOOL)prepare;
- (BOOL)setupItems;
- (void)setupNormalDialog;
- (void)setupItem:(id)arg1 dictionary:(id)arg2;
- (void)setupStartupBonusDialog;
- (BOOL)setupSpecialItem;
- (BOOL)setupTomorrowItem;
- (BOOL)setupTodaysItem;
- (void)start;
- (void)clearFlags;
- (void)reset;
- (id)initWithManager:(id)arg1 windowFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg2 messageFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3 buttonFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg4 choiceFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 digitFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg6 miscFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg7 itemPlateFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg8 itemNameFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg9;
- (void)dealloc;

@end

