//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BGSceneBase.h"

@class BGSceneObject;

@interface ISceneOptionButton : BGSceneBase
{
    BGSceneObject *buttonObject_;
    BOOL appearing_;
    BOOL hidden_;
}

@property(nonatomic) BOOL hidden; // @synthesize hidden=hidden_;
- (BOOL)isPressed:(struct CGPoint)arg1;
- (void)appear:(BOOL)arg1;
- (int)stateRun;
- (void)sceneStart;
- (void)render;
- (int)update;
- (void)sceneDestroy;
- (void)sceneLoad;
- (id)initWithManager:(id)arg1 frameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg2;

@end

