//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "BGSNSInterfaceDelegate.h"
#import "TaikoUpdateCheckerDelegate.h"
#import "UIAlertViewDelegate.h"

@class ISceneBonuspoint, ISceneNamePlate, LumenManager, TaikoPrize;

@interface ISceneFukubiki : ISceneBase <TaikoUpdateCheckerDelegate, BGSNSInterfaceDelegate, UIAlertViewDelegate>
{
    int m_NextScene;
    int m_FadeCounter;
    TaikoPrize *prize_;
    int fukubikiCost_;
    struct _AGTEXTURE mainTexture_;
    struct _AGTEXTUREFRAMEGROUP backButtonFrameGroup_;
    struct _AGOBJECT backButtonObject_;
    struct _AGTEXTUREFRAMEGROUP tfgPrizeListButton_;
    struct _AGOBJECT prizeListButtonObject_;
    struct _AGTEXTUREFRAMEGROUP tfgLumen_;
    struct _AGTEXTUREFRAMEGROUP tfgButton_;
    struct _AGTEXTUREFRAMEGROUP tfgBonuspointPlate_;
    struct _AGTEXTUREFRAMEGROUP tfgBonuspointDigit_;
    ISceneBonuspoint *sceneBonuspoint_;
    ISceneNamePlate *sceneNamePlate_;
    LumenManager *lumenManager_;
    void *lumenPlayer_;
    BOOL isGettingCost_;
    BOOL isGotoPriseList_;
}

- (void)updateChecker:(id)arg1 didFinishWithType:(unsigned int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFailWithError:(id)arg2 object:(id)arg3;
- (void)SNSInterfaceNumber:(unsigned int)arg1 didFinishWithCode:(id)arg2 entry:(id)arg3 object:(id)arg4;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (int)stateGetCost;
- (int)stateResult;
- (int)stateCheckUpdate;
- (int)stateWait;
- (int)stateRun;
- (void)goBackToMenu;
- (void)render;
- (void)updateAnimation;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

@end

