//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

@class UIProgressView;

@interface ISceneLoad : ISceneBase
{
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTUREFRAMEGROUP m_TFGBack;
    struct _AGOBJECT m_BackObject;
    int m_State;
    int m_Counter;
    UIProgressView *m_ProgressView;
}

- (int)stateRun;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

@end

