//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ISceneManager;

@interface ISceneBase : NSObject
{
    ISceneManager *m_Manager;
    SEL m_UpdateRoutine;
    unsigned long m_TouchState;
    struct CGPoint m_TouchPoint;
    BOOL m_FaderMode;
    unsigned long m_FaderColor;
    unsigned long m_FaderDuration;
    unsigned long m_FaderCount;
    unsigned int m_BgTask;
    int nestCount_;
    int beginCount_;
    int endCount_;
    int _layer;
}

@property(nonatomic) int layer; // @synthesize layer=_layer;
@property(readonly, nonatomic) ISceneManager *manager; // @synthesize manager=m_Manager;
- (void)renderBackgroundObject:(struct _AGOBJECT *)arg1 x:(float)arg2 y:(float)arg3;
- (void)renderBackgroundObject:(struct _AGOBJECT *)arg1;
- (BOOL)checkTaikoControllerDisconnectionWithDelegate:(id)arg1 tag:(int)arg2;
- (void)scenePause;
- (void)restoreTransactionsFailedWithError:(id)arg1;
- (void)restoreTransactionsCompleted;
- (void)transactionFailedWithTransaction:(id)arg1;
- (BOOL)transactionCompletedWithTransaction:(id)arg1;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive;
- (BOOL)backgroundTaskInvalid;
- (void)endBackgroundTask;
- (void)endBackgroundTaskImmediately:(BOOL)arg1;
- (void)beginBackgroundTask;
- (void)touchesUpdated;
- (int)update;
- (void)updateInput;
- (BOOL)isFaderFinished;
- (void)fadeOut;
- (void)fadeIn;
- (void)startFaderInMode:(BOOL)arg1 color:(unsigned long)arg2 duration:(unsigned long)arg3;
- (void)updateFader;
- (void)takeBackgroundTaskConsistency;
- (void)dealloc;
- (id)initWithManager:(id)arg1;

@end

