//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISceneBase.h"

#import "UIScrollViewDelegate.h"

@class HowtoScrollView;

@interface ISceneHowTo : ISceneBase <UIScrollViewDelegate>
{
    struct _AGTEXTURE m_MainTexture;
    struct _AGTEXTURE m_TextTexture[11];
    struct _AGTEXTUREFRAMEGROUP m_BackFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TitleFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_TextFrameGroup[11];
    struct _AGTEXTUREFRAMEGROUP m_BackButtonFrameGroup;
    struct _AGTEXTUREFRAMEGROUP m_LicenseButtonFrameGroup;
    struct _AGOBJECT m_BackObject;
    struct _AGOBJECT m_UpperBackObject;
    struct _AGOBJECT m_LowerBackObject;
    struct _AGOBJECT m_TitleObject;
    struct _AGOBJECT m_ScrollBarObject;
    struct _AGOBJECT m_BackButtonObject;
    struct _AGOBJECT m_LicenseButtonObject;
    struct CGPoint m_ScrollTouchPoint;
    float m_ScrollSpeed;
    float m_ScrollStartPosition;
    int m_NextScene;
    float m_yOffset;
    float m_yMax;
    float m_MaxScrollPosition;
    float m_ScrollPosition;
    float m_ScroolBarWidth;
    float m_ScrollBarHeight;
    float m_ScrollBarPosition;
    int m_FadeCounter;
    BOOL m_Scrolling;
    HowtoScrollView *m_ScrollView;
    unsigned long m_nTextMax;
}

- (int)stateRun;
- (void)scrollViewDidScroll:(id)arg1;
- (int)stateFadeOut;
- (int)stateFadeIn;
- (void)render;
- (int)update;
- (void)sceneStart;
- (void)sceneDestroy;
- (void)sceneLoad;

@end

