//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PlayerUserData : NSObject
{
    struct _AGOBJECT *objectArray;
    struct _AASAMPLE *sampleArray;
    int sampleNum;
    int bgmIndex;
    NSString *_lmName;
    NSString *_bgmResourceName;
}

@property(copy, nonatomic) NSString *bgmResourceName; // @synthesize bgmResourceName=_bgmResourceName;
@property(copy, nonatomic) NSString *lmName; // @synthesize lmName=_lmName;
- (void)dealloc;

@end

