//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TaikoButton.h"

#import "TaikoButtonDelegate.h"

@class NSArray, TaikoAction;

@interface SongCoursePlate : TaikoButton <TaikoButtonDelegate>
{
    struct _AGOBJECT objects_[4];
    struct _AGOBJECT starObject_;
    unsigned int difficulty_;
    unsigned int achievements_;
    BOOL hasBranch_;
    TaikoAction *difficultyAction_;
    TaikoAction *starAction_;
    int iconFrameIndexBase_;
    NSArray *_overlays;
}

@property(retain, nonatomic) NSArray *overlays; // @synthesize overlays=_overlays;
- (void)taikoButton:(id)arg1 frameIndexDidChange:(int)arg2;
- (void)render;
- (void)update;
- (void)setAlpha:(unsigned int)arg1;
- (void)setAlphaInternal:(unsigned int)arg1;
- (void)setHidden:(BOOL)arg1;
- (void)setOrigin:(struct CGPoint)arg1;
- (void)configureWithCourseIndex:(unsigned int)arg1 achievements:(unsigned int)arg2 difficulty:(unsigned int)arg3 hasBranch:(BOOL)arg4;
- (void)hideCrown;
- (void)dealloc;
- (id)initWithButtonTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1 iconTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg2 titleTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg3 crownTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg4 difficultyTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg5 starTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg6;

@end

