//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TaikoKeychain : NSObject
{
}

+ (id)allAttributesOfService:(id)arg1 group:(id)arg2;
+ (id)objectForAccount:(id)arg1 service:(id)arg2 group:(id)arg3;
+ (BOOL)removeObjectForAccount:(id)arg1 service:(id)arg2 group:(id)arg3;
+ (BOOL)setObject:(id)arg1 forAccount:(id)arg2 service:(id)arg3 group:(id)arg4;
+ (id)allAttributesOfService:(id)arg1;
+ (id)objectForAccount:(id)arg1 service:(id)arg2;
+ (BOOL)removeObjectForAccount:(id)arg1 service:(id)arg2;
+ (BOOL)setObject:(id)arg1 forAccount:(id)arg2 service:(id)arg3;

@end

