//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"

@class AVAudioPlayer;

@interface TaikoAudioPlayer : NSObject <AVAudioPlayerDelegate>
{
    AVAudioPlayer *player_;
    id <AVAudioPlayerDelegate> delegate_;
    int numberOfArbitraryTimeLoops_;
    double loopStartTime_;
}

- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(BOOL)arg2;
- (void)stop;
- (BOOL)prepareToPlay;
- (BOOL)play;
@property double loopStartTime;
@property double currentTime;
@property int numberOfLoops;
@property float volume;
@property id <AVAudioPlayerDelegate> delegate;
@property(readonly, getter=isPlaying) BOOL playing;
- (void)dealloc;
- (id)initWithData:(id)arg1 error:(id *)arg2;

@end

