//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSMutableSet, NSString;

@interface TaikoEquipmentManager : NSObject
{
    NSString *documentsDirectory_;
    NSArray *rootDirecotries_;
    NSMutableDictionary *newEquipments_;
    NSMutableSet *newEquipmentFlags_;
    NSArray *_themes;
    NSArray *_taikos;
    NSArray *_costumes;
    NSArray *_tones;
}

@property(readonly, nonatomic) NSArray *tones; // @synthesize tones=_tones;
@property(readonly, nonatomic) NSArray *costumes; // @synthesize costumes=_costumes;
@property(readonly, nonatomic) NSArray *taikos; // @synthesize taikos=_taikos;
@property(readonly, nonatomic) NSArray *themes; // @synthesize themes=_themes;
- (id)addToneData:(id)arg1 forIdentifier:(id)arg2 error:(id *)arg3;
- (BOOL)hasSavedTone;
- (void)setCurrentTone:(id)arg1;
- (id)currentTone;
- (id)toneWithIdentifier:(id)arg1;
- (id)defaultTone;
- (void)loadTones:(id)arg1;
- (id)addCostumeData:(id)arg1 forIdentifier:(id)arg2 error:(id *)arg3;
- (BOOL)hasSavedCostume;
- (void)setCurrentCostume:(id)arg1;
- (id)currentCostume;
- (id)costumeWithIdentifier:(id)arg1;
- (id)defaultCostume;
- (void)loadCostumes:(id)arg1;
- (id)addTaikoData:(id)arg1 forIdentifier:(id)arg2 error:(id *)arg3;
- (BOOL)hasSavedTaiko;
- (void)setCurrentTaiko:(id)arg1;
- (id)currentTaiko;
- (id)taikoWithIdentifier:(id)arg1;
- (id)defaultTaiko;
- (void)loadTaikos:(id)arg1;
- (id)addThemeData:(id)arg1 forIdentifier:(id)arg2 error:(id *)arg3;
- (BOOL)hasSavedTheme;
- (void)setCurrentTheme:(id)arg1;
- (id)currentTheme;
- (id)themeWithIdentifier:(id)arg1;
- (id)defaultTheme;
- (void)loadThemes:(id)arg1;
- (void)setNew:(BOOL)arg1 forClass:(Class)arg2;
- (BOOL)newForClass:(Class)arg1;
- (void)setNew:(BOOL)arg1 forEquipment:(id)arg2;
- (BOOL)newForEquipment:(id)arg1;
- (unsigned int)typeOfDirectory:(id)arg1;
- (id)pathForIdentifier:(id)arg1 rootDirectory:(id)arg2;
- (id)loadWithClass:(Class)arg1 digests:(id)arg2 originalArray:(id)arg3;
- (void)loadEquipments:(id)arg1;
- (void)saveEquipments;
- (id)digestsOfEquipments:(id)arg1;
- (void)dealloc;
- (id)init;

@end

