//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TaikoInputStream : NSObject
{
}

+ (id)inputStreamWithPath:(id)arg1;
+ (id)inputStreamWithData:(id)arg1;
- (unsigned long)size;
- (unsigned long)read:(void *)arg1 size:(unsigned long)arg2 count:(unsigned long)arg3;
- (int)seek:(long)arg1 whence:(int)arg2;

@end

