//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TaikoAction, UIView;

@interface TaikoSceneNode : NSObject
{
    struct _AGTEXTUREFRAMEGROUP *textureFrameGroup_;
    struct _AGOBJECT agobject_;
    UIView *superview_;
    TaikoAction *_action;
}

@property(retain, nonatomic) TaikoAction *action; // @synthesize action=_action;
@property(readonly, nonatomic) const struct _AGTEXTUREFRAME *frame;
- (void)renderRelativeToX:(float)arg1 y:(float)arg2;
- (void)render;
- (void)update;
- (void)setOrigin:(struct CGPoint)arg1;
@property(nonatomic) unsigned int frameIndex;
@property(nonatomic) struct _AGTEXTUREFRAMEGROUP *textureFrameGroup;
@property(nonatomic) unsigned int flags;
@property(nonatomic) unsigned int alpha;
@property(nonatomic) unsigned int color;
@property(nonatomic) float sy;
@property(nonatomic) float sx;
@property(nonatomic) BOOL hidden;
- (void)dealloc;
- (id)initWithTextureFrameGroup:(struct _AGTEXTUREFRAMEGROUP *)arg1;

@end

